-- create "devices" table
CREATE TABLE "devices" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NOT NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "device_tenant_id_name" to table: "devices"
CREATE UNIQUE INDEX "device_tenant_id_name" ON "devices" ("tenant_id", "name") WHERE (deleted_at IS NULL);
-- create "locations" table
CREATE TABLE "locations" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NOT NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "location_tenant_id_name" to table: "locations"
CREATE UNIQUE INDEX "location_tenant_id_name" ON "locations" ("tenant_id", "name") WHERE (deleted_at IS NULL);
-- create "device_locations" table
CREATE TABLE "device_locations" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NOT NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "device_id" uuid NOT NULL, "location_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "device_locations_devices_deviceLocationsDevice" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "device_locations_locations_deviceLocationsLocation" FOREIGN KEY ("location_id") REFERENCES "locations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create "device_users" table
CREATE TABLE "device_users" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NOT NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "device_id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "device_users_devices_deviceUsersDevice" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "device_users_users_deviceUsersUsers" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
