package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/pyck-ai/pyck/backend/common/datatype"
)

// DataTypeEntities is the resolver for the dataTypeEntities field.
func (r *queryResolver) DataTypeEntities(ctx context.Context) ([]string, error) {
	return datatype.DataTypeEntities(), nil
}
