package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqljson"
	"github.com/pyck-ai/pyck/backend/management/ent/gen"
	"github.com/pyck-ai/pyck/backend/management/ent/gen/location"
)

// Data is the resolver for the Data field.
func (r *locationWhereInputResolver) Data(ctx context.Context, obj *gen.LocationWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueEQ(location.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataHasKey is the resolver for the DataHasKey field.
func (r *locationWhereInputResolver) DataHasKey(ctx context.Context, obj *gen.LocationWhereInput, data *string) error {
	if obj == nil || data == nil {
		return nil
	}

	if *data != "" {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.HasKey(location.FieldData, sqljson.DotPath(*data)))
		})
	}
	return nil
}

// DataIn is the resolver for the DataIn field.
func (r *locationWhereInputResolver) DataIn(ctx context.Context, obj *gen.LocationWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) >= 2 {
		var args []any
		for _, v := range data[1:] {
			args = append(args, v)
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueIn(location.FieldData, args, sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataContains is the resolver for the DataContains field.
func (r *locationWhereInputResolver) DataContains(ctx context.Context, obj *gen.LocationWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueContains(location.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}
