package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/pyck-ai/pyck/backend/common/authn"
	mgmthandlers "github.com/pyck-ai/pyck/backend/management/handlers"
	"github.com/pyck-ai/pyck/backend/management/model"
)

// Organization is the resolver for the organization field. Wraps the
// local handlers.ResolveOrganization helper (two v2 SDK calls against
// the shared system zitadelConn) and enforces the system-user guard.
func (r *queryResolver) Organization(ctx context.Context, sub string) (*model.Organization, error) {
	if !authn.ForContext(ctx).IsSystemUser() {
		return nil, ErrOrganizationForbidden
	}
	result, err := mgmthandlers.ResolveOrganization(ctx, r.zitadelConn, sub)
	if err != nil {
		return nil, err
	}
	out := &model.Organization{Active: result.Active}
	if result.OrganizationID != "" {
		id := result.OrganizationID
		out.ID = &id
	}
	return out, nil
}
