package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/management/ent/gen"
)

// Policy is the resolver for the policy field.
func (r *queryResolver) Policy(ctx context.Context, id uuid.UUID) (*gen.AccessPolicy, error) {
	// Check authorization
	// if err := r.authorizer.MustEnforce(ctx, "management.policy", "read"); err != nil {
	// 	return nil, err
	// }

	return r.client.AccessPolicy.Get(ctx, id)
}
