package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/pyck-ai/pyck/backend/common/authn"
	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/common/serviceroles"
	"github.com/pyck-ai/pyck/backend/management/model"
)

// AssignRoles is the resolver for the assignRoles field.
func (r *mutationResolver) AssignRoles(ctx context.Context, input model.AssignRolesInput) (*model.AssignRolesResponse, error) {
	req := request.ForContext(ctx)

	if !req.User().IsAuthenticated() {
		return nil, fmt.Errorf("%w: authentication required for assignRoles", authn.ErrUnauthorized)
	}

	if !req.User().HasRole(authn.ROLE_ADMIN, input.TenantID) {
		return nil, fmt.Errorf("%w: admin role required for assignRoles", authn.ErrUnauthorized)
	}

	if len(input.Roles) == 0 {
		return nil, ErrNoRolesProvided
	}

	for _, key := range input.Roles {
		if !serviceroles.IsServiceRole(key) {
			return nil, fmt.Errorf("%w: %q", ErrNotAServiceRole, key)
		}
	}

	systemCtx := authn.Context(ctx, authn.SystemUser())
	orgID, zitadelUserID, err := r.resolveTenantUser(systemCtx, input.TenantID, input.UserID)
	if err != nil {
		return nil, err
	}

	roles, err := r.assignServiceRoles(ctx, orgID, zitadelUserID, input.Roles)
	if err != nil {
		return nil, err
	}

	return &model.AssignRolesResponse{UserID: input.UserID, Roles: roles}, nil
}

// RemoveRoles is the resolver for the removeRoles field.
func (r *mutationResolver) RemoveRoles(ctx context.Context, input model.RemoveRolesInput) (*model.RemoveRolesResponse, error) {
	req := request.ForContext(ctx)

	if !req.User().IsAuthenticated() {
		return nil, fmt.Errorf("%w: authentication required for removeRoles", authn.ErrUnauthorized)
	}

	if !req.User().HasRole(authn.ROLE_ADMIN, input.TenantID) {
		return nil, fmt.Errorf("%w: admin role required for removeRoles", authn.ErrUnauthorized)
	}

	if len(input.Roles) == 0 {
		return nil, ErrNoRolesProvided
	}

	for _, key := range input.Roles {
		if !serviceroles.IsServiceRole(key) {
			return nil, fmt.Errorf("%w: %q", ErrNotAServiceRole, key)
		}
	}

	systemCtx := authn.Context(ctx, authn.SystemUser())
	orgID, zitadelUserID, err := r.resolveTenantUser(systemCtx, input.TenantID, input.UserID)
	if err != nil {
		return nil, err
	}

	roles, err := r.removeServiceRoles(ctx, orgID, zitadelUserID, input.Roles)
	if err != nil {
		return nil, err
	}

	return &model.RemoveRolesResponse{UserID: input.UserID, Roles: roles}, nil
}

// ServiceRoles is the resolver for the serviceRoles field.
func (r *queryResolver) ServiceRoles(ctx context.Context) ([]*model.ServiceRole, error) {
	req := request.ForContext(ctx)
	if !req.User().IsAuthenticated() {
		return nil, fmt.Errorf("%w: authentication required for serviceRoles", authn.ErrUnauthorized)
	}
	if !req.User().HasRole(authn.ROLE_ADMIN, req.User().TenantID) {
		return nil, fmt.Errorf("%w: admin role required for serviceRoles", authn.ErrUnauthorized)
	}

	out := make([]*model.ServiceRole, 0, len(serviceroles.All))
	for _, sr := range serviceroles.All {
		out = append(out, &model.ServiceRole{
			Key: sr.String(),
		})
	}

	return out, nil
}

// UserServiceRoles is the resolver for the userServiceRoles field.
func (r *queryResolver) UserServiceRoles(ctx context.Context, input model.UserServiceRolesInput) ([]string, error) {
	req := request.ForContext(ctx)

	if !req.User().IsAuthenticated() {
		return nil, fmt.Errorf("%w: authentication required for userServiceRoles", authn.ErrUnauthorized)
	}

	if !req.User().HasRole(authn.ROLE_ADMIN, input.TenantID) {
		return nil, fmt.Errorf("%w: admin role required for userServiceRoles", authn.ErrUnauthorized)
	}

	systemCtx := authn.Context(ctx, authn.SystemUser())
	orgID, zitadelUserID, err := r.resolveTenantUser(systemCtx, input.TenantID, input.UserID)
	if err != nil {
		return nil, err
	}

	return r.listUserServiceRoles(ctx, orgID, zitadelUserID)
}
