// Code generated by "enumer -text -json -yaml -sql -gqlgen -typederrors -output=adapter_gen.go -type=AdapterType -linecomment"; DO NOT EDIT.

package config

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"io"
	"strconv"
	"strings"
)

const _AdapterTypeName = "invaliddefaultgrpcpostgres_listen"

var _AdapterTypeIndex = [...]uint8{0, 7, 14, 18, 33}

const _AdapterTypeLowerName = "invaliddefaultgrpcpostgres_listen"

func (i AdapterType) String() string {
	if i >= AdapterType(len(_AdapterTypeIndex)-1) {
		return fmt.Sprintf("AdapterType(%d)", i)
	}
	return _AdapterTypeName[_AdapterTypeIndex[i]:_AdapterTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AdapterTypeNoOp() {
	var x [1]struct{}
	_ = x[AdapterTypeInvalid-(0)]
	_ = x[AdapterTypeDefault-(1)]
	_ = x[AdapterTypeGRPC-(2)]
	_ = x[AdapterTypePostgresListen-(3)]
}

var _AdapterTypeValues = []AdapterType{AdapterTypeInvalid, AdapterTypeDefault, AdapterTypeGRPC, AdapterTypePostgresListen}

var _AdapterTypeNameToValueMap = map[string]AdapterType{
	_AdapterTypeName[0:7]:        AdapterTypeInvalid,
	_AdapterTypeLowerName[0:7]:   AdapterTypeInvalid,
	_AdapterTypeName[7:14]:       AdapterTypeDefault,
	_AdapterTypeLowerName[7:14]:  AdapterTypeDefault,
	_AdapterTypeName[14:18]:      AdapterTypeGRPC,
	_AdapterTypeLowerName[14:18]: AdapterTypeGRPC,
	_AdapterTypeName[18:33]:      AdapterTypePostgresListen,
	_AdapterTypeLowerName[18:33]: AdapterTypePostgresListen,
}

var _AdapterTypeNames = []string{
	_AdapterTypeName[0:7],
	_AdapterTypeName[7:14],
	_AdapterTypeName[14:18],
	_AdapterTypeName[18:33],
}

// AdapterTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AdapterTypeString(s string) (AdapterType, error) {
	if val, ok := _AdapterTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AdapterTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to AdapterType values", s))
}

// AdapterTypeValues returns all values of the enum
func AdapterTypeValues() []AdapterType {
	return _AdapterTypeValues
}

// AdapterTypeStrings returns a slice of all String values of the enum
func AdapterTypeStrings() []string {
	strs := make([]string, len(_AdapterTypeNames))
	copy(strs, _AdapterTypeNames)
	return strs
}

// IsAAdapterType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AdapterType) IsAAdapterType() bool {
	for _, v := range _AdapterTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AdapterType
func (i AdapterType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AdapterType
func (i *AdapterType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AdapterType should be a string, got %s", data)
	}

	var err error
	*i, err = AdapterTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AdapterType
func (i AdapterType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AdapterType
func (i *AdapterType) UnmarshalText(text []byte) error {
	var err error
	*i, err = AdapterTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for AdapterType
func (i AdapterType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for AdapterType
func (i *AdapterType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = AdapterTypeString(s)
	return err
}

func (i AdapterType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *AdapterType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of AdapterType: %[1]T(%[1]v)", value)
	}

	val, err := AdapterTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// MarshalGQL implements the graphql.Marshaler interface for AdapterType
func (i AdapterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for AdapterType
func (i *AdapterType) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("AdapterType should be a string, got %T", value)
	}

	var err error
	*i, err = AdapterTypeString(str)
	return err
}
