// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/workflow/ent/gen/workflowsignal"
)

type CurrentUserDataInput struct {
	ActivityIndex uint64              `json:"activityIndex"`
	ActivityCount *uint64             `json:"activityCount,omitempty"`
	Type          *WorkflowUpdateType `json:"type,omitempty"`
	Data          any                 `json:"data,omitempty"`
	Errors        []string            `json:"errors,omitempty"`
}

type GetWorkflowAssigneeInput struct {
	WorkflowID          string `json:"workflowId"`
	WorkflowExecutionID string `json:"workflowExecutionId"`
}

type GetWorkflowAssigneeResponse struct {
	Assignee string `json:"assignee"`
}

type RegisterWorkflowSignalInput struct {
	NatsTopic          string                            `json:"natsTopic"`
	TemporalSignal     string                            `json:"temporalSignal"`
	TemporalSignalType workflowsignal.TemporalSignalType `json:"temporalSignalType"`
	FilterRule         string                            `json:"filterRule"`
}

type RegisterWorkflowWithSignalsInput struct {
	DataTypeID   *uuid.UUID                     `json:"dataTypeID,omitempty"`
	DataTypeSlug *string                        `json:"dataTypeSlug,omitempty"`
	Data         map[string]any                 `json:"data,omitempty"`
	Name         string                         `json:"name"`
	TaskQueue    string                         `json:"taskQueue"`
	Signals      []*RegisterWorkflowSignalInput `json:"signals,omitempty"`
}

type ServiceInfo struct {
	Version string     `json:"version"`
	Date    *time.Time `json:"date,omitempty"`
}

type SetWorkflowAssigneeInput struct {
	WorkflowID          string     `json:"workflowId"`
	WorkflowExecutionID string     `json:"workflowExecutionId"`
	AssigneeID          *uuid.UUID `json:"assigneeID,omitempty"`
}

type SetWorkflowAssigneeResponse struct {
	Assignee string `json:"assignee"`
}

type SubmitUserDataInputInput struct {
	ID            *string `json:"id,omitempty"`
	Name          string  `json:"name"`
	Data          any     `json:"data"`
	WorkflowID    string  `json:"workflowID"`
	WorkflowRunID string  `json:"workflowRunID"`
}

type SubmitUserDataInputResponse struct {
	Workflow *TemporalWorkflow `json:"workflow,omitempty"`
	Result   map[string]any    `json:"result,omitempty"`
}

type TemporalMetadata struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TemporalWorkflow struct {
	Type  string `json:"type"`
	ID    string `json:"id"`
	RunID string `json:"runID"`
}

type UserDataInputQueryInput struct {
	WorkflowID          string `json:"workflowID"`
	WorkflowExecutionID string `json:"workflowExecutionID"`
}

type WorkflowDeletePayload struct {
	DeletedID *uuid.UUID `json:"deletedID,omitempty"`
}

type WorkflowEvent struct {
	EventID   int            `json:"eventId"`
	EventTime string         `json:"eventTime"`
	EventType string         `json:"eventType"`
	Extra     map[string]any `json:"extra,omitempty"`
}

type WorkflowExecution struct {
	WorkflowID string `json:"workflowId"`
	ID         string `json:"id"`
}

// Workflow execution with its history.
// Used for history retrieval via workflowHistory query.
type WorkflowExecutionHistory struct {
	// The workflow execution identifier.
	Execution *WorkflowExecution `json:"execution"`
	// The workflow type name.
	TypeName string `json:"typeName"`
	// All history events for this execution.
	History []*WorkflowEvent `json:"history"`
}

// A connection to a list of WorkflowExecutionHistory items.
type WorkflowExecutionHistoryConnection struct {
	// A list of edges.
	Edges []*WorkflowExecutionHistoryEdge `json:"edges"`
	// Information to aid in pagination.
	PageInfo *WorkflowPageInfo `json:"pageInfo"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// An edge in a WorkflowExecutionHistory connection.
type WorkflowExecutionHistoryEdge struct {
	// The item at the end of the edge.
	Node *WorkflowExecutionHistory `json:"node"`
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
}

// Information about a workflow execution.
// History is not included in list responses for performance.
// Use workflowHistory query to fetch history for specific executions.
type WorkflowExecutionInfo struct {
	// The workflow execution identifier (workflowId and runId).
	Execution *WorkflowExecution `json:"execution"`
	// The workflow type.
	Type *WorkflowType `json:"type"`
	// The time when the workflow started.
	StartTime string `json:"startTime"`
	// The time when the workflow completed (null if still running).
	CloseTime *string `json:"closeTime,omitempty"`
	// The current status of the workflow execution.
	Status string `json:"status"`
	// The number of events in the workflow history.
	HistoryLength int `json:"historyLength"`
	// The parent namespace ID if this is a child workflow.
	ParentNamespaceID *string `json:"parentNamespaceId,omitempty"`
	// The parent execution if this is a child workflow.
	ParentExecution *WorkflowExecution `json:"parentExecution,omitempty"`
	// The time when the workflow was scheduled to execute.
	ExecutionTime *string `json:"executionTime,omitempty"`
	// Custom memo data attached to the workflow.
	Memo *WorkflowMemo `json:"memo,omitempty"`
	// Search attributes for querying workflows.
	SearchAttributes []*TemporalMetadata `json:"searchAttributes"`
	// Auto reset points for the workflow.
	AutoResetPoints map[string]any `json:"autoResetPoints,omitempty"`
	// The task queue where the workflow is executed.
	TaskQueue string `json:"taskQueue"`
	// The number of state transitions in the workflow.
	StateTransitionCount int `json:"stateTransitionCount"`
	// The size of the workflow history in bytes.
	HistorySizeBytes int `json:"historySizeBytes"`
	// The version stamp of the most recent worker.
	MostRecentWorkerVersionStamp map[string]any `json:"mostRecentWorkerVersionStamp,omitempty"`
	// The duration of the workflow execution.
	ExecutionDuration *string `json:"executionDuration,omitempty"`
	// The root execution if this is part of a workflow chain.
	RootExecution *WorkflowExecution `json:"rootExecution,omitempty"`
}

// A connection to a list of WorkflowExecutionInfo items.
type WorkflowExecutionInfoConnection struct {
	// A list of edges.
	Edges []*WorkflowExecutionInfoEdge `json:"edges"`
	// Information to aid in pagination.
	PageInfo *WorkflowExecutionPageInfo `json:"pageInfo"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// An edge in a WorkflowExecutionInfo connection.
type WorkflowExecutionInfoEdge struct {
	// The item at the end of the edge.
	Node *WorkflowExecutionInfo `json:"node"`
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
}

// Ordering options for WorkflowExecution connections.
type WorkflowExecutionOrder struct {
	// The ordering direction.
	Direction WorkflowExecutionOrderDirection `json:"direction"`
	// The field by which to order WorkflowExecutions.
	Field WorkflowExecutionOrderField `json:"field"`
}

// Information about pagination in a connection.
type WorkflowExecutionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue.
	StartCursor *string `json:"startCursor,omitempty"`
	// When paginating forwards, the cursor to continue.
	EndCursor *string `json:"endCursor,omitempty"`
}

type WorkflowExecutionsWhereInput struct {
	Not *WorkflowExecutionsWhereInput   `json:"not,omitempty"`
	And []*WorkflowExecutionsWhereInput `json:"and,omitempty"`
	Or  []*WorkflowExecutionsWhereInput `json:"or,omitempty"`
	// type_name field predicates
	TypeName             *string  `json:"typeName,omitempty"`
	TypeNameNeq          *string  `json:"typeNameNEQ,omitempty"`
	TypeNameIn           []string `json:"typeNameIn,omitempty"`
	TypeNameNotIn        []string `json:"typeNameNotIn,omitempty"`
	TypeNameContains     *string  `json:"typeNameContains,omitempty"`
	TypeNameHasPrefix    *string  `json:"typeNameHasPrefix,omitempty"`
	TypeNameHasSuffix    *string  `json:"typeNameHasSuffix,omitempty"`
	TypeNameEqualFold    *string  `json:"typeNameEqualFold,omitempty"`
	TypeNameContainsFold *string  `json:"typeNameContainsFold,omitempty"`
	// workflow_name field predicates
	WorkflowName             *string  `json:"workflowName,omitempty"`
	WorkflowNameNeq          *string  `json:"workflowNameNEQ,omitempty"`
	WorkflowNameIn           []string `json:"workflowNameIn,omitempty"`
	WorkflowNameNotIn        []string `json:"workflowNameNotIn,omitempty"`
	WorkflowNameContains     *string  `json:"workflowNameContains,omitempty"`
	WorkflowNameHasPrefix    *string  `json:"workflowNameHasPrefix,omitempty"`
	WorkflowNameHasSuffix    *string  `json:"workflowNameHasSuffix,omitempty"`
	WorkflowNameEqualFold    *string  `json:"workflowNameEqualFold,omitempty"`
	WorkflowNameContainsFold *string  `json:"workflowNameContainsFold,omitempty"`
	// assignee field predicates
	Assignee             *string  `json:"assignee,omitempty"`
	AssigneeNeq          *string  `json:"assigneeNEQ,omitempty"`
	AssigneeIn           []string `json:"assigneeIn,omitempty"`
	AssigneeNotIn        []string `json:"assigneeNotIn,omitempty"`
	AssigneeIsNil        *bool    `json:"assigneeIsNil,omitempty"`
	AssigneeNotNil       *bool    `json:"assigneeNotNil,omitempty"`
	AssigneeContains     *string  `json:"assigneeContains,omitempty"`
	AssigneeHasPrefix    *string  `json:"assigneeHasPrefix,omitempty"`
	AssigneeHasSuffix    *string  `json:"assigneeHasSuffix,omitempty"`
	AssigneeEqualFold    *string  `json:"assigneeEqualFold,omitempty"`
	AssigneeContainsFold *string  `json:"assigneeContainsFold,omitempty"`
	// group_by field predicates
	GroupBy             *string  `json:"groupBy,omitempty"`
	GroupByNeq          *string  `json:"groupByNEQ,omitempty"`
	GroupByIn           []string `json:"groupByIn,omitempty"`
	GroupByNotIn        []string `json:"groupByNotIn,omitempty"`
	GroupByIsNil        *bool    `json:"groupByIsNil,omitempty"`
	GroupByNotNil       *bool    `json:"groupByNotNil,omitempty"`
	GroupByContains     *string  `json:"groupByContains,omitempty"`
	GroupByHasPrefix    *string  `json:"groupByHasPrefix,omitempty"`
	GroupByHasSuffix    *string  `json:"groupByHasSuffix,omitempty"`
	GroupByEqualFold    *string  `json:"groupByEqualFold,omitempty"`
	GroupByContainsFold *string  `json:"groupByContainsFold,omitempty"`
	// workflow_id field predicates
	WorkflowID             *string  `json:"workflowID,omitempty"`
	WorkflowIdneq          *string  `json:"workflowIDNEQ,omitempty"`
	WorkflowIDIn           []string `json:"workflowIDIn,omitempty"`
	WorkflowIDNotIn        []string `json:"workflowIDNotIn,omitempty"`
	WorkflowIDContains     *string  `json:"workflowIDContains,omitempty"`
	WorkflowIDHasPrefix    *string  `json:"workflowIDHasPrefix,omitempty"`
	WorkflowIDHasSuffix    *string  `json:"workflowIDHasSuffix,omitempty"`
	WorkflowIDEqualFold    *string  `json:"workflowIDEqualFold,omitempty"`
	WorkflowIDContainsFold *string  `json:"workflowIDContainsFold,omitempty"`
	// run_id field predicates
	RunID             *string  `json:"runID,omitempty"`
	RunIdneq          *string  `json:"runIDNEQ,omitempty"`
	RunIDIn           []string `json:"runIDIn,omitempty"`
	RunIDNotIn        []string `json:"runIDNotIn,omitempty"`
	RunIDContains     *string  `json:"runIDContains,omitempty"`
	RunIDHasPrefix    *string  `json:"runIDHasPrefix,omitempty"`
	RunIDHasSuffix    *string  `json:"runIDHasSuffix,omitempty"`
	RunIDEqualFold    *string  `json:"runIDEqualFold,omitempty"`
	RunIDContainsFold *string  `json:"runIDContainsFold,omitempty"`
	// status field predicates
	Status             *string  `json:"status,omitempty"`
	StatusNeq          *string  `json:"statusNEQ,omitempty"`
	StatusIn           []string `json:"statusIn,omitempty"`
	StatusNotIn        []string `json:"statusNotIn,omitempty"`
	StatusContains     *string  `json:"statusContains,omitempty"`
	StatusHasPrefix    *string  `json:"statusHasPrefix,omitempty"`
	StatusHasSuffix    *string  `json:"statusHasSuffix,omitempty"`
	StatusEqualFold    *string  `json:"statusEqualFold,omitempty"`
	StatusContainsFold *string  `json:"statusContainsFold,omitempty"`
	// start_time field predicates
	StartTime      *string  `json:"startTime,omitempty"`
	StartTimeNeq   *string  `json:"startTimeNEQ,omitempty"`
	StartTimeIn    []string `json:"startTimeIn,omitempty"`
	StartTimeNotIn []string `json:"startTimeNotIn,omitempty"`
	StartTimeGt    *string  `json:"startTimeGT,omitempty"`
	StartTimeGte   *string  `json:"startTimeGTE,omitempty"`
	StartTimeLt    *string  `json:"startTimeLT,omitempty"`
	StartTimeLte   *string  `json:"startTimeLTE,omitempty"`
	// close_time field predicates
	CloseTime       *string  `json:"closeTime,omitempty"`
	CloseTimeNeq    *string  `json:"closeTimeNEQ,omitempty"`
	CloseTimeIn     []string `json:"closeTimeIn,omitempty"`
	CloseTimeNotIn  []string `json:"closeTimeNotIn,omitempty"`
	CloseTimeGt     *string  `json:"closeTimeGT,omitempty"`
	CloseTimeGte    *string  `json:"closeTimeGTE,omitempty"`
	CloseTimeLt     *string  `json:"closeTimeLT,omitempty"`
	CloseTimeLte    *string  `json:"closeTimeLTE,omitempty"`
	CloseTimeIsNil  *bool    `json:"closeTimeIsNil,omitempty"`
	CloseTimeNotNil *bool    `json:"closeTimeNotNil,omitempty"`
	// service field predicates
	Service             *string  `json:"service,omitempty"`
	ServiceNeq          *string  `json:"serviceNEQ,omitempty"`
	ServiceIn           []string `json:"serviceIn,omitempty"`
	ServiceNotIn        []string `json:"serviceNotIn,omitempty"`
	ServiceContains     *string  `json:"serviceContains,omitempty"`
	ServiceHasPrefix    *string  `json:"serviceHasPrefix,omitempty"`
	ServiceHasSuffix    *string  `json:"serviceHasSuffix,omitempty"`
	ServiceEqualFold    *string  `json:"serviceEqualFold,omitempty"`
	ServiceContainsFold *string  `json:"serviceContainsFold,omitempty"`
	ServiceIsNil        *bool    `json:"serviceIsNil,omitempty"`
	ServiceNotNil       *bool    `json:"serviceNotNil,omitempty"`
	// dataType field predicates
	DataType             *string  `json:"dataType,omitempty"`
	DataTypeNeq          *string  `json:"dataTypeNEQ,omitempty"`
	DataTypeIn           []string `json:"dataTypeIn,omitempty"`
	DataTypeNotIn        []string `json:"dataTypeNotIn,omitempty"`
	DataTypeContains     *string  `json:"dataTypeContains,omitempty"`
	DataTypeHasPrefix    *string  `json:"dataTypeHasPrefix,omitempty"`
	DataTypeHasSuffix    *string  `json:"dataTypeHasSuffix,omitempty"`
	DataTypeEqualFold    *string  `json:"dataTypeEqualFold,omitempty"`
	DataTypeContainsFold *string  `json:"dataTypeContainsFold,omitempty"`
	DataTypeIsNil        *bool    `json:"dataTypeIsNil,omitempty"`
	DataTypeNotNil       *bool    `json:"dataTypeNotNil,omitempty"`
	// dataId field predicates
	DataID             *string  `json:"dataId,omitempty"`
	DataIDNeq          *string  `json:"dataIdNEQ,omitempty"`
	DataIDIn           []string `json:"dataIdIn,omitempty"`
	DataIDNotIn        []string `json:"dataIdNotIn,omitempty"`
	DataIDContains     *string  `json:"dataIdContains,omitempty"`
	DataIDHasPrefix    *string  `json:"dataIdHasPrefix,omitempty"`
	DataIDHasSuffix    *string  `json:"dataIdHasSuffix,omitempty"`
	DataIDEqualFold    *string  `json:"dataIdEqualFold,omitempty"`
	DataIDContainsFold *string  `json:"dataIdContainsFold,omitempty"`
	DataIDIsNil        *bool    `json:"dataIdIsNil,omitempty"`
	DataIDNotNil       *bool    `json:"dataIdNotNil,omitempty"`
}

type WorkflowMemo struct {
	Title    *string        `json:"title,omitempty"`
	Subtitle *string        `json:"subtitle,omitempty"`
	Data     map[string]any `json:"data,omitempty"`
}

// Page info for workflow connections.
type WorkflowPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue.
	StartCursor *string `json:"startCursor,omitempty"`
	// When paginating forwards, the cursor to continue.
	EndCursor *string `json:"endCursor,omitempty"`
}

type WorkflowType struct {
	Name string `json:"name"`
}

type WorkflowUpdateType struct {
	ID     string `json:"id"`
	Schema any    `json:"schema,omitempty"`
}

// Possible directions in which to order a list of items.
type WorkflowExecutionOrderDirection string

const (
	// Specifies an ascending order.
	WorkflowExecutionOrderDirectionAsc WorkflowExecutionOrderDirection = "ASC"
	// Specifies a descending order.
	WorkflowExecutionOrderDirectionDesc WorkflowExecutionOrderDirection = "DESC"
)

var AllWorkflowExecutionOrderDirection = []WorkflowExecutionOrderDirection{
	WorkflowExecutionOrderDirectionAsc,
	WorkflowExecutionOrderDirectionDesc,
}

func (e WorkflowExecutionOrderDirection) IsValid() bool {
	switch e {
	case WorkflowExecutionOrderDirectionAsc, WorkflowExecutionOrderDirectionDesc:
		return true
	}
	return false
}

func (e WorkflowExecutionOrderDirection) String() string {
	return string(e)
}

func (e *WorkflowExecutionOrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowExecutionOrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowExecutionOrderDirection", str)
	}
	return nil
}

func (e WorkflowExecutionOrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowExecutionOrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowExecutionOrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Properties by which WorkflowExecution connections can be ordered.
type WorkflowExecutionOrderField string

const (
	// Order by start time.
	WorkflowExecutionOrderFieldStartTime WorkflowExecutionOrderField = "START_TIME"
	// Order by close time.
	WorkflowExecutionOrderFieldCloseTime WorkflowExecutionOrderField = "CLOSE_TIME"
	// Order by workflow ID.
	WorkflowExecutionOrderFieldWorkflowID WorkflowExecutionOrderField = "WORKFLOW_ID"
	// Order by status.
	WorkflowExecutionOrderFieldStatus WorkflowExecutionOrderField = "STATUS"
)

var AllWorkflowExecutionOrderField = []WorkflowExecutionOrderField{
	WorkflowExecutionOrderFieldStartTime,
	WorkflowExecutionOrderFieldCloseTime,
	WorkflowExecutionOrderFieldWorkflowID,
	WorkflowExecutionOrderFieldStatus,
}

func (e WorkflowExecutionOrderField) IsValid() bool {
	switch e {
	case WorkflowExecutionOrderFieldStartTime, WorkflowExecutionOrderFieldCloseTime, WorkflowExecutionOrderFieldWorkflowID, WorkflowExecutionOrderFieldStatus:
		return true
	}
	return false
}

func (e WorkflowExecutionOrderField) String() string {
	return string(e)
}

func (e *WorkflowExecutionOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowExecutionOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowExecutionOrderField", str)
	}
	return nil
}

func (e WorkflowExecutionOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowExecutionOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowExecutionOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
