-- create "collection_movements" table
CREATE TABLE "collection_movements" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "handler" character varying NULL, "assignee" character varying NULL, "assignment_date" timestamptz NULL, PRIMARY KEY ("id"));
-- create "items" table
CREATE TABLE "items" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "sku" character varying NOT NULL, "inventory_json_data" jsonb NULL, PRIMARY KEY ("id"));
-- create index "item_tenant_id_sku_deleted_at" to table: "items"
CREATE UNIQUE INDEX "item_tenant_id_sku_deleted_at" ON "items" ("tenant_id", "sku", "deleted_at");
-- create "repositories" table
CREATE TABLE "repositories" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "parent_id" uuid NULL, "name" character varying NOT NULL, "layout" character varying NULL, "type" character varying NOT NULL, "virtual_repo" boolean NULL DEFAULT false, PRIMARY KEY ("id"));
-- create index "repository_tenant_id_name_deleted_at" to table: "repositories"
CREATE UNIQUE INDEX "repository_tenant_id_name_deleted_at" ON "repositories" ("tenant_id", "name", "deleted_at");
-- create "item_movements" table
CREATE TABLE "item_movements" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "quantity" bigint NOT NULL, "executed" boolean NULL DEFAULT false, "executed_at" timestamptz NULL, "handler" character varying NOT NULL, "blocked_by" character varying NULL, "collection_id" uuid NULL, "order_id" uuid NULL, "position" bigint NULL DEFAULT 0, "item_id" uuid NOT NULL, "to_id" uuid NOT NULL, "from_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "item_movements_items_itemMovementItems" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "item_movements_repositories_itemMovementFromRepositories" FOREIGN KEY ("from_id") REFERENCES "repositories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "item_movements_repositories_itemMovementToRepositories" FOREIGN KEY ("to_id") REFERENCES "repositories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create "item_sets" table
CREATE TABLE "item_sets" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "sku" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "itemset_tenant_id_sku_deleted_at" to table: "item_sets"
CREATE UNIQUE INDEX "itemset_tenant_id_sku_deleted_at" ON "item_sets" ("tenant_id", "sku", "deleted_at");
-- create "item_set_items" table
CREATE TABLE "item_set_items" ("item_set_id" uuid NOT NULL, "item_id" uuid NOT NULL, PRIMARY KEY ("item_set_id", "item_id"), CONSTRAINT "item_set_items_item_id" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "item_set_items_item_set_id" FOREIGN KEY ("item_set_id") REFERENCES "item_sets" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "repository_movements" table
CREATE TABLE "repository_movements" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "data_type_id" uuid NULL, "data_type_slug" character varying NULL, "data" jsonb NULL, "executed" boolean NULL DEFAULT false, "executed_at" timestamptz NULL, "handler" character varying NOT NULL, "blocked_by" character varying NULL, "collection_id" uuid NULL, "order_id" uuid NULL, "position" bigint NULL DEFAULT 0, "to_id" uuid NOT NULL, "from_id" uuid NULL, "repository_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "repository_movements_repositor_11724da7a5861a4e46d24739de833291" FOREIGN KEY ("to_id") REFERENCES "repositories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "repository_movements_repositor_56391c4246886e79cff2713ee6736783" FOREIGN KEY ("from_id") REFERENCES "repositories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "repository_movements_repositor_68ea1e3f96a5722a1c2bb352ca28f23e" FOREIGN KEY ("repository_id") REFERENCES "repositories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create "stocks" table
CREATE TABLE "stocks" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "quantity" bigint NOT NULL, "movement_id" uuid NULL, "incoming_stock" bigint NOT NULL DEFAULT 0, "outgoing_stock" bigint NOT NULL DEFAULT 0, "own_quantity" bigint NOT NULL DEFAULT 0, "own_incoming_stock" bigint NOT NULL DEFAULT 0, "own_outgoing_stock" bigint NOT NULL DEFAULT 0, "item_id" uuid NOT NULL, "repository_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "stocks_items_itemStocks" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "stocks_repositories_repositoryStocks" FOREIGN KEY ("repository_id") REFERENCES "repositories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create "transactions" table
CREATE TABLE "transactions" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "created_by" uuid NULL, "updated_at" timestamptz NULL, "updated_by" uuid NULL, "deleted_at" timestamptz NULL, "deleted_by" uuid NULL, "quantity" bigint NOT NULL, "type" character varying NOT NULL, "item_id" uuid NOT NULL, "repository_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "transactions_items_itemTransactions" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "transactions_repositories_repositoryTransactions" FOREIGN KEY ("repository_id") REFERENCES "repositories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
