-- reverse: set comment to column: "request_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."request_id" IS 'Server-generated request ID from OTel baggage. Observability only.';
-- reverse: set comment to column: "trace_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."trace_id" IS 'OpenTelemetry trace ID at row emission. Observability only.';
-- reverse: set comment to column: "transaction_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."transaction_id" IS 'Per-DB-transaction UUID v7 generated by gqltx at BeginTx. Used as the NATS message ID component for tx-scoped, restart-safe deduplication.';
-- reverse: create index "entityeventsoutbox_transaction_id_created_at" to table: "event_outbox"
DROP INDEX "entityeventsoutbox_transaction_id_created_at";
-- reverse: create index "entityeventsoutbox_next_retry_at_transaction_id_created_at" to table: "event_outbox"
DROP INDEX "entityeventsoutbox_next_retry_at_transaction_id_created_at";
-- reverse: drop index "idx_event_outbox_transaction" from table: "event_outbox"
CREATE INDEX "idx_event_outbox_transaction" ON "event_outbox" ("transaction_id", "created_at") WHERE ((published_at IS NULL) AND (dead_at IS NULL));
-- reverse: drop index "idx_event_outbox_polling_v2" from table: "event_outbox"
CREATE INDEX "idx_event_outbox_polling_v2" ON "event_outbox" ("next_retry_at" NULLS FIRST, "transaction_id", "created_at") WHERE ((published_at IS NULL) AND (dead_at IS NULL));
