-- reverse: create index "outboundshipmentnotification_tenant_id" to table: "outbound-shipment-notifications"
DROP INDEX "outboundshipmentnotification_tenant_id";
-- reverse: create index "outboundshipmentnotification_order_id" to table: "outbound-shipment-notifications"
DROP INDEX "outboundshipmentnotification_order_id";
-- reverse: modify "outbound-shipment-notifications" table
ALTER TABLE "outbound-shipment-notifications" DROP CONSTRAINT "outbound-shipment-notification_1f06f5df312d77b94b8653b8ac4948a5", ALTER COLUMN "created_by" DROP NOT NULL, ADD CONSTRAINT "outbound-shipment-notifications_orders_outboundShipmentNotifica" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- reverse: drop index "idx_outbound_shipment_notifications_tenant_id" from table: "outbound-shipment-notifications"
CREATE INDEX "idx_outbound_shipment_notifications_tenant_id" ON "outbound-shipment-notifications" ("tenant_id");
-- reverse: drop index "idx_outbound_shipment_notifications_order_id" from table: "outbound-shipment-notifications"
CREATE INDEX "idx_outbound_shipment_notifications_order_id" ON "outbound-shipment-notifications" ("order_id");
-- reverse: set comment to column: "request_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."request_id" IS 'Server-generated request ID from OTel baggage. Observability only.';
-- reverse: set comment to column: "trace_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."trace_id" IS 'OpenTelemetry trace ID at row emission. Observability only.';
-- reverse: set comment to column: "transaction_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."transaction_id" IS 'Per-DB-transaction UUID v7 generated by gqltx at BeginTx. Used as the NATS message ID component for tx-scoped, restart-safe deduplication.';
-- reverse: set comment to column: "tenant_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."tenant_id" IS 'Tenant UUID extracted from payload for filtering.';
-- reverse: set comment to column: "entity_id" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."entity_id" IS 'Entity UUID extracted from payload for filtering.';
-- reverse: set comment to column: "entity_type" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."entity_type" IS 'Ent schema name (e.g., Item, Location) extracted from payload for filtering.';
-- reverse: set comment to column: "next_retry_at" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."next_retry_at" IS 'Earliest time for next retry. NULL = immediately eligible. Set to NOW() + LEAST(2^retry_count, 3600) seconds on failure.';
-- reverse: set comment to column: "dead_at" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."dead_at" IS 'When set, marks the correlation group as dead for manual cleanup';
-- reverse: set comment to column: "retry_count" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."retry_count" IS 'Number of failed publish attempts, entry skipped after max retries';
-- reverse: set comment to column: "with_reply" on table: "event_outbox"
COMMENT ON COLUMN "event_outbox"."with_reply" IS 'When true, OutboxHandler waits for workflow IDs in NATS reply';
-- reverse: set comment to table: "event_outbox"
COMMENT ON TABLE "event_outbox" IS 'Transactional outbox for reliable event publishing to NATS';
-- reverse: create index "entityeventsoutbox_user_id_created_at" to table: "event_outbox"
DROP INDEX "entityeventsoutbox_user_id_created_at";
-- reverse: create index "entityeventsoutbox_transaction_id_created_at" to table: "event_outbox"
DROP INDEX "entityeventsoutbox_transaction_id_created_at";
-- reverse: create index "entityeventsoutbox_tenant_id_created_at" to table: "event_outbox"
DROP INDEX "entityeventsoutbox_tenant_id_created_at";
-- reverse: create index "entityeventsoutbox_next_retry_at_transaction_id_created_at" to table: "event_outbox"
DROP INDEX "entityeventsoutbox_next_retry_at_transaction_id_created_at";
-- reverse: modify "event_outbox" table
ALTER TABLE "event_outbox" ALTER COLUMN "retry_count" TYPE integer, ALTER COLUMN "created_at" SET DEFAULT now();
-- reverse: drop index "idx_event_outbox_user_created" from table: "event_outbox"
CREATE INDEX "idx_event_outbox_user_created" ON "event_outbox" ("user_id", "created_at");
-- reverse: drop index "idx_event_outbox_transaction" from table: "event_outbox"
CREATE INDEX "idx_event_outbox_transaction" ON "event_outbox" ("transaction_id", "created_at") WHERE ((published_at IS NULL) AND (dead_at IS NULL));
-- reverse: drop index "idx_event_outbox_tenant" from table: "event_outbox"
CREATE INDEX "idx_event_outbox_tenant" ON "event_outbox" ("tenant_id", "created_at") WHERE ((published_at IS NULL) AND (dead_at IS NULL));
-- reverse: drop index "idx_event_outbox_polling_v2" from table: "event_outbox"
CREATE INDEX "idx_event_outbox_polling_v2" ON "event_outbox" ("next_retry_at" NULLS FIRST, "transaction_id", "created_at") WHERE ((published_at IS NULL) AND (dead_at IS NULL));
