services:
  inventory:
    container_name: pyck-inventory
    build:
      context: ../../../
      dockerfile: ./backend/Dockerfile
      args:
        - SERVICE_NAME=inventory
        - SERVICE_PORT=8084
      network: host
    restart: always
    env_file:
      - path: ../../../config/keys/bootstrap.env
      - path: ../../../.env
      - path: ../../../.env.local
        required: false
    volumes:
      - ./../../../:/src:ro,z
      - ./../../../backend/inventory/ent/migrate/migrations/:/app/inventory/ent/migrate/migrations/:z
      - ./../../keys/:/data/keys/:ro,z
    ports:
      - "7084:7084"
      - "8084:8084"
    depends_on:
      gateway: { condition: service_healthy }
      management: { condition: service_healthy }
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8084"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 64M
