services:
  main-data:
    container_name: main-data
    build:
      context: ../../../
      dockerfile: ./backend/Dockerfile.debug
      args:
        - SERVICE_NAME=main-data
        - SERVICE_PORT=8081
        - DELVE_PORT=7081
    security_opt:
      - "apparmor:unconfined" # required for debugging with delve
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - go_cache:/var/cache/go/
      - go_modcache:/go/pkg/mod/
      - ./../../../backend/:/app/:ro,z
      - ./../../../backend/main-data/.var/debug/:/tmp/debug/:Z
      - ./../../keys/:/data/keys/:ro,z
    environment:
      - PYCK_LOG_FORMAT=console
      - PYCK_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    deploy:
      resources:
        limits:
          memory: '1G'
