services:
  management:
    container_name: pyck-management
    build:
      context: ../../../
      dockerfile: ./backend/Dockerfile
      args:
        - SERVICE_NAME=management
        - SERVICE_PORT=8082
      network: host
    restart: on-failure
    environment:
      - PYCK_BOOTSTRAP_TIMEOUT=10m
      - PYCK_BOOTSTRAP_ENABLED=true
      - PYCK_BOOTSTRAP_ONLY=false
      - PYCK_BOOTSTRAP_MODULE=temporal
    env_file:
      - path: ../../../config/keys/bootstrap.env
      - path: ../../../.env
      - path: ../../../.env.local
        required: false
    volumes:
      - ./../../../:/src:ro,z
      - ./../../../backend/management/ent/migrate/migrations/:/app/management/ent/migrate/migrations/:z
      - ./../../keys/:/data/keys/:ro,z
    ports:
      - "7082:7082"
      - "8082:8082"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8082"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      temporal: { condition: service_healthy }
