services:
  picking:
    container_name: picking
    build:
      context: ../../../
      dockerfile: ./backend/Dockerfile.debug
      args:
        - SERVICE_NAME=picking
        - SERVICE_PORT=8086
        - DELVE_PORT=7086
    security_opt:
      - "apparmor:unconfined" # required for debugging with delve
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - go_cache:/var/cache/go/
      - go_modcache:/go/pkg/mod/
      - ./../../../backend/:/app/:ro,z
      - ./../../../backend/picking/.var/debug/:/tmp/debug/:Z
      - ./../../../backend/picking/ent/migrate/migrations/:/app/picking/ent/migrate/migrations/:z
      - ./../../keys/:/data/keys/:ro,z
    environment:
      - PYCK_LOG_FORMAT=console
      - PYCK_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - PYCK_SERVICES_PATH=/app
    deploy:
      resources:
        limits:
          memory: '1G'
