services:
  receiving:
    container_name: receiving
    build:
      context: ../../../
      dockerfile: ./backend/Dockerfile.debug
      args:
        - SERVICE_NAME=receiving
        - SERVICE_PORT=8087
        - DELVE_PORT=7087
    security_opt:
      - "apparmor:unconfined" # required for debugging with delve
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - go_cache:/var/cache/go/
      - go_modcache:/go/pkg/mod/
      - ./../../../backend/:/app/:ro,z
      - ./../../../backend/receiving/.var/debug/:/tmp/debug/:Z
      - ./../../../backend/receiving/ent/migrate/migrations/:/app/receiving/ent/migrate/migrations/:z
      - ./../../keys/zitadel_certificate.crt:/etc/ssl/certs/zitadel.crt:ro,z
      - ./../../keys/local-key.json:/data/keys/local-key.json:ro,z
    environment:
      - PYCK_LOG_FORMAT=console
      - PYCK_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - PYCK_SERVICES_PATH=/app
    deploy:
      resources:
        limits:
          memory: '1G'
