// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package internal

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/workflow/ent/gen/workflowsignal"
)

// Ordering options for Workflow connections
type WorkflowOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order Workflows.
	Field *WorkflowOrderField `json:"field,omitempty"`
	// Dot-notation path into a JSONB column (e.g. "meta.weight").
	JSONPath *string `json:"jsonPath,omitempty"`
	// Cast type for the extracted JSONB value.
	JSONType *JSONType `json:"jsonType,omitempty"`
}

// Ordering options for WorkflowSignal connections
type WorkflowSignalOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order WorkflowSignals.
	Field *WorkflowSignalOrderField `json:"field,omitempty"`
	// Dot-notation path into a JSONB column (e.g. "meta.weight").
	JSONPath *string `json:"jsonPath,omitempty"`
	// Cast type for the extracted JSONB value.
	JSONType *JSONType `json:"jsonType,omitempty"`
}

// WorkflowSignalWhereInput is used for filtering WorkflowSignal objects.
// Input was generated by ent.
type WorkflowSignalWhereInput struct {
	Not *WorkflowSignalWhereInput   `json:"not,omitempty"`
	And []*WorkflowSignalWhereInput `json:"and,omitempty"`
	Or  []*WorkflowSignalWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *string  `json:"id,omitempty"`
	IDNeq   *string  `json:"idNEQ,omitempty"`
	IDIn    []string `json:"idIn,omitempty"`
	IDNotIn []string `json:"idNotIn,omitempty"`
	IDGt    *string  `json:"idGT,omitempty"`
	IDGte   *string  `json:"idGTE,omitempty"`
	IDLt    *string  `json:"idLT,omitempty"`
	IDLte   *string  `json:"idLTE,omitempty"`
	// tenant_id field predicates
	TenantID      *uuid.UUID  `json:"tenantID,omitempty"`
	TenantIdneq   *uuid.UUID  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn    []uuid.UUID `json:"tenantIDIn,omitempty"`
	TenantIDNotIn []uuid.UUID `json:"tenantIDNotIn,omitempty"`
	TenantIdgt    *uuid.UUID  `json:"tenantIDGT,omitempty"`
	TenantIdgte   *uuid.UUID  `json:"tenantIDGTE,omitempty"`
	TenantIdlt    *uuid.UUID  `json:"tenantIDLT,omitempty"`
	TenantIdlte   *uuid.UUID  `json:"tenantIDLTE,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// created_by field predicates
	CreatedBy      *uuid.UUID  `json:"createdBy,omitempty"`
	CreatedByNeq   *uuid.UUID  `json:"createdByNEQ,omitempty"`
	CreatedByIn    []uuid.UUID `json:"createdByIn,omitempty"`
	CreatedByNotIn []uuid.UUID `json:"createdByNotIn,omitempty"`
	CreatedByGt    *uuid.UUID  `json:"createdByGT,omitempty"`
	CreatedByGte   *uuid.UUID  `json:"createdByGTE,omitempty"`
	CreatedByLt    *uuid.UUID  `json:"createdByLT,omitempty"`
	CreatedByLte   *uuid.UUID  `json:"createdByLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt       *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq    *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn     []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn  []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt     *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte    *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt     *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte    *time.Time   `json:"updatedAtLTE,omitempty"`
	UpdatedAtIsNil  *bool        `json:"updatedAtIsNil,omitempty"`
	UpdatedAtNotNil *bool        `json:"updatedAtNotNil,omitempty"`
	// updated_by field predicates
	UpdatedBy       *uuid.UUID  `json:"updatedBy,omitempty"`
	UpdatedByNeq    *uuid.UUID  `json:"updatedByNEQ,omitempty"`
	UpdatedByIn     []uuid.UUID `json:"updatedByIn,omitempty"`
	UpdatedByNotIn  []uuid.UUID `json:"updatedByNotIn,omitempty"`
	UpdatedByGt     *uuid.UUID  `json:"updatedByGT,omitempty"`
	UpdatedByGte    *uuid.UUID  `json:"updatedByGTE,omitempty"`
	UpdatedByLt     *uuid.UUID  `json:"updatedByLT,omitempty"`
	UpdatedByLte    *uuid.UUID  `json:"updatedByLTE,omitempty"`
	UpdatedByIsNil  *bool       `json:"updatedByIsNil,omitempty"`
	UpdatedByNotNil *bool       `json:"updatedByNotNil,omitempty"`
	// workflow_id field predicates
	WorkflowID      *string  `json:"workflowID,omitempty"`
	WorkflowIdneq   *string  `json:"workflowIDNEQ,omitempty"`
	WorkflowIDIn    []string `json:"workflowIDIn,omitempty"`
	WorkflowIDNotIn []string `json:"workflowIDNotIn,omitempty"`
	// nats_topic field predicates
	NatsTopic             *string  `json:"natsTopic,omitempty"`
	NatsTopicNeq          *string  `json:"natsTopicNEQ,omitempty"`
	NatsTopicIn           []string `json:"natsTopicIn,omitempty"`
	NatsTopicNotIn        []string `json:"natsTopicNotIn,omitempty"`
	NatsTopicGt           *string  `json:"natsTopicGT,omitempty"`
	NatsTopicGte          *string  `json:"natsTopicGTE,omitempty"`
	NatsTopicLt           *string  `json:"natsTopicLT,omitempty"`
	NatsTopicLte          *string  `json:"natsTopicLTE,omitempty"`
	NatsTopicContains     *string  `json:"natsTopicContains,omitempty"`
	NatsTopicHasPrefix    *string  `json:"natsTopicHasPrefix,omitempty"`
	NatsTopicHasSuffix    *string  `json:"natsTopicHasSuffix,omitempty"`
	NatsTopicEqualFold    *string  `json:"natsTopicEqualFold,omitempty"`
	NatsTopicContainsFold *string  `json:"natsTopicContainsFold,omitempty"`
	// temporal_signal field predicates
	TemporalSignal             *string  `json:"temporalSignal,omitempty"`
	TemporalSignalNeq          *string  `json:"temporalSignalNEQ,omitempty"`
	TemporalSignalIn           []string `json:"temporalSignalIn,omitempty"`
	TemporalSignalNotIn        []string `json:"temporalSignalNotIn,omitempty"`
	TemporalSignalGt           *string  `json:"temporalSignalGT,omitempty"`
	TemporalSignalGte          *string  `json:"temporalSignalGTE,omitempty"`
	TemporalSignalLt           *string  `json:"temporalSignalLT,omitempty"`
	TemporalSignalLte          *string  `json:"temporalSignalLTE,omitempty"`
	TemporalSignalContains     *string  `json:"temporalSignalContains,omitempty"`
	TemporalSignalHasPrefix    *string  `json:"temporalSignalHasPrefix,omitempty"`
	TemporalSignalHasSuffix    *string  `json:"temporalSignalHasSuffix,omitempty"`
	TemporalSignalIsNil        *bool    `json:"temporalSignalIsNil,omitempty"`
	TemporalSignalNotNil       *bool    `json:"temporalSignalNotNil,omitempty"`
	TemporalSignalEqualFold    *string  `json:"temporalSignalEqualFold,omitempty"`
	TemporalSignalContainsFold *string  `json:"temporalSignalContainsFold,omitempty"`
	// temporal_signal_type field predicates
	TemporalSignalType      *workflowsignal.TemporalSignalType  `json:"temporalSignalType,omitempty"`
	TemporalSignalTypeNeq   *workflowsignal.TemporalSignalType  `json:"temporalSignalTypeNEQ,omitempty"`
	TemporalSignalTypeIn    []workflowsignal.TemporalSignalType `json:"temporalSignalTypeIn,omitempty"`
	TemporalSignalTypeNotIn []workflowsignal.TemporalSignalType `json:"temporalSignalTypeNotIn,omitempty"`
	// filter_rule field predicates
	FilterRule             *string  `json:"filterRule,omitempty"`
	FilterRuleNeq          *string  `json:"filterRuleNEQ,omitempty"`
	FilterRuleIn           []string `json:"filterRuleIn,omitempty"`
	FilterRuleNotIn        []string `json:"filterRuleNotIn,omitempty"`
	FilterRuleGt           *string  `json:"filterRuleGT,omitempty"`
	FilterRuleGte          *string  `json:"filterRuleGTE,omitempty"`
	FilterRuleLt           *string  `json:"filterRuleLT,omitempty"`
	FilterRuleLte          *string  `json:"filterRuleLTE,omitempty"`
	FilterRuleContains     *string  `json:"filterRuleContains,omitempty"`
	FilterRuleHasPrefix    *string  `json:"filterRuleHasPrefix,omitempty"`
	FilterRuleHasSuffix    *string  `json:"filterRuleHasSuffix,omitempty"`
	FilterRuleIsNil        *bool    `json:"filterRuleIsNil,omitempty"`
	FilterRuleNotNil       *bool    `json:"filterRuleNotNil,omitempty"`
	FilterRuleEqualFold    *string  `json:"filterRuleEqualFold,omitempty"`
	FilterRuleContainsFold *string  `json:"filterRuleContainsFold,omitempty"`
	// workflow edge predicates
	HasWorkflow     *bool                 `json:"hasWorkflow,omitempty"`
	HasWorkflowWith []*WorkflowWhereInput `json:"hasWorkflowWith,omitempty"`
}

// WorkflowWhereInput is used for filtering Workflow objects.
// Input was generated by ent.
type WorkflowWhereInput struct {
	Not *WorkflowWhereInput   `json:"not,omitempty"`
	And []*WorkflowWhereInput `json:"and,omitempty"`
	Or  []*WorkflowWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *string  `json:"id,omitempty"`
	IDNeq   *string  `json:"idNEQ,omitempty"`
	IDIn    []string `json:"idIn,omitempty"`
	IDNotIn []string `json:"idNotIn,omitempty"`
	IDGt    *string  `json:"idGT,omitempty"`
	IDGte   *string  `json:"idGTE,omitempty"`
	IDLt    *string  `json:"idLT,omitempty"`
	IDLte   *string  `json:"idLTE,omitempty"`
	// tenant_id field predicates
	TenantID      *uuid.UUID  `json:"tenantID,omitempty"`
	TenantIdneq   *uuid.UUID  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn    []uuid.UUID `json:"tenantIDIn,omitempty"`
	TenantIDNotIn []uuid.UUID `json:"tenantIDNotIn,omitempty"`
	TenantIdgt    *uuid.UUID  `json:"tenantIDGT,omitempty"`
	TenantIdgte   *uuid.UUID  `json:"tenantIDGTE,omitempty"`
	TenantIdlt    *uuid.UUID  `json:"tenantIDLT,omitempty"`
	TenantIdlte   *uuid.UUID  `json:"tenantIDLTE,omitempty"`
	// data_type_id field predicates
	DataTypeID       *uuid.UUID  `json:"dataTypeID,omitempty"`
	DataTypeIdneq    *uuid.UUID  `json:"dataTypeIDNEQ,omitempty"`
	DataTypeIDIn     []uuid.UUID `json:"dataTypeIDIn,omitempty"`
	DataTypeIDNotIn  []uuid.UUID `json:"dataTypeIDNotIn,omitempty"`
	DataTypeIdgt     *uuid.UUID  `json:"dataTypeIDGT,omitempty"`
	DataTypeIdgte    *uuid.UUID  `json:"dataTypeIDGTE,omitempty"`
	DataTypeIdlt     *uuid.UUID  `json:"dataTypeIDLT,omitempty"`
	DataTypeIdlte    *uuid.UUID  `json:"dataTypeIDLTE,omitempty"`
	DataTypeIDIsNil  *bool       `json:"dataTypeIDIsNil,omitempty"`
	DataTypeIDNotNil *bool       `json:"dataTypeIDNotNil,omitempty"`
	// data_type_slug field predicates
	DataTypeSlug             *string  `json:"dataTypeSlug,omitempty"`
	DataTypeSlugNeq          *string  `json:"dataTypeSlugNEQ,omitempty"`
	DataTypeSlugIn           []string `json:"dataTypeSlugIn,omitempty"`
	DataTypeSlugNotIn        []string `json:"dataTypeSlugNotIn,omitempty"`
	DataTypeSlugGt           *string  `json:"dataTypeSlugGT,omitempty"`
	DataTypeSlugGte          *string  `json:"dataTypeSlugGTE,omitempty"`
	DataTypeSlugLt           *string  `json:"dataTypeSlugLT,omitempty"`
	DataTypeSlugLte          *string  `json:"dataTypeSlugLTE,omitempty"`
	DataTypeSlugContains     *string  `json:"dataTypeSlugContains,omitempty"`
	DataTypeSlugHasPrefix    *string  `json:"dataTypeSlugHasPrefix,omitempty"`
	DataTypeSlugHasSuffix    *string  `json:"dataTypeSlugHasSuffix,omitempty"`
	DataTypeSlugIsNil        *bool    `json:"dataTypeSlugIsNil,omitempty"`
	DataTypeSlugNotNil       *bool    `json:"dataTypeSlugNotNil,omitempty"`
	DataTypeSlugEqualFold    *string  `json:"dataTypeSlugEqualFold,omitempty"`
	DataTypeSlugContainsFold *string  `json:"dataTypeSlugContainsFold,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// created_by field predicates
	CreatedBy      *uuid.UUID  `json:"createdBy,omitempty"`
	CreatedByNeq   *uuid.UUID  `json:"createdByNEQ,omitempty"`
	CreatedByIn    []uuid.UUID `json:"createdByIn,omitempty"`
	CreatedByNotIn []uuid.UUID `json:"createdByNotIn,omitempty"`
	CreatedByGt    *uuid.UUID  `json:"createdByGT,omitempty"`
	CreatedByGte   *uuid.UUID  `json:"createdByGTE,omitempty"`
	CreatedByLt    *uuid.UUID  `json:"createdByLT,omitempty"`
	CreatedByLte   *uuid.UUID  `json:"createdByLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt       *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq    *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn     []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn  []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt     *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte    *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt     *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte    *time.Time   `json:"updatedAtLTE,omitempty"`
	UpdatedAtIsNil  *bool        `json:"updatedAtIsNil,omitempty"`
	UpdatedAtNotNil *bool        `json:"updatedAtNotNil,omitempty"`
	// updated_by field predicates
	UpdatedBy       *uuid.UUID  `json:"updatedBy,omitempty"`
	UpdatedByNeq    *uuid.UUID  `json:"updatedByNEQ,omitempty"`
	UpdatedByIn     []uuid.UUID `json:"updatedByIn,omitempty"`
	UpdatedByNotIn  []uuid.UUID `json:"updatedByNotIn,omitempty"`
	UpdatedByGt     *uuid.UUID  `json:"updatedByGT,omitempty"`
	UpdatedByGte    *uuid.UUID  `json:"updatedByGTE,omitempty"`
	UpdatedByLt     *uuid.UUID  `json:"updatedByLT,omitempty"`
	UpdatedByLte    *uuid.UUID  `json:"updatedByLTE,omitempty"`
	UpdatedByIsNil  *bool       `json:"updatedByIsNil,omitempty"`
	UpdatedByNotNil *bool       `json:"updatedByNotNil,omitempty"`
	// name field predicates
	Name             *string  `json:"name,omitempty"`
	NameNeq          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGt           *string  `json:"nameGT,omitempty"`
	NameGte          *string  `json:"nameGTE,omitempty"`
	NameLt           *string  `json:"nameLT,omitempty"`
	NameLte          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`
	// task_queue field predicates
	TaskQueue             *string  `json:"taskQueue,omitempty"`
	TaskQueueNeq          *string  `json:"taskQueueNEQ,omitempty"`
	TaskQueueIn           []string `json:"taskQueueIn,omitempty"`
	TaskQueueNotIn        []string `json:"taskQueueNotIn,omitempty"`
	TaskQueueGt           *string  `json:"taskQueueGT,omitempty"`
	TaskQueueGte          *string  `json:"taskQueueGTE,omitempty"`
	TaskQueueLt           *string  `json:"taskQueueLT,omitempty"`
	TaskQueueLte          *string  `json:"taskQueueLTE,omitempty"`
	TaskQueueContains     *string  `json:"taskQueueContains,omitempty"`
	TaskQueueHasPrefix    *string  `json:"taskQueueHasPrefix,omitempty"`
	TaskQueueHasSuffix    *string  `json:"taskQueueHasSuffix,omitempty"`
	TaskQueueEqualFold    *string  `json:"taskQueueEqualFold,omitempty"`
	TaskQueueContainsFold *string  `json:"taskQueueContainsFold,omitempty"`
	// workflowSignals edge predicates
	HasWorkflowSignals     *bool                       `json:"hasWorkflowSignals,omitempty"`
	HasWorkflowSignalsWith []*WorkflowSignalWhereInput `json:"hasWorkflowSignalsWith,omitempty"`
	Data                   []string                    `json:"Data,omitempty"`
	DataHasKey             *string                     `json:"DataHasKey,omitempty"`
	DataIn                 []string                    `json:"DataIn,omitempty"`
	DataContains           []string                    `json:"DataContains,omitempty"`
}

// JSON type for casting extracted JSONB values during ordering.
type JSONType string

const (
	// Cast to numeric for number comparisons.
	JSONTypeNumber JSONType = "NUMBER"
	// Cast to text for string comparisons.
	JSONTypeString JSONType = "STRING"
	// Cast to boolean for boolean comparisons.
	JSONTypeBoolean JSONType = "BOOLEAN"
)

var AllJSONType = []JSONType{
	JSONTypeNumber,
	JSONTypeString,
	JSONTypeBoolean,
}

func (e JSONType) IsValid() bool {
	switch e {
	case JSONTypeNumber, JSONTypeString, JSONTypeBoolean:
		return true
	}
	return false
}

func (e JSONType) String() string {
	return string(e)
}

func (e *JSONType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JSONType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JSONType", str)
	}
	return nil
}

func (e JSONType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JSONType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JSONType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Possible directions in which to order a list of items when provided an `orderBy` argument.
type OrderDirection string

const (
	// Specifies an ascending order for a given `orderBy` argument.
	OrderDirectionAsc OrderDirection = "ASC"
	// Specifies a descending order for a given `orderBy` argument.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Properties by which Workflow connections can be ordered.
type WorkflowOrderField string

const (
	WorkflowOrderFieldTenantID  WorkflowOrderField = "TENANT_ID"
	WorkflowOrderFieldCreatedAt WorkflowOrderField = "CREATED_AT"
	WorkflowOrderFieldCreatedBy WorkflowOrderField = "CREATED_BY"
	WorkflowOrderFieldUpdatedAt WorkflowOrderField = "UPDATED_AT"
	WorkflowOrderFieldUpdatedBy WorkflowOrderField = "UPDATED_BY"
	WorkflowOrderFieldDeletedAt WorkflowOrderField = "DELETED_AT"
	WorkflowOrderFieldDeletedBy WorkflowOrderField = "DELETED_BY"
	WorkflowOrderFieldName      WorkflowOrderField = "NAME"
	WorkflowOrderFieldTaskQueue WorkflowOrderField = "TASK_QUEUE"
)

var AllWorkflowOrderField = []WorkflowOrderField{
	WorkflowOrderFieldTenantID,
	WorkflowOrderFieldCreatedAt,
	WorkflowOrderFieldCreatedBy,
	WorkflowOrderFieldUpdatedAt,
	WorkflowOrderFieldUpdatedBy,
	WorkflowOrderFieldDeletedAt,
	WorkflowOrderFieldDeletedBy,
	WorkflowOrderFieldName,
	WorkflowOrderFieldTaskQueue,
}

func (e WorkflowOrderField) IsValid() bool {
	switch e {
	case WorkflowOrderFieldTenantID, WorkflowOrderFieldCreatedAt, WorkflowOrderFieldCreatedBy, WorkflowOrderFieldUpdatedAt, WorkflowOrderFieldUpdatedBy, WorkflowOrderFieldDeletedAt, WorkflowOrderFieldDeletedBy, WorkflowOrderFieldName, WorkflowOrderFieldTaskQueue:
		return true
	}
	return false
}

func (e WorkflowOrderField) String() string {
	return string(e)
}

func (e *WorkflowOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowOrderField", str)
	}
	return nil
}

func (e WorkflowOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Properties by which WorkflowSignal connections can be ordered.
type WorkflowSignalOrderField string

const (
	WorkflowSignalOrderFieldTenantID           WorkflowSignalOrderField = "TENANT_ID"
	WorkflowSignalOrderFieldCreatedAt          WorkflowSignalOrderField = "CREATED_AT"
	WorkflowSignalOrderFieldCreatedBy          WorkflowSignalOrderField = "CREATED_BY"
	WorkflowSignalOrderFieldUpdatedAt          WorkflowSignalOrderField = "UPDATED_AT"
	WorkflowSignalOrderFieldUpdatedBy          WorkflowSignalOrderField = "UPDATED_BY"
	WorkflowSignalOrderFieldDeletedAt          WorkflowSignalOrderField = "DELETED_AT"
	WorkflowSignalOrderFieldDeletedBy          WorkflowSignalOrderField = "DELETED_BY"
	WorkflowSignalOrderFieldWorkflowID         WorkflowSignalOrderField = "WORKFLOW_ID"
	WorkflowSignalOrderFieldNatsTopic          WorkflowSignalOrderField = "NATS_TOPIC"
	WorkflowSignalOrderFieldTemporalSignal     WorkflowSignalOrderField = "TEMPORAL_SIGNAL"
	WorkflowSignalOrderFieldTemporalSignalType WorkflowSignalOrderField = "TEMPORAL_SIGNAL_TYPE"
	WorkflowSignalOrderFieldFilterRule         WorkflowSignalOrderField = "FILTER_RULE"
)

var AllWorkflowSignalOrderField = []WorkflowSignalOrderField{
	WorkflowSignalOrderFieldTenantID,
	WorkflowSignalOrderFieldCreatedAt,
	WorkflowSignalOrderFieldCreatedBy,
	WorkflowSignalOrderFieldUpdatedAt,
	WorkflowSignalOrderFieldUpdatedBy,
	WorkflowSignalOrderFieldDeletedAt,
	WorkflowSignalOrderFieldDeletedBy,
	WorkflowSignalOrderFieldWorkflowID,
	WorkflowSignalOrderFieldNatsTopic,
	WorkflowSignalOrderFieldTemporalSignal,
	WorkflowSignalOrderFieldTemporalSignalType,
	WorkflowSignalOrderFieldFilterRule,
}

func (e WorkflowSignalOrderField) IsValid() bool {
	switch e {
	case WorkflowSignalOrderFieldTenantID, WorkflowSignalOrderFieldCreatedAt, WorkflowSignalOrderFieldCreatedBy, WorkflowSignalOrderFieldUpdatedAt, WorkflowSignalOrderFieldUpdatedBy, WorkflowSignalOrderFieldDeletedAt, WorkflowSignalOrderFieldDeletedBy, WorkflowSignalOrderFieldWorkflowID, WorkflowSignalOrderFieldNatsTopic, WorkflowSignalOrderFieldTemporalSignal, WorkflowSignalOrderFieldTemporalSignalType, WorkflowSignalOrderFieldFilterRule:
		return true
	}
	return false
}

func (e WorkflowSignalOrderField) String() string {
	return string(e)
}

func (e *WorkflowSignalOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowSignalOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowSignalOrderField", str)
	}
	return nil
}

func (e WorkflowSignalOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowSignalOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowSignalOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
