// Code generated by github.com/pyck-ai/pyck/backend/common/cmd/apigen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/Yamashou/gqlgenc/clientv2"

	"github.com/pyck-ai/pyck/backend/common/api"
	"github.com/pyck-ai/pyck/backend/common/env"
	"github.com/pyck-ai/pyck/backend/workflow/model"

	internalapi "github.com/pyck-ai/pyck/backend/workflow/api/internal"
)

type Config = api.Config

// DefaultClient creates a new Client with default configuration loaded from
// environment variables. Additional request interceptors can be provided which
// will be appended to the default ones. The default configuration includes
// authentication and tenant ID headers. Returns an error if the configuration
// cannot be loaded.
func DefaultClient(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (Client, error) {
	_, config, err := env.Load[api.Config](ctx)
	if err != nil {
		return nil, err
	}

	clientOptions := clientv2.Options{
		ParseDataAlongWithErrors: false,
	}

	interceptors = append([]clientv2.RequestInterceptor{
		api.AuthnMiddleware(api.Config{
			GatewayConfig: config.GatewayConfig,
			APIToken:      config.APIToken,
			APITenantID:   config.APITenantID,
		}),
	}, interceptors...)

	return NewClient(http.DefaultClient, config.GatewayUrl, &clientOptions, interceptors...), nil
}

type Client interface {
	GetWorkflows(ctx context.Context, input GetWorkflowsArgs) (*GetWorkflows, error)
	GetWorkflowSignals(ctx context.Context, input GetWorkflowSignalsArgs) (*GetWorkflowSignals, error)
	GetWorkflowServiceInfo(ctx context.Context) (*GetWorkflowServiceInfo, error)
	GetCurrentUserDataInput(ctx context.Context, input GetCurrentUserDataInputArgs) (*GetCurrentUserDataInput, error)
	GetWorkflowExecutions(ctx context.Context, input GetWorkflowExecutionsArgs) (*GetWorkflowExecutions, error)
	GetAssignableWorkflowExecutions(ctx context.Context, input GetAssignableWorkflowExecutionsArgs) (*GetAssignableWorkflowExecutions, error)
	GetWorkflowHistory(ctx context.Context, input GetWorkflowHistoryArgs) (*GetWorkflowHistory, error)
	GetWorkflowActions(ctx context.Context, input GetWorkflowActionsArgs) (*GetWorkflowActions, error)
	GetWorkflowAssignee(ctx context.Context, input GetWorkflowAssigneeArgs) (*GetWorkflowAssignee, error)
	GetWorkflowIsAssignable(ctx context.Context, input GetWorkflowIsAssignableArgs) (*GetWorkflowIsAssignable, error)
	GetWorkflowTargets(ctx context.Context, input GetWorkflowTargetsArgs) (*GetWorkflowTargets, error)
	EnsureTemporalNamespace(ctx context.Context) (*EnsureTemporalNamespace, error)
	SubmitUserDataInput(ctx context.Context, input SubmitUserDataInputArgs) (*SubmitUserDataInput, error)
	RegisterWorkflow(ctx context.Context, input RegisterWorkflowArgs) (*RegisterWorkflow, error)
	DeleteWorkflow(ctx context.Context, input DeleteWorkflowArgs) (*DeleteWorkflow, error)
	CancelWorkflow(ctx context.Context, input CancelWorkflowArgs) (*CancelWorkflow, error)
	SetWorkflowAssignee(ctx context.Context, input SetWorkflowAssigneeArgs) (*SetWorkflowAssignee, error)
	SetWorkflowIsAssignable(ctx context.Context, input SetWorkflowIsAssignableArgs) (*SetWorkflowIsAssignable, error)
	SetWorkflowTargets(ctx context.Context, input SetWorkflowTargetsArgs) (*SetWorkflowTargets, error)
}

type client struct {
	api          internalapi.APIClient
	interceptors []clientv2.RequestInterceptor
}

func NewClient(c clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *client {
	api := internalapi.NewClient(c, baseURL, options, interceptors...)

	return &client{
		api: api,
	}
}

// GetWorkflowsArgs is a sparse struct for GetWorkflows parameters
type GetWorkflowsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *WorkflowOrder
	Where   *WorkflowWhereInput
}

func (c *client) GetWorkflows(ctx context.Context, input GetWorkflowsArgs) (*GetWorkflows, error) {
	return c.api.GetWorkflows(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetWorkflowSignalsArgs is a sparse struct for GetWorkflowSignals parameters
type GetWorkflowSignalsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *WorkflowSignalOrder
	Where   *WorkflowSignalWhereInput
}

func (c *client) GetWorkflowSignals(ctx context.Context, input GetWorkflowSignalsArgs) (*GetWorkflowSignals, error) {
	return c.api.GetWorkflowSignals(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

func (c *client) GetWorkflowServiceInfo(ctx context.Context) (*GetWorkflowServiceInfo, error) {
	return c.api.GetWorkflowServiceInfo(ctx)
}

// GetCurrentUserDataInputArgs is a sparse struct for GetCurrentUserDataInput parameters
type GetCurrentUserDataInputArgs struct {
	Input model.UserDataInputQueryInput
}

func (c *client) GetCurrentUserDataInput(ctx context.Context, input GetCurrentUserDataInputArgs) (*GetCurrentUserDataInput, error) {
	return c.api.GetCurrentUserDataInput(ctx, input.Input)
}

// GetWorkflowExecutionsArgs is a sparse struct for GetWorkflowExecutions parameters
type GetWorkflowExecutionsArgs struct {
	Where   *model.WorkflowExecutionsWhereInput
	First   *int
	After   *string
	OrderBy *model.WorkflowExecutionOrder
}

func (c *client) GetWorkflowExecutions(ctx context.Context, input GetWorkflowExecutionsArgs) (*GetWorkflowExecutions, error) {
	return c.api.GetWorkflowExecutions(ctx, input.Where, input.First, input.After, input.OrderBy)
}

// GetAssignableWorkflowExecutionsArgs is a sparse struct for GetAssignableWorkflowExecutions parameters
type GetAssignableWorkflowExecutionsArgs struct {
	Where   *model.WorkflowExecutionsWhereInput
	First   *int
	After   *string
	OrderBy *model.WorkflowExecutionOrder
}

func (c *client) GetAssignableWorkflowExecutions(ctx context.Context, input GetAssignableWorkflowExecutionsArgs) (*GetAssignableWorkflowExecutions, error) {
	return c.api.GetAssignableWorkflowExecutions(ctx, input.Where, input.First, input.After, input.OrderBy)
}

// GetWorkflowHistoryArgs is a sparse struct for GetWorkflowHistory parameters
type GetWorkflowHistoryArgs struct {
	Where model.WorkflowExecutionsWhereInput
	Limit *int
}

func (c *client) GetWorkflowHistory(ctx context.Context, input GetWorkflowHistoryArgs) (*GetWorkflowHistory, error) {
	return c.api.GetWorkflowHistory(ctx, input.Where, input.Limit)
}

// GetWorkflowActionsArgs is a sparse struct for GetWorkflowActions parameters
type GetWorkflowActionsArgs struct {
	Input model.GetWorkflowActionsInput
	Where *model.WorkflowActionsWhereInput
}

func (c *client) GetWorkflowActions(ctx context.Context, input GetWorkflowActionsArgs) (*GetWorkflowActions, error) {
	return c.api.GetWorkflowActions(ctx, input.Input, input.Where)
}

// GetWorkflowAssigneeArgs is a sparse struct for GetWorkflowAssignee parameters
type GetWorkflowAssigneeArgs struct {
	Input model.GetWorkflowAssigneeInput
}

func (c *client) GetWorkflowAssignee(ctx context.Context, input GetWorkflowAssigneeArgs) (*GetWorkflowAssignee, error) {
	return c.api.GetWorkflowAssignee(ctx, input.Input)
}

// GetWorkflowIsAssignableArgs is a sparse struct for GetWorkflowIsAssignable parameters
type GetWorkflowIsAssignableArgs struct {
	Input model.GetWorkflowIsAssignableInput
}

func (c *client) GetWorkflowIsAssignable(ctx context.Context, input GetWorkflowIsAssignableArgs) (*GetWorkflowIsAssignable, error) {
	return c.api.GetWorkflowIsAssignable(ctx, input.Input)
}

// GetWorkflowTargetsArgs is a sparse struct for GetWorkflowTargets parameters
type GetWorkflowTargetsArgs struct {
	Input model.GetWorkflowTargetsInput
}

func (c *client) GetWorkflowTargets(ctx context.Context, input GetWorkflowTargetsArgs) (*GetWorkflowTargets, error) {
	return c.api.GetWorkflowTargets(ctx, input.Input)
}

func (c *client) EnsureTemporalNamespace(ctx context.Context) (*EnsureTemporalNamespace, error) {
	return c.api.EnsureTemporalNamespace(ctx)
}

// SubmitUserDataInputArgs is a sparse struct for SubmitUserDataInput parameters
type SubmitUserDataInputArgs struct {
	Input model.SubmitUserDataInputInput
}

func (c *client) SubmitUserDataInput(ctx context.Context, input SubmitUserDataInputArgs) (*SubmitUserDataInput, error) {
	return c.api.SubmitUserDataInput(ctx, input.Input)
}

// RegisterWorkflowArgs is a sparse struct for RegisterWorkflow parameters
type RegisterWorkflowArgs struct {
	Input model.RegisterWorkflowWithSignalsInput
}

func (c *client) RegisterWorkflow(ctx context.Context, input RegisterWorkflowArgs) (*RegisterWorkflow, error) {
	return c.api.RegisterWorkflow(ctx, input.Input)
}

// DeleteWorkflowArgs is a sparse struct for DeleteWorkflow parameters
type DeleteWorkflowArgs struct {
	Id string
}

func (c *client) DeleteWorkflow(ctx context.Context, input DeleteWorkflowArgs) (*DeleteWorkflow, error) {
	return c.api.DeleteWorkflow(ctx, input.Id)
}

// CancelWorkflowArgs is a sparse struct for CancelWorkflow parameters
type CancelWorkflowArgs struct {
	Input model.CancelWorkflowInput
}

func (c *client) CancelWorkflow(ctx context.Context, input CancelWorkflowArgs) (*CancelWorkflow, error) {
	return c.api.CancelWorkflow(ctx, input.Input)
}

// SetWorkflowAssigneeArgs is a sparse struct for SetWorkflowAssignee parameters
type SetWorkflowAssigneeArgs struct {
	Input model.SetWorkflowAssigneeInput
}

func (c *client) SetWorkflowAssignee(ctx context.Context, input SetWorkflowAssigneeArgs) (*SetWorkflowAssignee, error) {
	return c.api.SetWorkflowAssignee(ctx, input.Input)
}

// SetWorkflowIsAssignableArgs is a sparse struct for SetWorkflowIsAssignable parameters
type SetWorkflowIsAssignableArgs struct {
	Input model.SetWorkflowIsAssignableInput
}

func (c *client) SetWorkflowIsAssignable(ctx context.Context, input SetWorkflowIsAssignableArgs) (*SetWorkflowIsAssignable, error) {
	return c.api.SetWorkflowIsAssignable(ctx, input.Input)
}

// SetWorkflowTargetsArgs is a sparse struct for SetWorkflowTargets parameters
type SetWorkflowTargetsArgs struct {
	Input model.SetWorkflowTargetsInput
}

func (c *client) SetWorkflowTargets(ctx context.Context, input SetWorkflowTargetsArgs) (*SetWorkflowTargets, error) {
	return c.api.SetWorkflowTargets(ctx, input.Input)
}
