package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/workflow/exec"
)

// EnsureTemporalNamespace is the resolver for the ensureTemporalNamespace field.
func (r *mutationResolver) EnsureTemporalNamespace(ctx context.Context) (bool, error) {
	req := request.ForContext(ctx)

	if !req.User().IsAuthenticated() {
		return false, ErrUnauthenticated
	}

	nsClient, err := r.workflowRouter.GetClient(ctx, req.MutationTenantID().String())
	if err != nil || nsClient == nil {
		return false, err
	}

	return true, nil
}

// Mutation returns exec.MutationResolver implementation.
func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
