package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/pyck-ai/pyck/backend/common/request"
	common_workflow "github.com/pyck-ai/pyck/backend/common/workflow"
	"github.com/pyck-ai/pyck/backend/workflow/model"
	"go.temporal.io/sdk/converter"
)

// SetWorkflowAssignee is the resolver for the setWorkflowAssignee field.
func (r *mutationResolver) SetWorkflowAssignee(ctx context.Context, input model.SetWorkflowAssigneeInput) (*model.SetWorkflowAssigneeResponse, error) {
	req := request.ForContext(ctx)

	workflowClient, err := r.workflowRouter.GetClient(ctx, req.MutationTenantID().String())
	if err != nil {
		return nil, err
	}

	// Build the assignee value: nil means "unassign", non-nil means "assign to this user".
	var assignee common_workflow.WorkflowAssignee
	if input.AssigneeID != nil {
		s := input.AssigneeID.String()
		assignee = &s
	}

	var updateResult any
	if err := workflowClient.UpdateWorkflow(ctx, input.WorkflowID, input.WorkflowExecutionID,
		common_workflow.WorkflowQueryTypeSetAssignee.String(),
		common_workflow.WorkflowAssigneeUpdaterInput{
			Assignee: assignee,
		},
		&updateResult,
	); err != nil {
		return nil, err
	}

	resp := &model.SetWorkflowAssigneeResponse{}
	if assignee != nil {
		s := input.AssigneeID.String()
		resp.Assignee = &s
	}

	return resp, nil
}

// WorkflowAssignee is the resolver for the workflowAssignee field.
func (r *queryResolver) WorkflowAssignee(ctx context.Context, input model.GetWorkflowAssigneeInput) (*model.GetWorkflowAssigneeResponse, error) {
	req := request.ForContext(ctx)

	workflowClient, err := r.workflowRouter.GetClient(ctx, req.MutationTenantID().String())
	if err != nil || workflowClient == nil {
		return nil, ErrInvalidWorkflowClient
	}

	executionInfo, err := workflowClient.GetWorkflowExecutionInfo(ctx, input.WorkflowID, input.WorkflowExecutionID)
	if err != nil {
		return nil, err
	}

	dataConverter := converter.GetDefaultDataConverter()

	var assignee string

	for key, value := range executionInfo.GetSearchAttributes().GetIndexedFields() {
		if key == "pyck_workflow_assignee" {
			assignee = dataConverter.ToString(value)
		}
	}

	resp := &model.GetWorkflowAssigneeResponse{
		Assignee: assignee,
	}

	return resp, nil
}
