// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type CustomerDeletePayload struct {
	DeletedID *uuid.UUID `json:"deletedID,omitempty"`
}

type ServiceInfo struct {
	Version string     `json:"version"`
	Date    *time.Time `json:"date,omitempty"`
}

type SupplierDeletePayload struct {
	DeletedID *uuid.UUID `json:"deletedID,omitempty"`
}
