// Code generated by "enumer -text -json -yaml -sql -gqlgen -typederrors -output=feature_gen.go -type=Feature -linecomment"; DO NOT EDIT.

package feature

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"io"
	"strconv"
	"strings"
)

const _FeatureName = "showdeletedsyncupdatesasyncsignals"

var _FeatureIndex = [...]uint8{0, 11, 22, 34}

const _FeatureLowerName = "showdeletedsyncupdatesasyncsignals"

func (i Feature) String() string {
	i -= 1
	if i >= Feature(len(_FeatureIndex)-1) {
		return fmt.Sprintf("Feature(%d)", i+1)
	}
	return _FeatureName[_FeatureIndex[i]:_FeatureIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FeatureNoOp() {
	var x [1]struct{}
	_ = x[FEATURE_SHOW_DELETED-(1)]
	_ = x[FEATURE_SYNC_UPDATES-(2)]
	_ = x[FEATURE_ASYNC_SIGNALS-(3)]
}

var _FeatureValues = []Feature{FEATURE_SHOW_DELETED, FEATURE_SYNC_UPDATES, FEATURE_ASYNC_SIGNALS}

var _FeatureNameToValueMap = map[string]Feature{
	_FeatureName[0:11]:       FEATURE_SHOW_DELETED,
	_FeatureLowerName[0:11]:  FEATURE_SHOW_DELETED,
	_FeatureName[11:22]:      FEATURE_SYNC_UPDATES,
	_FeatureLowerName[11:22]: FEATURE_SYNC_UPDATES,
	_FeatureName[22:34]:      FEATURE_ASYNC_SIGNALS,
	_FeatureLowerName[22:34]: FEATURE_ASYNC_SIGNALS,
}

var _FeatureNames = []string{
	_FeatureName[0:11],
	_FeatureName[11:22],
	_FeatureName[22:34],
}

// FeatureString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FeatureString(s string) (Feature, error) {
	if val, ok := _FeatureNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FeatureNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to Feature values", s))
}

// FeatureValues returns all values of the enum
func FeatureValues() []Feature {
	return _FeatureValues
}

// FeatureStrings returns a slice of all String values of the enum
func FeatureStrings() []string {
	strs := make([]string, len(_FeatureNames))
	copy(strs, _FeatureNames)
	return strs
}

// IsAFeature returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Feature) IsAFeature() bool {
	for _, v := range _FeatureValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Feature
func (i Feature) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Feature
func (i *Feature) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Feature should be a string, got %s", data)
	}

	var err error
	*i, err = FeatureString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Feature
func (i Feature) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Feature
func (i *Feature) UnmarshalText(text []byte) error {
	var err error
	*i, err = FeatureString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Feature
func (i Feature) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Feature
func (i *Feature) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = FeatureString(s)
	return err
}

func (i Feature) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Feature) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Feature: %[1]T(%[1]v)", value)
	}

	val, err := FeatureString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// MarshalGQL implements the graphql.Marshaler interface for Feature
func (i Feature) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for Feature
func (i *Feature) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("Feature should be a string, got %T", value)
	}

	var err error
	*i, err = FeatureString(str)
	return err
}
