package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/main-data/ent/gen"
	"github.com/pyck-ai/pyck/backend/main-data/ent/gen/customer"
	"github.com/pyck-ai/pyck/backend/main-data/ent/gen/supplier"
	"github.com/pyck-ai/pyck/backend/main-data/exec"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id uuid.UUID) (gen.Noder, error) {
	return r.client.Noder(ctx, id, gen.WithFixedNodeType(customer.Table), gen.WithFixedNodeType(supplier.Table))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []uuid.UUID) ([]gen.Noder, error) {
	return r.client.Noders(ctx, ids, gen.WithFixedNodeType(customer.Table), gen.WithFixedNodeType(supplier.Table))
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, orderBy *gen.CustomerOrder, where *gen.CustomerWhereInput) (*gen.CustomerConnection, error) {
	return r.client.Customer.Query().
		Paginate(ctx, after, first, before, last,
			gen.WithCustomerOrder(orderBy),
			gen.WithCustomerFilter(where.Filter),
		)
}

// Suppliers is the resolver for the suppliers field.
func (r *queryResolver) Suppliers(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, orderBy *gen.SupplierOrder, where *gen.SupplierWhereInput) (*gen.SupplierConnection, error) {
	return r.client.Supplier.Query().
		Paginate(ctx, after, first, before, last,
			gen.WithSupplierOrder(orderBy),
			gen.WithSupplierFilter(where.Filter),
		)
}

// Query returns exec.QueryResolver implementation.
func (r *Resolver) Query() exec.QueryResolver { return &queryResolver{r} }

// CustomerWhereInput returns exec.CustomerWhereInputResolver implementation.
func (r *Resolver) CustomerWhereInput() exec.CustomerWhereInputResolver {
	return &customerWhereInputResolver{r}
}

// SupplierWhereInput returns exec.SupplierWhereInputResolver implementation.
func (r *Resolver) SupplierWhereInput() exec.SupplierWhereInputResolver {
	return &supplierWhereInputResolver{r}
}

type queryResolver struct{ *Resolver }
type customerWhereInputResolver struct{ *Resolver }
type supplierWhereInputResolver struct{ *Resolver }
