package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	maindata "github.com/pyck-ai/pyck/backend/main-data"
	"github.com/pyck-ai/pyck/backend/main-data/ent/gen"
)

// FindCustomerByID is the resolver for the findCustomerByID field.
func (r *entityResolver) FindCustomerByID(ctx context.Context, id uuid.UUID) (*gen.Customer, error) {
	customer, err := r.client.Customer.Query().Where(func(s *sql.Selector) {
		s.Where(sql.EQ("id", id))
	}).First(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed reading customer: %w", err)
	}

	return customer, nil
}

// FindSupplierByID is the resolver for the findSupplierByID field.
func (r *entityResolver) FindSupplierByID(ctx context.Context, id uuid.UUID) (*gen.Supplier, error) {
	supplier, err := r.client.Supplier.Query().Where(func(s *sql.Selector) {
		s.Where(sql.EQ("id", id))
	}).First(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed reading supplier: %w", err)
	}

	return supplier, nil
}

// Entity returns maindata.EntityResolver implementation.
func (r *Resolver) Entity() maindata.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
