package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"time"

	"entgo.io/ent/dialect"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/common/ent/mixin"
	"github.com/pyck-ai/pyck/backend/common/gqltx"
	"github.com/pyck-ai/pyck/backend/common/jsonpatch"
	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/common/validator"
	"github.com/pyck-ai/pyck/backend/main-data/core"
	ent "github.com/pyck-ai/pyck/backend/main-data/ent/gen"
	entcustomer "github.com/pyck-ai/pyck/backend/main-data/ent/gen/customer"
	entsupplier "github.com/pyck-ai/pyck/backend/main-data/ent/gen/supplier"
	"github.com/pyck-ai/pyck/backend/main-data/exec"
	"github.com/pyck-ai/pyck/backend/main-data/model"
)

// CreateCustomer is the resolver for the createCustomer field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateCustomer(ctx context.Context, input ent.CreateCustomerInput) (*ent.Customer, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	customer, err := tx.Customer.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entcustomer.Table,
		FieldName: entcustomer.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	return customer, nil
}

// UpdateCustomer is the resolver for the updateCustomer field.
// MutationEventHook captures the mutation automatically with field-level events.
func (r *mutationResolver) UpdateCustomer(ctx context.Context, id uuid.UUID, input ent.UpdateCustomerInput) (*ent.Customer, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	customer, err := tx.Customer.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entcustomer.Table,
		FieldName: entcustomer.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	return customer, nil
}

// DeleteCustomer is the resolver for the deleteCustomer field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteCustomer(ctx context.Context, id uuid.UUID) (*model.CustomerDeletePayload, error) {
	req := request.ForContext(ctx)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	_, err = tx.Customer.UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.CustomerDeletePayload{DeletedID: &id}, nil
}

// CreateSupplier is the resolver for the createSupplier field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateSupplier(ctx context.Context, input ent.CreateSupplierInput) (*ent.Supplier, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	supplier, err := tx.Supplier.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entsupplier.Table,
		FieldName: entsupplier.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	return supplier, nil
}

// UpdateSupplier is the resolver for the updateSupplier field.
// MutationEventHook captures the mutation automatically with field-level events.
func (r *mutationResolver) UpdateSupplier(ctx context.Context, id uuid.UUID, input ent.UpdateSupplierInput) (*ent.Supplier, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	supplier, err := tx.Supplier.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entsupplier.Table,
		FieldName: entsupplier.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	return supplier, nil
}

// DeleteSupplier is the resolver for the deleteSupplier field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteSupplier(ctx context.Context, id uuid.UUID) (*model.SupplierDeletePayload, error) {
	req := request.ForContext(ctx)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	_, err = tx.Supplier.UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.SupplierDeletePayload{DeletedID: &id}, nil
}

// PatchCustomerData applies RFC 6902 JSON Patch operations to the customer's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchCustomerData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*ent.Customer, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.Customer.Query().Where(entcustomer.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    entcustomer.Table,
		FieldName:    entcustomer.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	return tx.Customer.UpdateOneID(id).SetData(patched).Save(ctx)
}

// PatchSupplierData applies RFC 6902 JSON Patch operations to the supplier's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchSupplierData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*ent.Supplier, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.Supplier.Query().Where(entsupplier.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    entsupplier.Table,
		FieldName:    entsupplier.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	return tx.Supplier.UpdateOneID(id).SetData(patched).Save(ctx)
}

// Mutation returns exec.MutationResolver implementation.
func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
