// Code generated by github.com/pyck-ai/pyck/backend/common/cmd/apigen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/gqlgo/gqlgenc/clientv2"

	"github.com/pyck-ai/pyck/backend/common/api"
	"github.com/pyck-ai/pyck/backend/common/env"
	"github.com/pyck-ai/pyck/backend/management/model"

	internalapi "github.com/pyck-ai/pyck/backend/management/api/internal"
)

type Config = api.Config

// DefaultClient creates a new Client with default configuration loaded from
// environment variables. Additional request interceptors can be provided which
// will be appended to the default ones. The default configuration includes
// authentication and tenant ID headers. Returns an error if the configuration
// cannot be loaded.
func DefaultClient(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (Client, error) {
	_, config, err := env.Load[api.Config](ctx)
	if err != nil {
		return nil, err
	}

	clientOptions := clientv2.Options{
		ParseDataAlongWithErrors: false,
	}

	interceptors = append([]clientv2.RequestInterceptor{
		api.AuthnMiddleware(api.Config{
			GatewayConfig: config.GatewayConfig,
			APIToken:      config.APIToken,
			APITenantID:   config.APITenantID,
		}),
	}, interceptors...)

	return NewClient(http.DefaultClient, config.GatewayUrl, &clientOptions, interceptors...), nil
}

type Client interface {
	GetDataTypes(ctx context.Context, input GetDataTypesArgs) (*GetDataTypes, error)
	GetDevices(ctx context.Context, input GetDevicesArgs) (*GetDevices, error)
	GetDeviceLocations(ctx context.Context, input GetDeviceLocationsArgs) (*GetDeviceLocations, error)
	GetDeviceUsers(ctx context.Context, input GetDeviceUsersArgs) (*GetDeviceUsers, error)
	GetEvents(ctx context.Context, input GetEventsArgs) (*GetEvents, error)
	GetKeyValues(ctx context.Context, input GetKeyValuesArgs) (*GetKeyValues, error)
	GetLocations(ctx context.Context, input GetLocationsArgs) (*GetLocations, error)
	GetTenants(ctx context.Context, input GetTenantsArgs) (*GetTenants, error)
	GetUsers(ctx context.Context, input GetUsersArgs) (*GetUsers, error)
	GetDataTypeEntities(ctx context.Context) (*GetDataTypeEntities, error)
	GetOrganization(ctx context.Context, input GetOrganizationArgs) (*GetOrganization, error)
	GetServiceRoles(ctx context.Context) (*GetServiceRoles, error)
	GetUserServiceRoles(ctx context.Context, input GetUserServiceRolesArgs) (*GetUserServiceRoles, error)
	GetManagementServiceInfo(ctx context.Context) (*GetManagementServiceInfo, error)
	GetMe(ctx context.Context) (*GetMe, error)
	CreateDataType(ctx context.Context, input CreateDataTypeArgs) (*CreateDataType, error)
	UpdateDataType(ctx context.Context, input UpdateDataTypeArgs) (*UpdateDataType, error)
	DeleteDataType(ctx context.Context, input DeleteDataTypeArgs) (*DeleteDataType, error)
	SendCustomEvent(ctx context.Context, input SendCustomEventArgs) (*SendCustomEvent, error)
	RegisterTenant(ctx context.Context, input RegisterTenantArgs) (*RegisterTenant, error)
	DeleteTenant(ctx context.Context) (*DeleteTenant, error)
	RestoreTenant(ctx context.Context, input RestoreTenantArgs) (*RestoreTenant, error)
	SetTenantExpiry(ctx context.Context, input SetTenantExpiryArgs) (*SetTenantExpiry, error)
	SetTenantUITemplate(ctx context.Context, input SetTenantUITemplateArgs) (*SetTenantUITemplate, error)
	GenerateJSONSchema(ctx context.Context, input GenerateJSONSchemaArgs) (*GenerateJSONSchema, error)
	CreateUser(ctx context.Context, input CreateUserArgs) (*CreateUser, error)
	UpdateUser(ctx context.Context, input UpdateUserArgs) (*UpdateUser, error)
	DeleteUser(ctx context.Context, input DeleteUserArgs) (*DeleteUser, error)
	CreateEvent(ctx context.Context, input CreateEventArgs) (*CreateEvent, error)
	UpdateEvent(ctx context.Context, input UpdateEventArgs) (*UpdateEvent, error)
	DeleteEvent(ctx context.Context, input DeleteEventArgs) (*DeleteEvent, error)
	SetKeyValue(ctx context.Context, input SetKeyValueArgs) (*SetKeyValue, error)
	DeleteKeyValue(ctx context.Context, input DeleteKeyValueArgs) (*DeleteKeyValue, error)
	CreateLocation(ctx context.Context, input CreateLocationArgs) (*CreateLocation, error)
	UpdateLocation(ctx context.Context, input UpdateLocationArgs) (*UpdateLocation, error)
	DeleteLocation(ctx context.Context, input DeleteLocationArgs) (*DeleteLocation, error)
	CreateDevice(ctx context.Context, input CreateDeviceArgs) (*CreateDevice, error)
	UpdateDevice(ctx context.Context, input UpdateDeviceArgs) (*UpdateDevice, error)
	DeleteDevice(ctx context.Context, input DeleteDeviceArgs) (*DeleteDevice, error)
	SetDeviceLocation(ctx context.Context, input SetDeviceLocationArgs) (*SetDeviceLocation, error)
	UnsetDeviceLocation(ctx context.Context, input UnsetDeviceLocationArgs) (*UnsetDeviceLocation, error)
	CheckInUserDevice(ctx context.Context, input CheckInUserDeviceArgs) (*CheckInUserDevice, error)
	CheckOutUserDevice(ctx context.Context, input CheckOutUserDeviceArgs) (*CheckOutUserDevice, error)
	PatchLocationData(ctx context.Context, input PatchLocationDataArgs) (*PatchLocationData, error)
	PatchDeviceData(ctx context.Context, input PatchDeviceDataArgs) (*PatchDeviceData, error)
	PatchDeviceLocationData(ctx context.Context, input PatchDeviceLocationDataArgs) (*PatchDeviceLocationData, error)
	AssignRoles(ctx context.Context, input AssignRolesArgs) (*AssignRoles, error)
	RemoveRoles(ctx context.Context, input RemoveRolesArgs) (*RemoveRoles, error)
}

type client struct {
	api          internalapi.APIClient
	interceptors []clientv2.RequestInterceptor
}

func NewClient(c clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *client {
	api := internalapi.NewClient(c, baseURL, options, interceptors...)

	return &client{
		api: api,
	}
}

// GetDataTypesArgs is a sparse struct for GetDataTypes parameters
type GetDataTypesArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *DataTypeOrder
	Where   *DataTypeWhereInput
}

func (c *client) GetDataTypes(ctx context.Context, input GetDataTypesArgs) (*GetDataTypes, error) {
	return c.api.GetDataTypes(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetDevicesArgs is a sparse struct for GetDevices parameters
type GetDevicesArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *DeviceOrder
	Where   *DeviceWhereInput
}

func (c *client) GetDevices(ctx context.Context, input GetDevicesArgs) (*GetDevices, error) {
	return c.api.GetDevices(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetDeviceLocationsArgs is a sparse struct for GetDeviceLocations parameters
type GetDeviceLocationsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *DeviceLocationOrder
	Where   *DeviceLocationWhereInput
}

func (c *client) GetDeviceLocations(ctx context.Context, input GetDeviceLocationsArgs) (*GetDeviceLocations, error) {
	return c.api.GetDeviceLocations(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetDeviceUsersArgs is a sparse struct for GetDeviceUsers parameters
type GetDeviceUsersArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *DeviceUserOrder
	Where   *DeviceUserWhereInput
}

func (c *client) GetDeviceUsers(ctx context.Context, input GetDeviceUsersArgs) (*GetDeviceUsers, error) {
	return c.api.GetDeviceUsers(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetEventsArgs is a sparse struct for GetEvents parameters
type GetEventsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *EventOrder
	Where   *EventWhereInput
}

func (c *client) GetEvents(ctx context.Context, input GetEventsArgs) (*GetEvents, error) {
	return c.api.GetEvents(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetKeyValuesArgs is a sparse struct for GetKeyValues parameters
type GetKeyValuesArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *KeyValueOrder
	Where   *KeyValueWhereInput
}

func (c *client) GetKeyValues(ctx context.Context, input GetKeyValuesArgs) (*GetKeyValues, error) {
	return c.api.GetKeyValues(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetLocationsArgs is a sparse struct for GetLocations parameters
type GetLocationsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *LocationOrder
	Where   *LocationWhereInput
}

func (c *client) GetLocations(ctx context.Context, input GetLocationsArgs) (*GetLocations, error) {
	return c.api.GetLocations(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetTenantsArgs is a sparse struct for GetTenants parameters
type GetTenantsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *TenantOrder
	Where   *TenantWhereInput
}

func (c *client) GetTenants(ctx context.Context, input GetTenantsArgs) (*GetTenants, error) {
	return c.api.GetTenants(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetUsersArgs is a sparse struct for GetUsers parameters
type GetUsersArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *UserOrder
	Where   *UserWhereInput
}

func (c *client) GetUsers(ctx context.Context, input GetUsersArgs) (*GetUsers, error) {
	return c.api.GetUsers(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

func (c *client) GetDataTypeEntities(ctx context.Context) (*GetDataTypeEntities, error) {
	return c.api.GetDataTypeEntities(ctx)
}

// GetOrganizationArgs is a sparse struct for GetOrganization parameters
type GetOrganizationArgs struct {
	Sub string
}

func (c *client) GetOrganization(ctx context.Context, input GetOrganizationArgs) (*GetOrganization, error) {
	return c.api.GetOrganization(ctx, input.Sub)
}

func (c *client) GetServiceRoles(ctx context.Context) (*GetServiceRoles, error) {
	return c.api.GetServiceRoles(ctx)
}

// GetUserServiceRolesArgs is a sparse struct for GetUserServiceRoles parameters
type GetUserServiceRolesArgs struct {
	Input model.UserServiceRolesInput
}

func (c *client) GetUserServiceRoles(ctx context.Context, input GetUserServiceRolesArgs) (*GetUserServiceRoles, error) {
	return c.api.GetUserServiceRoles(ctx, input.Input)
}

func (c *client) GetManagementServiceInfo(ctx context.Context) (*GetManagementServiceInfo, error) {
	return c.api.GetManagementServiceInfo(ctx)
}

func (c *client) GetMe(ctx context.Context) (*GetMe, error) {
	return c.api.GetMe(ctx)
}

// CreateDataTypeArgs is a sparse struct for CreateDataType parameters
type CreateDataTypeArgs struct {
	Input CreateDataTypeInput
}

func (c *client) CreateDataType(ctx context.Context, input CreateDataTypeArgs) (*CreateDataType, error) {
	return c.api.CreateDataType(ctx, input.Input)
}

// UpdateDataTypeArgs is a sparse struct for UpdateDataType parameters
type UpdateDataTypeArgs struct {
	Id    string
	Input UpdateDataTypeInput
}

func (c *client) UpdateDataType(ctx context.Context, input UpdateDataTypeArgs) (*UpdateDataType, error) {
	return c.api.UpdateDataType(ctx, input.Id, input.Input)
}

// DeleteDataTypeArgs is a sparse struct for DeleteDataType parameters
type DeleteDataTypeArgs struct {
	Id string
}

func (c *client) DeleteDataType(ctx context.Context, input DeleteDataTypeArgs) (*DeleteDataType, error) {
	return c.api.DeleteDataType(ctx, input.Id)
}

// SendCustomEventArgs is a sparse struct for SendCustomEvent parameters
type SendCustomEventArgs struct {
	Input model.SendCustomEventInput
}

func (c *client) SendCustomEvent(ctx context.Context, input SendCustomEventArgs) (*SendCustomEvent, error) {
	return c.api.SendCustomEvent(ctx, input.Input)
}

// RegisterTenantArgs is a sparse struct for RegisterTenant parameters
type RegisterTenantArgs struct {
	Input model.RegisterTenantInput
}

func (c *client) RegisterTenant(ctx context.Context, input RegisterTenantArgs) (*RegisterTenant, error) {
	return c.api.RegisterTenant(ctx, input.Input)
}

func (c *client) DeleteTenant(ctx context.Context) (*DeleteTenant, error) {
	return c.api.DeleteTenant(ctx)
}

// RestoreTenantArgs is a sparse struct for RestoreTenant parameters
type RestoreTenantArgs struct {
	Input model.RestoreTenantInput
}

func (c *client) RestoreTenant(ctx context.Context, input RestoreTenantArgs) (*RestoreTenant, error) {
	return c.api.RestoreTenant(ctx, input.Input)
}

// SetTenantExpiryArgs is a sparse struct for SetTenantExpiry parameters
type SetTenantExpiryArgs struct {
	Input model.SetTenantExpiryInput
}

func (c *client) SetTenantExpiry(ctx context.Context, input SetTenantExpiryArgs) (*SetTenantExpiry, error) {
	return c.api.SetTenantExpiry(ctx, input.Input)
}

// SetTenantUITemplateArgs is a sparse struct for SetTenantUITemplate parameters
type SetTenantUITemplateArgs struct {
	Input model.SetTenantUITemplateInput
}

func (c *client) SetTenantUITemplate(ctx context.Context, input SetTenantUITemplateArgs) (*SetTenantUITemplate, error) {
	return c.api.SetTenantUITemplate(ctx, input.Input)
}

// GenerateJSONSchemaArgs is a sparse struct for GenerateJSONSchema parameters
type GenerateJSONSchemaArgs struct {
	JsonData string
}

func (c *client) GenerateJSONSchema(ctx context.Context, input GenerateJSONSchemaArgs) (*GenerateJSONSchema, error) {
	return c.api.GenerateJSONSchema(ctx, input.JsonData)
}

// CreateUserArgs is a sparse struct for CreateUser parameters
type CreateUserArgs struct {
	Input CreateUserInput
}

func (c *client) CreateUser(ctx context.Context, input CreateUserArgs) (*CreateUser, error) {
	return c.api.CreateUser(ctx, input.Input)
}

// UpdateUserArgs is a sparse struct for UpdateUser parameters
type UpdateUserArgs struct {
	Id    string
	Input UpdateUserInput
}

func (c *client) UpdateUser(ctx context.Context, input UpdateUserArgs) (*UpdateUser, error) {
	return c.api.UpdateUser(ctx, input.Id, input.Input)
}

// DeleteUserArgs is a sparse struct for DeleteUser parameters
type DeleteUserArgs struct {
	Id string
}

func (c *client) DeleteUser(ctx context.Context, input DeleteUserArgs) (*DeleteUser, error) {
	return c.api.DeleteUser(ctx, input.Id)
}

// CreateEventArgs is a sparse struct for CreateEvent parameters
type CreateEventArgs struct {
	Input model.CreateEventInput
}

func (c *client) CreateEvent(ctx context.Context, input CreateEventArgs) (*CreateEvent, error) {
	return c.api.CreateEvent(ctx, input.Input)
}

// UpdateEventArgs is a sparse struct for UpdateEvent parameters
type UpdateEventArgs struct {
	Id    string
	Input model.UpdateEventInput
}

func (c *client) UpdateEvent(ctx context.Context, input UpdateEventArgs) (*UpdateEvent, error) {
	return c.api.UpdateEvent(ctx, input.Id, input.Input)
}

// DeleteEventArgs is a sparse struct for DeleteEvent parameters
type DeleteEventArgs struct {
	Id string
}

func (c *client) DeleteEvent(ctx context.Context, input DeleteEventArgs) (*DeleteEvent, error) {
	return c.api.DeleteEvent(ctx, input.Id)
}

// SetKeyValueArgs is a sparse struct for SetKeyValue parameters
type SetKeyValueArgs struct {
	Input model.SetKeyValueInput
}

func (c *client) SetKeyValue(ctx context.Context, input SetKeyValueArgs) (*SetKeyValue, error) {
	return c.api.SetKeyValue(ctx, input.Input)
}

// DeleteKeyValueArgs is a sparse struct for DeleteKeyValue parameters
type DeleteKeyValueArgs struct {
	Id string
}

func (c *client) DeleteKeyValue(ctx context.Context, input DeleteKeyValueArgs) (*DeleteKeyValue, error) {
	return c.api.DeleteKeyValue(ctx, input.Id)
}

// CreateLocationArgs is a sparse struct for CreateLocation parameters
type CreateLocationArgs struct {
	Input CreateLocationInput
}

func (c *client) CreateLocation(ctx context.Context, input CreateLocationArgs) (*CreateLocation, error) {
	return c.api.CreateLocation(ctx, input.Input)
}

// UpdateLocationArgs is a sparse struct for UpdateLocation parameters
type UpdateLocationArgs struct {
	Id    string
	Input UpdateLocationInput
}

func (c *client) UpdateLocation(ctx context.Context, input UpdateLocationArgs) (*UpdateLocation, error) {
	return c.api.UpdateLocation(ctx, input.Id, input.Input)
}

// DeleteLocationArgs is a sparse struct for DeleteLocation parameters
type DeleteLocationArgs struct {
	Id string
}

func (c *client) DeleteLocation(ctx context.Context, input DeleteLocationArgs) (*DeleteLocation, error) {
	return c.api.DeleteLocation(ctx, input.Id)
}

// CreateDeviceArgs is a sparse struct for CreateDevice parameters
type CreateDeviceArgs struct {
	Input CreateDeviceInput
}

func (c *client) CreateDevice(ctx context.Context, input CreateDeviceArgs) (*CreateDevice, error) {
	return c.api.CreateDevice(ctx, input.Input)
}

// UpdateDeviceArgs is a sparse struct for UpdateDevice parameters
type UpdateDeviceArgs struct {
	Id    string
	Input UpdateDeviceInput
}

func (c *client) UpdateDevice(ctx context.Context, input UpdateDeviceArgs) (*UpdateDevice, error) {
	return c.api.UpdateDevice(ctx, input.Id, input.Input)
}

// DeleteDeviceArgs is a sparse struct for DeleteDevice parameters
type DeleteDeviceArgs struct {
	Id string
}

func (c *client) DeleteDevice(ctx context.Context, input DeleteDeviceArgs) (*DeleteDevice, error) {
	return c.api.DeleteDevice(ctx, input.Id)
}

// SetDeviceLocationArgs is a sparse struct for SetDeviceLocation parameters
type SetDeviceLocationArgs struct {
	Input CreateDeviceLocationInput
}

func (c *client) SetDeviceLocation(ctx context.Context, input SetDeviceLocationArgs) (*SetDeviceLocation, error) {
	return c.api.SetDeviceLocation(ctx, input.Input)
}

// UnsetDeviceLocationArgs is a sparse struct for UnsetDeviceLocation parameters
type UnsetDeviceLocationArgs struct {
	Id string
}

func (c *client) UnsetDeviceLocation(ctx context.Context, input UnsetDeviceLocationArgs) (*UnsetDeviceLocation, error) {
	return c.api.UnsetDeviceLocation(ctx, input.Id)
}

// CheckInUserDeviceArgs is a sparse struct for CheckInUserDevice parameters
type CheckInUserDeviceArgs struct {
	Input model.CheckInUserDeviceInput
}

func (c *client) CheckInUserDevice(ctx context.Context, input CheckInUserDeviceArgs) (*CheckInUserDevice, error) {
	return c.api.CheckInUserDevice(ctx, input.Input)
}

// CheckOutUserDeviceArgs is a sparse struct for CheckOutUserDevice parameters
type CheckOutUserDeviceArgs struct {
	Input model.CheckOutUserDeviceInput
}

func (c *client) CheckOutUserDevice(ctx context.Context, input CheckOutUserDeviceArgs) (*CheckOutUserDevice, error) {
	return c.api.CheckOutUserDevice(ctx, input.Input)
}

// PatchLocationDataArgs is a sparse struct for PatchLocationData parameters
type PatchLocationDataArgs struct {
	Id      string
	Patches []*JSONPatchInput
}

func (c *client) PatchLocationData(ctx context.Context, input PatchLocationDataArgs) (*PatchLocationData, error) {
	return c.api.PatchLocationData(ctx, input.Id, input.Patches)
}

// PatchDeviceDataArgs is a sparse struct for PatchDeviceData parameters
type PatchDeviceDataArgs struct {
	Id      string
	Patches []*JSONPatchInput
}

func (c *client) PatchDeviceData(ctx context.Context, input PatchDeviceDataArgs) (*PatchDeviceData, error) {
	return c.api.PatchDeviceData(ctx, input.Id, input.Patches)
}

// PatchDeviceLocationDataArgs is a sparse struct for PatchDeviceLocationData parameters
type PatchDeviceLocationDataArgs struct {
	Id      string
	Patches []*JSONPatchInput
}

func (c *client) PatchDeviceLocationData(ctx context.Context, input PatchDeviceLocationDataArgs) (*PatchDeviceLocationData, error) {
	return c.api.PatchDeviceLocationData(ctx, input.Id, input.Patches)
}

// AssignRolesArgs is a sparse struct for AssignRoles parameters
type AssignRolesArgs struct {
	Input model.AssignRolesInput
}

func (c *client) AssignRoles(ctx context.Context, input AssignRolesArgs) (*AssignRoles, error) {
	return c.api.AssignRoles(ctx, input.Input)
}

// RemoveRolesArgs is a sparse struct for RemoveRoles parameters
type RemoveRolesArgs struct {
	Input model.RemoveRolesInput
}

func (c *client) RemoveRoles(ctx context.Context, input RemoveRolesArgs) (*RemoveRoles, error) {
	return c.api.RemoveRoles(ctx, input.Input)
}
