package events

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"github.com/pyck-ai/pyck/backend/common/requestid"
	"github.com/pyck-ai/pyck/backend/common/txid"
)

// ErrNoTransactionID is returned when no tx-scoped transaction ID is available
// on ctx (gqltx middleware did not run or this is a read-only path).
var ErrNoTransactionID = errors.New("no transaction ID: gqltx middleware did not run on this context")

// Context keys for event middleware values.
type (
	expectReplyKey           struct{}
	extraSearchAttributesKey struct{}
)

// TransactionIDFromContext returns the per-tx UUID generated by the gqltx
// middleware at BeginTx. This is the canonical NATS message-ID component
// for the outbox: stable across outbox-handler restarts (persisted in the
// tx) and unique per OCC attempt.
//
// Returns ErrNoTransactionID if no tx is active on ctx.
func TransactionIDFromContext(ctx context.Context) (uuid.UUID, error) {
	if id, ok := txid.FromContext(ctx); ok {
		return id, nil
	}
	return uuid.Nil, ErrNoTransactionID
}

// TraceIDFromContext extracts the OpenTelemetry trace ID from ctx for
// observability tagging. Returns the empty string when no trace context is
// available (e.g. background goroutine, sampling disabled). The trace ID is
// NOT used for deduplication — see TransactionIDFromContext for that.
func TraceIDFromContext(ctx context.Context) string {
	spanCtx := trace.SpanFromContext(ctx).SpanContext()
	if spanCtx.HasTraceID() {
		return spanCtx.TraceID().String()
	}
	return ""
}

// RequestIDFromContext extracts the server-generated request ID from OTel
// baggage. Returns the empty string when absent. Observability only.
func RequestIDFromContext(ctx context.Context) string {
	return requestid.FromContext(ctx)
}

// WithExpectReply sets whether the mutation should wait for a reply containing workflow IDs.
// When true, the resolver will block until the outbox handler delivers workflow details
// or the timeout expires.
func WithExpectReply(ctx context.Context, expect bool) context.Context {
	return context.WithValue(ctx, expectReplyKey{}, expect)
}

// ExpectsReply returns whether the mutation should wait for a reply.
// Defaults to false if not set.
func ExpectsReply(ctx context.Context) bool {
	if expect, ok := ctx.Value(expectReplyKey{}).(bool); ok {
		return expect
	}
	return false
}

// WithExtraSearchAttribute adds a workflow search attribute to the context.
// These attributes are merged with auto-computed attributes from entity mixin fields.
// Use this to add custom search attributes that cannot be derived from the entity.
func WithExtraSearchAttribute(ctx context.Context, name, value string) context.Context {
	existing := ExtraSearchAttributesFromContext(ctx)
	merged := make(map[string]string, len(existing)+1)

	for k, v := range existing {
		merged[k] = v
	}
	merged[name] = value

	return context.WithValue(ctx, extraSearchAttributesKey{}, merged)
}

// ExtraSearchAttributesFromContext returns the extended search attributes from the context.
// Returns nil if no attributes were set.
func ExtraSearchAttributesFromContext(ctx context.Context) map[string]string {
	if attrs, ok := ctx.Value(extraSearchAttributesKey{}).(map[string]string); ok {
		return attrs
	}
	return nil
}
