// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package internal

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// CreateReceivingInboundItemInput is used for create ReceivingInboundItem object.
// Input was generated by ent.
type CreateReceivingInboundItemInput struct {
	DataTypeID   *uuid.UUID     `json:"dataTypeID,omitempty"`
	DataTypeSlug *string        `json:"dataTypeSlug,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
	Sku          string         `json:"sku"`
	Quantity     int            `json:"quantity"`
	InboundID    string         `json:"inboundID"`
}

// CreateReceivingInboundShipmentNotificationInput is used for create ReceivingInboundShipmentNotification object.
// Input was generated by ent.
type CreateReceivingInboundShipmentNotificationInput struct {
	DataTypeID   *uuid.UUID     `json:"dataTypeID,omitempty"`
	DataTypeSlug *string        `json:"dataTypeSlug,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
	InboundID    string         `json:"inboundID"`
}

// Ordering options for ReceivingInboundItem connections
type ReceivingInboundItemOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order ReceivingInboundItems.
	Field *ReceivingInboundItemOrderField `json:"field,omitempty"`
	// Dot-notation path into a JSONB column (e.g. "meta.weight").
	JSONPath *string `json:"jsonPath,omitempty"`
	// Cast type for the extracted JSONB value.
	JSONType *JSONType `json:"jsonType,omitempty"`
}

// ReceivingInboundItemWhereInput is used for filtering InboundItem objects.
// Input was generated by ent.
type ReceivingInboundItemWhereInput struct {
	Not *ReceivingInboundItemWhereInput   `json:"not,omitempty"`
	And []*ReceivingInboundItemWhereInput `json:"and,omitempty"`
	Or  []*ReceivingInboundItemWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *string  `json:"id,omitempty"`
	IDNeq   *string  `json:"idNEQ,omitempty"`
	IDIn    []string `json:"idIn,omitempty"`
	IDNotIn []string `json:"idNotIn,omitempty"`
	IDGt    *string  `json:"idGT,omitempty"`
	IDGte   *string  `json:"idGTE,omitempty"`
	IDLt    *string  `json:"idLT,omitempty"`
	IDLte   *string  `json:"idLTE,omitempty"`
	// tenant_id field predicates
	TenantID      *uuid.UUID  `json:"tenantID,omitempty"`
	TenantIdneq   *uuid.UUID  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn    []uuid.UUID `json:"tenantIDIn,omitempty"`
	TenantIDNotIn []uuid.UUID `json:"tenantIDNotIn,omitempty"`
	TenantIdgt    *uuid.UUID  `json:"tenantIDGT,omitempty"`
	TenantIdgte   *uuid.UUID  `json:"tenantIDGTE,omitempty"`
	TenantIdlt    *uuid.UUID  `json:"tenantIDLT,omitempty"`
	TenantIdlte   *uuid.UUID  `json:"tenantIDLTE,omitempty"`
	// data_type_id field predicates
	DataTypeID       *uuid.UUID  `json:"dataTypeID,omitempty"`
	DataTypeIdneq    *uuid.UUID  `json:"dataTypeIDNEQ,omitempty"`
	DataTypeIDIn     []uuid.UUID `json:"dataTypeIDIn,omitempty"`
	DataTypeIDNotIn  []uuid.UUID `json:"dataTypeIDNotIn,omitempty"`
	DataTypeIdgt     *uuid.UUID  `json:"dataTypeIDGT,omitempty"`
	DataTypeIdgte    *uuid.UUID  `json:"dataTypeIDGTE,omitempty"`
	DataTypeIdlt     *uuid.UUID  `json:"dataTypeIDLT,omitempty"`
	DataTypeIdlte    *uuid.UUID  `json:"dataTypeIDLTE,omitempty"`
	DataTypeIDIsNil  *bool       `json:"dataTypeIDIsNil,omitempty"`
	DataTypeIDNotNil *bool       `json:"dataTypeIDNotNil,omitempty"`
	// data_type_slug field predicates
	DataTypeSlug             *string  `json:"dataTypeSlug,omitempty"`
	DataTypeSlugNeq          *string  `json:"dataTypeSlugNEQ,omitempty"`
	DataTypeSlugIn           []string `json:"dataTypeSlugIn,omitempty"`
	DataTypeSlugNotIn        []string `json:"dataTypeSlugNotIn,omitempty"`
	DataTypeSlugGt           *string  `json:"dataTypeSlugGT,omitempty"`
	DataTypeSlugGte          *string  `json:"dataTypeSlugGTE,omitempty"`
	DataTypeSlugLt           *string  `json:"dataTypeSlugLT,omitempty"`
	DataTypeSlugLte          *string  `json:"dataTypeSlugLTE,omitempty"`
	DataTypeSlugContains     *string  `json:"dataTypeSlugContains,omitempty"`
	DataTypeSlugHasPrefix    *string  `json:"dataTypeSlugHasPrefix,omitempty"`
	DataTypeSlugHasSuffix    *string  `json:"dataTypeSlugHasSuffix,omitempty"`
	DataTypeSlugIsNil        *bool    `json:"dataTypeSlugIsNil,omitempty"`
	DataTypeSlugNotNil       *bool    `json:"dataTypeSlugNotNil,omitempty"`
	DataTypeSlugEqualFold    *string  `json:"dataTypeSlugEqualFold,omitempty"`
	DataTypeSlugContainsFold *string  `json:"dataTypeSlugContainsFold,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// created_by field predicates
	CreatedBy      *uuid.UUID  `json:"createdBy,omitempty"`
	CreatedByNeq   *uuid.UUID  `json:"createdByNEQ,omitempty"`
	CreatedByIn    []uuid.UUID `json:"createdByIn,omitempty"`
	CreatedByNotIn []uuid.UUID `json:"createdByNotIn,omitempty"`
	CreatedByGt    *uuid.UUID  `json:"createdByGT,omitempty"`
	CreatedByGte   *uuid.UUID  `json:"createdByGTE,omitempty"`
	CreatedByLt    *uuid.UUID  `json:"createdByLT,omitempty"`
	CreatedByLte   *uuid.UUID  `json:"createdByLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt       *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq    *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn     []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn  []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt     *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte    *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt     *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte    *time.Time   `json:"updatedAtLTE,omitempty"`
	UpdatedAtIsNil  *bool        `json:"updatedAtIsNil,omitempty"`
	UpdatedAtNotNil *bool        `json:"updatedAtNotNil,omitempty"`
	// updated_by field predicates
	UpdatedBy       *uuid.UUID  `json:"updatedBy,omitempty"`
	UpdatedByNeq    *uuid.UUID  `json:"updatedByNEQ,omitempty"`
	UpdatedByIn     []uuid.UUID `json:"updatedByIn,omitempty"`
	UpdatedByNotIn  []uuid.UUID `json:"updatedByNotIn,omitempty"`
	UpdatedByGt     *uuid.UUID  `json:"updatedByGT,omitempty"`
	UpdatedByGte    *uuid.UUID  `json:"updatedByGTE,omitempty"`
	UpdatedByLt     *uuid.UUID  `json:"updatedByLT,omitempty"`
	UpdatedByLte    *uuid.UUID  `json:"updatedByLTE,omitempty"`
	UpdatedByIsNil  *bool       `json:"updatedByIsNil,omitempty"`
	UpdatedByNotNil *bool       `json:"updatedByNotNil,omitempty"`
	// sku field predicates
	Sku             *string  `json:"sku,omitempty"`
	SkuNeq          *string  `json:"skuNEQ,omitempty"`
	SkuIn           []string `json:"skuIn,omitempty"`
	SkuNotIn        []string `json:"skuNotIn,omitempty"`
	SkuGt           *string  `json:"skuGT,omitempty"`
	SkuGte          *string  `json:"skuGTE,omitempty"`
	SkuLt           *string  `json:"skuLT,omitempty"`
	SkuLte          *string  `json:"skuLTE,omitempty"`
	SkuContains     *string  `json:"skuContains,omitempty"`
	SkuHasPrefix    *string  `json:"skuHasPrefix,omitempty"`
	SkuHasSuffix    *string  `json:"skuHasSuffix,omitempty"`
	SkuEqualFold    *string  `json:"skuEqualFold,omitempty"`
	SkuContainsFold *string  `json:"skuContainsFold,omitempty"`
	// inbound_id field predicates
	InboundID      *string  `json:"inboundID,omitempty"`
	InboundIdneq   *string  `json:"inboundIDNEQ,omitempty"`
	InboundIDIn    []string `json:"inboundIDIn,omitempty"`
	InboundIDNotIn []string `json:"inboundIDNotIn,omitempty"`
	// quantity field predicates
	Quantity      *int  `json:"quantity,omitempty"`
	QuantityNeq   *int  `json:"quantityNEQ,omitempty"`
	QuantityIn    []int `json:"quantityIn,omitempty"`
	QuantityNotIn []int `json:"quantityNotIn,omitempty"`
	QuantityGt    *int  `json:"quantityGT,omitempty"`
	QuantityGte   *int  `json:"quantityGTE,omitempty"`
	QuantityLt    *int  `json:"quantityLT,omitempty"`
	QuantityLte   *int  `json:"quantityLTE,omitempty"`
	// inbound edge predicates
	HasInbound     *bool                         `json:"hasInbound,omitempty"`
	HasInboundWith []*ReceivingInboundWhereInput `json:"hasInboundWith,omitempty"`
	Data           []string                      `json:"Data,omitempty"`
	DataHasKey     *string                       `json:"DataHasKey,omitempty"`
	DataIn         []string                      `json:"DataIn,omitempty"`
	DataContains   []string                      `json:"DataContains,omitempty"`
}

// Ordering options for ReceivingInbound connections
type ReceivingInboundOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order ReceivingInbounds.
	Field *ReceivingInboundOrderField `json:"field,omitempty"`
	// Dot-notation path into a JSONB column (e.g. "meta.weight").
	JSONPath *string `json:"jsonPath,omitempty"`
	// Cast type for the extracted JSONB value.
	JSONType *JSONType `json:"jsonType,omitempty"`
}

// Ordering options for ReceivingInboundShipmentNotification connections
type ReceivingInboundShipmentNotificationOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order ReceivingInboundShipmentNotifications.
	Field *ReceivingInboundShipmentNotificationOrderField `json:"field,omitempty"`
	// Dot-notation path into a JSONB column (e.g. "meta.weight").
	JSONPath *string `json:"jsonPath,omitempty"`
	// Cast type for the extracted JSONB value.
	JSONType *JSONType `json:"jsonType,omitempty"`
}

// ReceivingInboundShipmentNotificationWhereInput is used for filtering InboundShipmentNotification objects.
// Input was generated by ent.
type ReceivingInboundShipmentNotificationWhereInput struct {
	Not *ReceivingInboundShipmentNotificationWhereInput   `json:"not,omitempty"`
	And []*ReceivingInboundShipmentNotificationWhereInput `json:"and,omitempty"`
	Or  []*ReceivingInboundShipmentNotificationWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *string  `json:"id,omitempty"`
	IDNeq   *string  `json:"idNEQ,omitempty"`
	IDIn    []string `json:"idIn,omitempty"`
	IDNotIn []string `json:"idNotIn,omitempty"`
	IDGt    *string  `json:"idGT,omitempty"`
	IDGte   *string  `json:"idGTE,omitempty"`
	IDLt    *string  `json:"idLT,omitempty"`
	IDLte   *string  `json:"idLTE,omitempty"`
	// tenant_id field predicates
	TenantID      *uuid.UUID  `json:"tenantID,omitempty"`
	TenantIdneq   *uuid.UUID  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn    []uuid.UUID `json:"tenantIDIn,omitempty"`
	TenantIDNotIn []uuid.UUID `json:"tenantIDNotIn,omitempty"`
	TenantIdgt    *uuid.UUID  `json:"tenantIDGT,omitempty"`
	TenantIdgte   *uuid.UUID  `json:"tenantIDGTE,omitempty"`
	TenantIdlt    *uuid.UUID  `json:"tenantIDLT,omitempty"`
	TenantIdlte   *uuid.UUID  `json:"tenantIDLTE,omitempty"`
	// data_type_id field predicates
	DataTypeID       *uuid.UUID  `json:"dataTypeID,omitempty"`
	DataTypeIdneq    *uuid.UUID  `json:"dataTypeIDNEQ,omitempty"`
	DataTypeIDIn     []uuid.UUID `json:"dataTypeIDIn,omitempty"`
	DataTypeIDNotIn  []uuid.UUID `json:"dataTypeIDNotIn,omitempty"`
	DataTypeIdgt     *uuid.UUID  `json:"dataTypeIDGT,omitempty"`
	DataTypeIdgte    *uuid.UUID  `json:"dataTypeIDGTE,omitempty"`
	DataTypeIdlt     *uuid.UUID  `json:"dataTypeIDLT,omitempty"`
	DataTypeIdlte    *uuid.UUID  `json:"dataTypeIDLTE,omitempty"`
	DataTypeIDIsNil  *bool       `json:"dataTypeIDIsNil,omitempty"`
	DataTypeIDNotNil *bool       `json:"dataTypeIDNotNil,omitempty"`
	// data_type_slug field predicates
	DataTypeSlug             *string  `json:"dataTypeSlug,omitempty"`
	DataTypeSlugNeq          *string  `json:"dataTypeSlugNEQ,omitempty"`
	DataTypeSlugIn           []string `json:"dataTypeSlugIn,omitempty"`
	DataTypeSlugNotIn        []string `json:"dataTypeSlugNotIn,omitempty"`
	DataTypeSlugGt           *string  `json:"dataTypeSlugGT,omitempty"`
	DataTypeSlugGte          *string  `json:"dataTypeSlugGTE,omitempty"`
	DataTypeSlugLt           *string  `json:"dataTypeSlugLT,omitempty"`
	DataTypeSlugLte          *string  `json:"dataTypeSlugLTE,omitempty"`
	DataTypeSlugContains     *string  `json:"dataTypeSlugContains,omitempty"`
	DataTypeSlugHasPrefix    *string  `json:"dataTypeSlugHasPrefix,omitempty"`
	DataTypeSlugHasSuffix    *string  `json:"dataTypeSlugHasSuffix,omitempty"`
	DataTypeSlugIsNil        *bool    `json:"dataTypeSlugIsNil,omitempty"`
	DataTypeSlugNotNil       *bool    `json:"dataTypeSlugNotNil,omitempty"`
	DataTypeSlugEqualFold    *string  `json:"dataTypeSlugEqualFold,omitempty"`
	DataTypeSlugContainsFold *string  `json:"dataTypeSlugContainsFold,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// created_by field predicates
	CreatedBy      *uuid.UUID  `json:"createdBy,omitempty"`
	CreatedByNeq   *uuid.UUID  `json:"createdByNEQ,omitempty"`
	CreatedByIn    []uuid.UUID `json:"createdByIn,omitempty"`
	CreatedByNotIn []uuid.UUID `json:"createdByNotIn,omitempty"`
	CreatedByGt    *uuid.UUID  `json:"createdByGT,omitempty"`
	CreatedByGte   *uuid.UUID  `json:"createdByGTE,omitempty"`
	CreatedByLt    *uuid.UUID  `json:"createdByLT,omitempty"`
	CreatedByLte   *uuid.UUID  `json:"createdByLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt       *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq    *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn     []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn  []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt     *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte    *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt     *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte    *time.Time   `json:"updatedAtLTE,omitempty"`
	UpdatedAtIsNil  *bool        `json:"updatedAtIsNil,omitempty"`
	UpdatedAtNotNil *bool        `json:"updatedAtNotNil,omitempty"`
	// updated_by field predicates
	UpdatedBy       *uuid.UUID  `json:"updatedBy,omitempty"`
	UpdatedByNeq    *uuid.UUID  `json:"updatedByNEQ,omitempty"`
	UpdatedByIn     []uuid.UUID `json:"updatedByIn,omitempty"`
	UpdatedByNotIn  []uuid.UUID `json:"updatedByNotIn,omitempty"`
	UpdatedByGt     *uuid.UUID  `json:"updatedByGT,omitempty"`
	UpdatedByGte    *uuid.UUID  `json:"updatedByGTE,omitempty"`
	UpdatedByLt     *uuid.UUID  `json:"updatedByLT,omitempty"`
	UpdatedByLte    *uuid.UUID  `json:"updatedByLTE,omitempty"`
	UpdatedByIsNil  *bool       `json:"updatedByIsNil,omitempty"`
	UpdatedByNotNil *bool       `json:"updatedByNotNil,omitempty"`
	// inbound_id field predicates
	InboundID      *string  `json:"inboundID,omitempty"`
	InboundIdneq   *string  `json:"inboundIDNEQ,omitempty"`
	InboundIDIn    []string `json:"inboundIDIn,omitempty"`
	InboundIDNotIn []string `json:"inboundIDNotIn,omitempty"`
	// inbound edge predicates
	HasInbound     *bool                         `json:"hasInbound,omitempty"`
	HasInboundWith []*ReceivingInboundWhereInput `json:"hasInboundWith,omitempty"`
	Data           []string                      `json:"Data,omitempty"`
	DataHasKey     *string                       `json:"DataHasKey,omitempty"`
	DataIn         []string                      `json:"DataIn,omitempty"`
	DataContains   []string                      `json:"DataContains,omitempty"`
}

// ReceivingInboundWhereInput is used for filtering Inbound objects.
// Input was generated by ent.
type ReceivingInboundWhereInput struct {
	Not *ReceivingInboundWhereInput   `json:"not,omitempty"`
	And []*ReceivingInboundWhereInput `json:"and,omitempty"`
	Or  []*ReceivingInboundWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *string  `json:"id,omitempty"`
	IDNeq   *string  `json:"idNEQ,omitempty"`
	IDIn    []string `json:"idIn,omitempty"`
	IDNotIn []string `json:"idNotIn,omitempty"`
	IDGt    *string  `json:"idGT,omitempty"`
	IDGte   *string  `json:"idGTE,omitempty"`
	IDLt    *string  `json:"idLT,omitempty"`
	IDLte   *string  `json:"idLTE,omitempty"`
	// tenant_id field predicates
	TenantID      *uuid.UUID  `json:"tenantID,omitempty"`
	TenantIdneq   *uuid.UUID  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn    []uuid.UUID `json:"tenantIDIn,omitempty"`
	TenantIDNotIn []uuid.UUID `json:"tenantIDNotIn,omitempty"`
	TenantIdgt    *uuid.UUID  `json:"tenantIDGT,omitempty"`
	TenantIdgte   *uuid.UUID  `json:"tenantIDGTE,omitempty"`
	TenantIdlt    *uuid.UUID  `json:"tenantIDLT,omitempty"`
	TenantIdlte   *uuid.UUID  `json:"tenantIDLTE,omitempty"`
	// data_type_id field predicates
	DataTypeID       *uuid.UUID  `json:"dataTypeID,omitempty"`
	DataTypeIdneq    *uuid.UUID  `json:"dataTypeIDNEQ,omitempty"`
	DataTypeIDIn     []uuid.UUID `json:"dataTypeIDIn,omitempty"`
	DataTypeIDNotIn  []uuid.UUID `json:"dataTypeIDNotIn,omitempty"`
	DataTypeIdgt     *uuid.UUID  `json:"dataTypeIDGT,omitempty"`
	DataTypeIdgte    *uuid.UUID  `json:"dataTypeIDGTE,omitempty"`
	DataTypeIdlt     *uuid.UUID  `json:"dataTypeIDLT,omitempty"`
	DataTypeIdlte    *uuid.UUID  `json:"dataTypeIDLTE,omitempty"`
	DataTypeIDIsNil  *bool       `json:"dataTypeIDIsNil,omitempty"`
	DataTypeIDNotNil *bool       `json:"dataTypeIDNotNil,omitempty"`
	// data_type_slug field predicates
	DataTypeSlug             *string  `json:"dataTypeSlug,omitempty"`
	DataTypeSlugNeq          *string  `json:"dataTypeSlugNEQ,omitempty"`
	DataTypeSlugIn           []string `json:"dataTypeSlugIn,omitempty"`
	DataTypeSlugNotIn        []string `json:"dataTypeSlugNotIn,omitempty"`
	DataTypeSlugGt           *string  `json:"dataTypeSlugGT,omitempty"`
	DataTypeSlugGte          *string  `json:"dataTypeSlugGTE,omitempty"`
	DataTypeSlugLt           *string  `json:"dataTypeSlugLT,omitempty"`
	DataTypeSlugLte          *string  `json:"dataTypeSlugLTE,omitempty"`
	DataTypeSlugContains     *string  `json:"dataTypeSlugContains,omitempty"`
	DataTypeSlugHasPrefix    *string  `json:"dataTypeSlugHasPrefix,omitempty"`
	DataTypeSlugHasSuffix    *string  `json:"dataTypeSlugHasSuffix,omitempty"`
	DataTypeSlugIsNil        *bool    `json:"dataTypeSlugIsNil,omitempty"`
	DataTypeSlugNotNil       *bool    `json:"dataTypeSlugNotNil,omitempty"`
	DataTypeSlugEqualFold    *string  `json:"dataTypeSlugEqualFold,omitempty"`
	DataTypeSlugContainsFold *string  `json:"dataTypeSlugContainsFold,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// created_by field predicates
	CreatedBy      *uuid.UUID  `json:"createdBy,omitempty"`
	CreatedByNeq   *uuid.UUID  `json:"createdByNEQ,omitempty"`
	CreatedByIn    []uuid.UUID `json:"createdByIn,omitempty"`
	CreatedByNotIn []uuid.UUID `json:"createdByNotIn,omitempty"`
	CreatedByGt    *uuid.UUID  `json:"createdByGT,omitempty"`
	CreatedByGte   *uuid.UUID  `json:"createdByGTE,omitempty"`
	CreatedByLt    *uuid.UUID  `json:"createdByLT,omitempty"`
	CreatedByLte   *uuid.UUID  `json:"createdByLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt       *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq    *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn     []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn  []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt     *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte    *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt     *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte    *time.Time   `json:"updatedAtLTE,omitempty"`
	UpdatedAtIsNil  *bool        `json:"updatedAtIsNil,omitempty"`
	UpdatedAtNotNil *bool        `json:"updatedAtNotNil,omitempty"`
	// updated_by field predicates
	UpdatedBy       *uuid.UUID  `json:"updatedBy,omitempty"`
	UpdatedByNeq    *uuid.UUID  `json:"updatedByNEQ,omitempty"`
	UpdatedByIn     []uuid.UUID `json:"updatedByIn,omitempty"`
	UpdatedByNotIn  []uuid.UUID `json:"updatedByNotIn,omitempty"`
	UpdatedByGt     *uuid.UUID  `json:"updatedByGT,omitempty"`
	UpdatedByGte    *uuid.UUID  `json:"updatedByGTE,omitempty"`
	UpdatedByLt     *uuid.UUID  `json:"updatedByLT,omitempty"`
	UpdatedByLte    *uuid.UUID  `json:"updatedByLTE,omitempty"`
	UpdatedByIsNil  *bool       `json:"updatedByIsNil,omitempty"`
	UpdatedByNotNil *bool       `json:"updatedByNotNil,omitempty"`
	// order_id field predicates
	OrderID             *string  `json:"orderID,omitempty"`
	OrderIdneq          *string  `json:"orderIDNEQ,omitempty"`
	OrderIDIn           []string `json:"orderIDIn,omitempty"`
	OrderIDNotIn        []string `json:"orderIDNotIn,omitempty"`
	OrderIdgt           *string  `json:"orderIDGT,omitempty"`
	OrderIdgte          *string  `json:"orderIDGTE,omitempty"`
	OrderIdlt           *string  `json:"orderIDLT,omitempty"`
	OrderIdlte          *string  `json:"orderIDLTE,omitempty"`
	OrderIDContains     *string  `json:"orderIDContains,omitempty"`
	OrderIDHasPrefix    *string  `json:"orderIDHasPrefix,omitempty"`
	OrderIDHasSuffix    *string  `json:"orderIDHasSuffix,omitempty"`
	OrderIDIsNil        *bool    `json:"orderIDIsNil,omitempty"`
	OrderIDNotNil       *bool    `json:"orderIDNotNil,omitempty"`
	OrderIDEqualFold    *string  `json:"orderIDEqualFold,omitempty"`
	OrderIDContainsFold *string  `json:"orderIDContainsFold,omitempty"`
	// supplier_id field predicates
	SupplierID      *uuid.UUID  `json:"supplierID,omitempty"`
	SupplierIdneq   *uuid.UUID  `json:"supplierIDNEQ,omitempty"`
	SupplierIDIn    []uuid.UUID `json:"supplierIDIn,omitempty"`
	SupplierIDNotIn []uuid.UUID `json:"supplierIDNotIn,omitempty"`
	SupplierIdgt    *uuid.UUID  `json:"supplierIDGT,omitempty"`
	SupplierIdgte   *uuid.UUID  `json:"supplierIDGTE,omitempty"`
	SupplierIdlt    *uuid.UUID  `json:"supplierIDLT,omitempty"`
	SupplierIdlte   *uuid.UUID  `json:"supplierIDLTE,omitempty"`
	// inboundItems edge predicates
	HasInboundItems     *bool                             `json:"hasInboundItems,omitempty"`
	HasInboundItemsWith []*ReceivingInboundItemWhereInput `json:"hasInboundItemsWith,omitempty"`
	// inboundShipmentNotifications edge predicates
	HasInboundShipmentNotifications     *bool                                             `json:"hasInboundShipmentNotifications,omitempty"`
	HasInboundShipmentNotificationsWith []*ReceivingInboundShipmentNotificationWhereInput `json:"hasInboundShipmentNotificationsWith,omitempty"`
	Data                                []string                                          `json:"Data,omitempty"`
	DataHasKey                          *string                                           `json:"DataHasKey,omitempty"`
	DataIn                              []string                                          `json:"DataIn,omitempty"`
	DataContains                        []string                                          `json:"DataContains,omitempty"`
}

// UpdateReceivingInboundInput is used for update ReceivingInbound object.
// Input was generated by ent.
type UpdateReceivingInboundInput struct {
	DataTypeID                           *uuid.UUID     `json:"dataTypeID,omitempty"`
	ClearDataTypeID                      *bool          `json:"clearDataTypeID,omitempty"`
	DataTypeSlug                         *string        `json:"dataTypeSlug,omitempty"`
	ClearDataTypeSlug                    *bool          `json:"clearDataTypeSlug,omitempty"`
	Data                                 map[string]any `json:"data,omitempty"`
	ClearData                            *bool          `json:"clearData,omitempty"`
	OrderID                              *string        `json:"orderID,omitempty"`
	ClearOrderID                         *bool          `json:"clearOrderID,omitempty"`
	SupplierID                           *uuid.UUID     `json:"supplierID,omitempty"`
	AddInboundItemIDs                    []string       `json:"addInboundItemIDs,omitempty"`
	RemoveInboundItemIDs                 []string       `json:"removeInboundItemIDs,omitempty"`
	ClearInboundItems                    *bool          `json:"clearInboundItems,omitempty"`
	AddInboundShipmentNotificationIDs    []string       `json:"addInboundShipmentNotificationIDs,omitempty"`
	RemoveInboundShipmentNotificationIDs []string       `json:"removeInboundShipmentNotificationIDs,omitempty"`
	ClearInboundShipmentNotifications    *bool          `json:"clearInboundShipmentNotifications,omitempty"`
}

// UpdateReceivingInboundItemInput is used for update ReceivingInboundItem object.
// Input was generated by ent.
type UpdateReceivingInboundItemInput struct {
	DataTypeID        *uuid.UUID     `json:"dataTypeID,omitempty"`
	ClearDataTypeID   *bool          `json:"clearDataTypeID,omitempty"`
	DataTypeSlug      *string        `json:"dataTypeSlug,omitempty"`
	ClearDataTypeSlug *bool          `json:"clearDataTypeSlug,omitempty"`
	Data              map[string]any `json:"data,omitempty"`
	ClearData         *bool          `json:"clearData,omitempty"`
	Sku               *string        `json:"sku,omitempty"`
	Quantity          *int           `json:"quantity,omitempty"`
	InboundID         *string        `json:"inboundID,omitempty"`
}

// UpdateReceivingInboundShipmentNotificationInput is used for update ReceivingInboundShipmentNotification object.
// Input was generated by ent.
type UpdateReceivingInboundShipmentNotificationInput struct {
	DataTypeID        *uuid.UUID     `json:"dataTypeID,omitempty"`
	ClearDataTypeID   *bool          `json:"clearDataTypeID,omitempty"`
	DataTypeSlug      *string        `json:"dataTypeSlug,omitempty"`
	ClearDataTypeSlug *bool          `json:"clearDataTypeSlug,omitempty"`
	Data              map[string]any `json:"data,omitempty"`
	ClearData         *bool          `json:"clearData,omitempty"`
	InboundID         *string        `json:"inboundID,omitempty"`
}

// JSON type for casting extracted JSONB values during ordering.
type JSONType string

const (
	// Cast to numeric for number comparisons.
	JSONTypeNumber JSONType = "NUMBER"
	// Cast to text for string comparisons.
	JSONTypeString JSONType = "STRING"
	// Cast to boolean for boolean comparisons.
	JSONTypeBoolean JSONType = "BOOLEAN"
)

var AllJSONType = []JSONType{
	JSONTypeNumber,
	JSONTypeString,
	JSONTypeBoolean,
}

func (e JSONType) IsValid() bool {
	switch e {
	case JSONTypeNumber, JSONTypeString, JSONTypeBoolean:
		return true
	}
	return false
}

func (e JSONType) String() string {
	return string(e)
}

func (e *JSONType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JSONType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JSONType", str)
	}
	return nil
}

func (e JSONType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JSONType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JSONType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Possible directions in which to order a list of items when provided an `orderBy` argument.
type OrderDirection string

const (
	// Specifies an ascending order for a given `orderBy` argument.
	OrderDirectionAsc OrderDirection = "ASC"
	// Specifies a descending order for a given `orderBy` argument.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Properties by which ReceivingInboundItem connections can be ordered.
type ReceivingInboundItemOrderField string

const (
	ReceivingInboundItemOrderFieldTenantID  ReceivingInboundItemOrderField = "TENANT_ID"
	ReceivingInboundItemOrderFieldCreatedAt ReceivingInboundItemOrderField = "CREATED_AT"
	ReceivingInboundItemOrderFieldCreatedBy ReceivingInboundItemOrderField = "CREATED_BY"
	ReceivingInboundItemOrderFieldUpdatedAt ReceivingInboundItemOrderField = "UPDATED_AT"
	ReceivingInboundItemOrderFieldUpdatedBy ReceivingInboundItemOrderField = "UPDATED_BY"
	ReceivingInboundItemOrderFieldDeletedAt ReceivingInboundItemOrderField = "DELETED_AT"
	ReceivingInboundItemOrderFieldDeletedBy ReceivingInboundItemOrderField = "DELETED_BY"
	ReceivingInboundItemOrderFieldSku       ReceivingInboundItemOrderField = "SKU"
	ReceivingInboundItemOrderFieldInboundID ReceivingInboundItemOrderField = "INBOUND_ID"
	ReceivingInboundItemOrderFieldQuantity  ReceivingInboundItemOrderField = "QUANTITY"
)

var AllReceivingInboundItemOrderField = []ReceivingInboundItemOrderField{
	ReceivingInboundItemOrderFieldTenantID,
	ReceivingInboundItemOrderFieldCreatedAt,
	ReceivingInboundItemOrderFieldCreatedBy,
	ReceivingInboundItemOrderFieldUpdatedAt,
	ReceivingInboundItemOrderFieldUpdatedBy,
	ReceivingInboundItemOrderFieldDeletedAt,
	ReceivingInboundItemOrderFieldDeletedBy,
	ReceivingInboundItemOrderFieldSku,
	ReceivingInboundItemOrderFieldInboundID,
	ReceivingInboundItemOrderFieldQuantity,
}

func (e ReceivingInboundItemOrderField) IsValid() bool {
	switch e {
	case ReceivingInboundItemOrderFieldTenantID, ReceivingInboundItemOrderFieldCreatedAt, ReceivingInboundItemOrderFieldCreatedBy, ReceivingInboundItemOrderFieldUpdatedAt, ReceivingInboundItemOrderFieldUpdatedBy, ReceivingInboundItemOrderFieldDeletedAt, ReceivingInboundItemOrderFieldDeletedBy, ReceivingInboundItemOrderFieldSku, ReceivingInboundItemOrderFieldInboundID, ReceivingInboundItemOrderFieldQuantity:
		return true
	}
	return false
}

func (e ReceivingInboundItemOrderField) String() string {
	return string(e)
}

func (e *ReceivingInboundItemOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReceivingInboundItemOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReceivingInboundItemOrderField", str)
	}
	return nil
}

func (e ReceivingInboundItemOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReceivingInboundItemOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReceivingInboundItemOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Properties by which ReceivingInbound connections can be ordered.
type ReceivingInboundOrderField string

const (
	ReceivingInboundOrderFieldTenantID   ReceivingInboundOrderField = "TENANT_ID"
	ReceivingInboundOrderFieldCreatedAt  ReceivingInboundOrderField = "CREATED_AT"
	ReceivingInboundOrderFieldCreatedBy  ReceivingInboundOrderField = "CREATED_BY"
	ReceivingInboundOrderFieldUpdatedAt  ReceivingInboundOrderField = "UPDATED_AT"
	ReceivingInboundOrderFieldUpdatedBy  ReceivingInboundOrderField = "UPDATED_BY"
	ReceivingInboundOrderFieldDeletedAt  ReceivingInboundOrderField = "DELETED_AT"
	ReceivingInboundOrderFieldDeletedBy  ReceivingInboundOrderField = "DELETED_BY"
	ReceivingInboundOrderFieldOrderID    ReceivingInboundOrderField = "ORDER_ID"
	ReceivingInboundOrderFieldSupplierID ReceivingInboundOrderField = "SUPPLIER_ID"
)

var AllReceivingInboundOrderField = []ReceivingInboundOrderField{
	ReceivingInboundOrderFieldTenantID,
	ReceivingInboundOrderFieldCreatedAt,
	ReceivingInboundOrderFieldCreatedBy,
	ReceivingInboundOrderFieldUpdatedAt,
	ReceivingInboundOrderFieldUpdatedBy,
	ReceivingInboundOrderFieldDeletedAt,
	ReceivingInboundOrderFieldDeletedBy,
	ReceivingInboundOrderFieldOrderID,
	ReceivingInboundOrderFieldSupplierID,
}

func (e ReceivingInboundOrderField) IsValid() bool {
	switch e {
	case ReceivingInboundOrderFieldTenantID, ReceivingInboundOrderFieldCreatedAt, ReceivingInboundOrderFieldCreatedBy, ReceivingInboundOrderFieldUpdatedAt, ReceivingInboundOrderFieldUpdatedBy, ReceivingInboundOrderFieldDeletedAt, ReceivingInboundOrderFieldDeletedBy, ReceivingInboundOrderFieldOrderID, ReceivingInboundOrderFieldSupplierID:
		return true
	}
	return false
}

func (e ReceivingInboundOrderField) String() string {
	return string(e)
}

func (e *ReceivingInboundOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReceivingInboundOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReceivingInboundOrderField", str)
	}
	return nil
}

func (e ReceivingInboundOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReceivingInboundOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReceivingInboundOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Properties by which ReceivingInboundShipmentNotification connections can be ordered.
type ReceivingInboundShipmentNotificationOrderField string

const (
	ReceivingInboundShipmentNotificationOrderFieldTenantID  ReceivingInboundShipmentNotificationOrderField = "TENANT_ID"
	ReceivingInboundShipmentNotificationOrderFieldCreatedAt ReceivingInboundShipmentNotificationOrderField = "CREATED_AT"
	ReceivingInboundShipmentNotificationOrderFieldCreatedBy ReceivingInboundShipmentNotificationOrderField = "CREATED_BY"
	ReceivingInboundShipmentNotificationOrderFieldUpdatedAt ReceivingInboundShipmentNotificationOrderField = "UPDATED_AT"
	ReceivingInboundShipmentNotificationOrderFieldUpdatedBy ReceivingInboundShipmentNotificationOrderField = "UPDATED_BY"
	ReceivingInboundShipmentNotificationOrderFieldDeletedAt ReceivingInboundShipmentNotificationOrderField = "DELETED_AT"
	ReceivingInboundShipmentNotificationOrderFieldDeletedBy ReceivingInboundShipmentNotificationOrderField = "DELETED_BY"
	ReceivingInboundShipmentNotificationOrderFieldInboundID ReceivingInboundShipmentNotificationOrderField = "INBOUND_ID"
)

var AllReceivingInboundShipmentNotificationOrderField = []ReceivingInboundShipmentNotificationOrderField{
	ReceivingInboundShipmentNotificationOrderFieldTenantID,
	ReceivingInboundShipmentNotificationOrderFieldCreatedAt,
	ReceivingInboundShipmentNotificationOrderFieldCreatedBy,
	ReceivingInboundShipmentNotificationOrderFieldUpdatedAt,
	ReceivingInboundShipmentNotificationOrderFieldUpdatedBy,
	ReceivingInboundShipmentNotificationOrderFieldDeletedAt,
	ReceivingInboundShipmentNotificationOrderFieldDeletedBy,
	ReceivingInboundShipmentNotificationOrderFieldInboundID,
}

func (e ReceivingInboundShipmentNotificationOrderField) IsValid() bool {
	switch e {
	case ReceivingInboundShipmentNotificationOrderFieldTenantID, ReceivingInboundShipmentNotificationOrderFieldCreatedAt, ReceivingInboundShipmentNotificationOrderFieldCreatedBy, ReceivingInboundShipmentNotificationOrderFieldUpdatedAt, ReceivingInboundShipmentNotificationOrderFieldUpdatedBy, ReceivingInboundShipmentNotificationOrderFieldDeletedAt, ReceivingInboundShipmentNotificationOrderFieldDeletedBy, ReceivingInboundShipmentNotificationOrderFieldInboundID:
		return true
	}
	return false
}

func (e ReceivingInboundShipmentNotificationOrderField) String() string {
	return string(e)
}

func (e *ReceivingInboundShipmentNotificationOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReceivingInboundShipmentNotificationOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReceivingInboundShipmentNotificationOrderField", str)
	}
	return nil
}

func (e ReceivingInboundShipmentNotificationOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReceivingInboundShipmentNotificationOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReceivingInboundShipmentNotificationOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
