// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/management/ent/gen"
)

type AssignRolesInput struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
	Roles    []string  `json:"roles"`
}

type AssignRolesResponse struct {
	UserID uuid.UUID `json:"userId"`
	// All per-service roles the user holds after the assignment.
	Roles []string `json:"roles"`
}

type CheckInUserDeviceInput struct {
	DeviceID uuid.UUID `json:"deviceID"`
}

type CheckInUserDeviceOutput struct {
	DeviceUser *gen.DeviceUser     `json:"deviceUser"`
	Workflows  []*TemporalWorkflow `json:"workflows"`
}

type CheckOutUserDeviceInput struct {
	DeviceID uuid.UUID `json:"deviceID"`
}

type CheckOutUserDeviceOutput struct {
	DeviceUser []*gen.DeviceUser   `json:"deviceUser"`
	Workflows  []*TemporalWorkflow `json:"workflows"`
}

type CreateEventInput struct {
	Topic       string         `json:"topic"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Example     map[string]any `json:"example,omitempty"`
}

type CustomEventPayloadInput struct {
	ID   uuid.UUID      `json:"id"`
	Data map[string]any `json:"data,omitempty"`
}

type DataTypeDeletePayload struct {
	DeletedID *uuid.UUID `json:"deletedID,omitempty"`
}

// Result of a manually-triggered tenant delete. Triggers the
// soft-delete half of the lifecycle — the row remains in the database
// and can be reactivated via restoreTenant during the grace period.
// Returns an error when the tenant does not exist; idempotent on
// already-deleted tenants.
//
// Target tenant is derived from X-Pyck-Tenant-Id (req.MutationTenantID),
// validated by tenant.Middleware; the resolver additionally enforces
// ROLE_ADMIN on that tenant before any state change.
type DeleteTenantResponse struct {
	Success bool `json:"success"`
}

type DeviceDeletePayload struct {
	DeletedID *uuid.UUID          `json:"deletedID,omitempty"`
	Workflows []*TemporalWorkflow `json:"workflows"`
}

type DeviceLocationDeletePayload struct {
	DeletedID *uuid.UUID          `json:"deletedID,omitempty"`
	Workflows []*TemporalWorkflow `json:"workflows"`
}

type DeviceLocationOutput struct {
	DeviceLocation *gen.DeviceLocation `json:"DeviceLocation"`
	Workflows      []*TemporalWorkflow `json:"workflows"`
}

type DeviceOutput struct {
	Device    *gen.Device         `json:"device"`
	Workflows []*TemporalWorkflow `json:"workflows"`
}

type GenerateJSONSchemaResponse struct {
	JSONSchema string `json:"jsonSchema"`
}

type KeyValueDeletePayload struct {
	DeletedID *uuid.UUID `json:"deletedID,omitempty"`
}

type LocationDeletePayload struct {
	DeletedID *uuid.UUID          `json:"deletedID,omitempty"`
	Workflows []*TemporalWorkflow `json:"workflows"`
}

type LocationOutput struct {
	Location  *gen.Location       `json:"location"`
	Workflows []*TemporalWorkflow `json:"workflows"`
}

type Organization struct {
	ID     *string `json:"id,omitempty"`
	Active bool    `json:"active"`
}

type RegisterTenantInput struct {
	Name           string `json:"name"`
	AdminUsername  string `json:"adminUsername"`
	AdminEmail     string `json:"adminEmail"`
	AdminFirstName string `json:"adminFirstName"`
	AdminLastName  string `json:"adminLastName"`
	AdminPassword  string `json:"adminPassword"`
	// Optional metadata for the tenant.
	// Synced to Zitadel org metadata and tenant.data.
	Data map[string]any `json:"data,omitempty"`
	// Optional expiry timestamp. Written directly to
	// tenant.expires_at; the periodic tenant-expiry-check workflow
	// soft-deletes the tenant once the timestamp is in the past.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type RegisterTenantResponse struct {
	Success bool        `json:"success"`
	Tenant  *gen.Tenant `json:"tenant,omitempty"`
}

type RemoveRolesInput struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
	Roles    []string  `json:"roles"`
}

type RemoveRolesResponse struct {
	UserID uuid.UUID `json:"userId"`
	// All per-service roles the user holds after the removal.
	Roles []string `json:"roles"`
}

// Input for restoreTenant. Target tenant derived from
// X-Pyck-Tenant-Id (req.MutationTenantID); ROLE_ADMIN required.
type RestoreTenantInput struct {
	// Optional new expiry timestamp written alongside the restore. When
	// omitted, the tenant's prior expires_at persists.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// Result of a manually-triggered tenant restore. Returns an error when
// the tenant does not exist; idempotent on already-active tenants.
type RestoreTenantResponse struct {
	Success bool `json:"success"`
}

type SendCustomEventInput struct {
	Type      string                   `json:"type"`
	Operation string                   `json:"operation"`
	Payload   *CustomEventPayloadInput `json:"payload"`
}

type SendCustomEventResponse struct {
	Success   bool                `json:"success"`
	Workflows []*TemporalWorkflow `json:"workflows"`
}

type ServiceInfo struct {
	Version string     `json:"version"`
	Date    *time.Time `json:"date,omitempty"`
}

// An assignable per-service gate role.
type ServiceRole struct {
	Key string `json:"key"`
}

type SetKeyValueInput struct {
	Name         string         `json:"name"`
	DataTypeID   *uuid.UUID     `json:"dataTypeID,omitempty"`
	DataTypeSlug *string        `json:"dataTypeSlug,omitempty"`
	Data         map[string]any `json:"data"`
}

// Input for setTenantExpiry. Target tenant derived from
// X-Pyck-Tenant-Id (req.MutationTenantID); ROLE_ADMIN required.
type SetTenantExpiryInput struct {
	// New expiry timestamp; pass null to clear.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// Result of setTenantExpiry. Returns an error when the tenant does not
// exist; soft-deleted tenants are invisible to the mutation and report
// the same error. Idempotent on the already-at-target-state cases
// (clear against empty, set matching the current value).
type SetTenantExpiryResponse struct {
	Success bool `json:"success"`
}

// Input for setTenantUITemplate. System-only (ROLE_SYSTEM / IsSystemUser).
// Per platform: set a non-empty URL template (carrying {{.Slug}}/{{.Version}}
// placeholders) to override the system-wide default, or clear*: true to drop the
// override and revert to the default. Omit both to leave the stored value
// unchanged. Setting a template and clearing it in the same call is rejected, and
// the request must change at least one field. Target tenant is derived from
// X-Pyck-Tenant-Id (req.MutationTenantID).
type SetTenantUITemplateInput struct {
	// Web UI bundle URL template (remoteWebUITemplate). Omit to leave unchanged.
	WebTemplate *string `json:"webTemplate,omitempty"`
	// Drop the per-tenant web template, reverting to the system-wide default.
	ClearWebTemplate *bool `json:"clearWebTemplate,omitempty"`
	// Mobile UI bundle URL template (remoteMobileUITemplate). Omit to leave unchanged.
	MobileTemplate *string `json:"mobileTemplate,omitempty"`
	// Drop the per-tenant mobile template, reverting to the system-wide default.
	ClearMobileTemplate *bool `json:"clearMobileTemplate,omitempty"`
}

// Result of setTenantUITemplate. Returns an error when the tenant does not
// exist. Idempotent when the provided values already match what is stored.
type SetTenantUITemplateResponse struct {
	Success bool `json:"success"`
}

type TemporalMetadata struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TemporalWorkflow struct {
	Type  string `json:"type"`
	ID    string `json:"id"`
	RunID string `json:"runID"`
}

type UpdateEventInput struct {
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Example     map[string]any `json:"example,omitempty"`
}

type UserProfile struct {
	UserID        uuid.UUID        `json:"UserID"`
	Username      string           `json:"Username"`
	Email         string           `json:"Email"`
	FirstName     string           `json:"FirstName"`
	LastName      string           `json:"LastName"`
	TenantID      uuid.UUID        `json:"TenantID"`
	TenantName    string           `json:"TenantName"`
	AssignedRoles []*UserRoleTuple `json:"AssignedRoles"`
	Tenants       []*UserTenants   `json:"Tenants"`
}

type UserRoleTuple struct {
	Role     string    `json:"Role"`
	TenantID uuid.UUID `json:"TenantID"`
}

type UserServiceRolesInput struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
}

type UserTenants struct {
	ID   uuid.UUID `json:"ID"`
	Name string    `json:"Name"`
	Role string    `json:"Role"`
}
