package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqljson"
	"github.com/pyck-ai/pyck/backend/common/sqljsonpath"
	"github.com/pyck-ai/pyck/backend/receiving/ent/gen"
	"github.com/pyck-ai/pyck/backend/receiving/ent/gen/inbound"
)

// Data is the resolver for the Data field.
func (r *receivingInboundWhereInputResolver) Data(ctx context.Context, obj *gen.ReceivingInboundWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	jsonPath, value, err := sqljsonpath.PathValue(data)
	if err != nil {
		return err
	}
	obj.AddPredicates(func(s *sql.Selector) {
		s.Where(sqljson.ValueEQ(inbound.FieldData, value, jsonPath))
	})
	return nil
}

// DataHasKey is the resolver for the DataHasKey field.
func (r *receivingInboundWhereInputResolver) DataHasKey(ctx context.Context, obj *gen.ReceivingInboundWhereInput, data *string) error {
	if obj == nil || data == nil {
		return nil
	}

	jsonPath, err := sqljsonpath.KeyPath(*data)
	if err != nil {
		return err
	}
	obj.AddPredicates(func(s *sql.Selector) {
		s.Where(sqljson.HasKey(inbound.FieldData, jsonPath))
	})
	return nil
}

// DataIn is the resolver for the DataIn field.
func (r *receivingInboundWhereInputResolver) DataIn(ctx context.Context, obj *gen.ReceivingInboundWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	jsonPath, values, err := sqljsonpath.PathValues(data)
	if err != nil {
		return err
	}
	obj.AddPredicates(func(s *sql.Selector) {
		s.Where(sqljson.ValueIn(inbound.FieldData, values, jsonPath))
	})
	return nil
}

// DataContains is the resolver for the DataContains field.
func (r *receivingInboundWhereInputResolver) DataContains(ctx context.Context, obj *gen.ReceivingInboundWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	jsonPath, value, err := sqljsonpath.PathValue(data)
	if err != nil {
		return err
	}
	obj.AddPredicates(func(s *sql.Selector) {
		s.Where(sqljson.ValueContains(inbound.FieldData, value, jsonPath))
	})
	return nil
}
