package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/common/ent/mixin"
	"github.com/pyck-ai/pyck/backend/common/gqltx"
	"github.com/pyck-ai/pyck/backend/common/jsonpatch"
	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/common/validator"
	"github.com/pyck-ai/pyck/backend/receiving"
	"github.com/pyck-ai/pyck/backend/receiving/core"
	ent "github.com/pyck-ai/pyck/backend/receiving/ent/gen"
	"github.com/pyck-ai/pyck/backend/receiving/ent/gen/inbound"
	"github.com/pyck-ai/pyck/backend/receiving/ent/gen/inbounditem"
	"github.com/pyck-ai/pyck/backend/receiving/ent/gen/inboundshipmentnotification"
	"github.com/pyck-ai/pyck/backend/receiving/model"
)

// CreateReceivingInbound is the resolver for the createReceivingInbound field.
func (r *mutationResolver) CreateReceivingInbound(ctx context.Context, input model.CreateReceivingInboundWithItemsInput) (*model.ReceivingInboundOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Validate uniqueness for inbound
	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: inbound.Table,
		FieldName: inbound.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	// Prepare and validate inbound items first
	var bulk []*ent.InboundItemCreate
	for _, item := range input.InboundItems {
		if item == nil {
			continue
		}
		itemDataType, err := r.validator.ValidateDataTypeInput(ctx, true, item.Data, item.DataTypeID, item.DataTypeSlug)
		if err != nil {
			return nil, err
		}
		mixin.PatchDataTypeIdSlugInput(item, itemDataType)
		if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
			Input:     item.Data,
			DataType:  itemDataType,
			TableName: inbound.Table,
			FieldName: inbound.FieldData,
			DbDriver:  core.Config.DbDriver,
		}); err != nil {
			return nil, err
		}
	}

	// Create inbound (MutationEventHook captures automatically, WorkflowReplyMiddleware handles reply)
	inboundInput := ent.CreateReceivingInboundInput{
		DataTypeID:   input.DataTypeID,
		DataTypeSlug: input.DataTypeSlug,
		Data:         input.Data,
		OrderID:      input.OrderID,
		SupplierID:   input.SupplierID,
	}

	receivedInbound, err := tx.Inbound.Create().SetInput(inboundInput).Save(ctx)
	if err != nil {
		return nil, err
	}

	// Create inbound items (hook captures automatically)
	for _, item := range input.InboundItems {
		if item == nil {
			continue
		}
		createInput := ent.CreateReceivingInboundItemInput{
			DataTypeID:   item.DataTypeID,
			DataTypeSlug: item.DataTypeSlug,
			Data:         item.Data,
			Sku:          item.Sku,
			Quantity:     int64(item.Quantity),
			InboundID:    receivedInbound.ID,
		}
		bulk = append(bulk, tx.InboundItem.Create().SetInput(createInput))
	}

	if _, err := tx.InboundItem.CreateBulk(bulk...).Save(ctx); err != nil {
		return nil, err
	}

	return &model.ReceivingInboundOutput{ReceivingInbound: receivedInbound}, nil
}

// UpdateReceivingInbound is the resolver for the updateReceivingInbound field.
func (r *mutationResolver) UpdateReceivingInbound(ctx context.Context, id uuid.UUID, input ent.UpdateReceivingInboundInput) (*model.ReceivingInboundOutput, error) {
	req := request.ForContext(ctx)

	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: inbound.Table,
		FieldName: inbound.FieldData,
		DbDriver:  core.Config.DbDriver,
		ExcludeID: &id,
	}); err != nil {
		return nil, err
	}

	// Remove inbound items (hook captures these as soft deletes)
	for _, v := range input.RemoveInboundItemIDs {
		_, err = tx.InboundItem.
			UpdateOneID(v).
			SetDeletedAt(time.Now().UTC()).
			SetDeletedBy(req.User().ID).
			Save(ctx)
		if err != nil {
			return nil, err
		}
	}

	// Update inbound (MutationEventHook captures automatically with field-level events)
	receivingInbound, err := tx.Inbound.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundOutput{ReceivingInbound: receivingInbound}, nil
}

// DeleteReceivingInbound is the resolver for the deleteReceivingInbound field.
func (r *mutationResolver) DeleteReceivingInbound(ctx context.Context, id uuid.UUID) (*model.ReceivingInboundDeletePayload, error) {
	req := request.ForContext(ctx)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Soft delete inbound
	_, err = tx.Inbound.
		UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	// Soft delete related inbound items
	items, err := tx.InboundItem.
		Query().
		Where(inbounditem.InboundID(id)).
		All(ctx)
	if err != nil {
		return nil, err
	}

	for _, v := range items {
		_, err = tx.InboundItem.
			UpdateOneID(v.ID).
			SetDeletedAt(time.Now().UTC()).
			SetDeletedBy(req.User().ID).
			Save(ctx)
		if err != nil {
			return nil, err
		}
	}

	return &model.ReceivingInboundDeletePayload{DeletedID: &id}, nil
}

// CreateReceivingInboundItem is the resolver for the createReceivingInboundItem field.
func (r *mutationResolver) CreateReceivingInboundItem(ctx context.Context, input ent.CreateReceivingInboundItemInput) (*model.ReceivingInboundItemOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: inbounditem.Table,
		FieldName: inbounditem.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	// Verify the parent inbound belongs to the caller's tenant.
	if _, err := tx.Inbound.Get(ctx, input.InboundID); err != nil {
		return nil, fmt.Errorf("invalid inbound: %w", err)
	}

	// Create item (MutationEventHook captures automatically, WorkflowReplyMiddleware handles reply)
	inboundItem, err := tx.InboundItem.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundItemOutput{ReceivingInboundItem: inboundItem}, nil
}

// UpdateReceivingInboundItem is the resolver for the updateReceivingInboundItem field.
func (r *mutationResolver) UpdateReceivingInboundItem(ctx context.Context, id uuid.UUID, input ent.UpdateReceivingInboundItemInput) (*model.ReceivingInboundItemOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: inbounditem.Table,
		FieldName: inbounditem.FieldData,
		DbDriver:  core.Config.DbDriver,
		ExcludeID: &id,
	}); err != nil {
		return nil, err
	}

	if input.InboundID != nil {
		if _, err := tx.Inbound.Get(ctx, *input.InboundID); err != nil {
			return nil, fmt.Errorf("invalid inbound: %w", err)
		}
	}

	// Update item (MutationEventHook captures automatically with field-level events)
	inboundItem, err := tx.InboundItem.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundItemOutput{ReceivingInboundItem: inboundItem}, nil
}

// DeleteReceivingInboundItem is the resolver for the deleteReceivingInboundItem field.
func (r *mutationResolver) DeleteReceivingInboundItem(ctx context.Context, id uuid.UUID) (*model.ReceivingInboundItemDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Soft delete item (MutationEventHook detects soft delete, WorkflowReplyMiddleware handles reply)
	_, err = tx.InboundItem.
		UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(request.ForContext(ctx).User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundItemDeletePayload{DeletedID: &id}, nil
}

// CreateReceivingInboundShipmentNotification is the resolver for the createReceivingInboundShipmentNotification field.
func (r *mutationResolver) CreateReceivingInboundShipmentNotification(ctx context.Context, input ent.CreateReceivingInboundShipmentNotificationInput) (*model.ReceivingInboundShipmentNotificationOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: inboundshipmentnotification.Table,
		FieldName: inboundshipmentnotification.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	// Verify the inbound exists and belongs to the caller's tenant
	if _, err := tx.Inbound.Get(ctx, input.InboundID); err != nil {
		return nil, fmt.Errorf("invalid inbound: %w", err)
	}

	// Create notification (MutationEventHook captures automatically, WorkflowReplyMiddleware handles reply)
	notification, err := tx.InboundShipmentNotification.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundShipmentNotificationOutput{ReceivingInboundShipmentNotification: notification}, nil
}

// UpdateReceivingInboundShipmentNotification is the resolver for the updateReceivingInboundShipmentNotification field.
func (r *mutationResolver) UpdateReceivingInboundShipmentNotification(ctx context.Context, id uuid.UUID, input ent.UpdateReceivingInboundShipmentNotificationInput) (*model.ReceivingInboundShipmentNotificationOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: inboundshipmentnotification.Table,
		FieldName: inboundshipmentnotification.FieldData,
		DbDriver:  core.Config.DbDriver,
		ExcludeID: &id,
	}); err != nil {
		return nil, err
	}

	// Verify the inbound belongs to the caller's tenant if being changed
	if input.InboundID != nil {
		if _, err := tx.Inbound.Get(ctx, *input.InboundID); err != nil {
			return nil, fmt.Errorf("invalid inbound: %w", err)
		}
	}

	// Update notification (MutationEventHook captures automatically with field-level events)
	notification, err := tx.InboundShipmentNotification.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundShipmentNotificationOutput{ReceivingInboundShipmentNotification: notification}, nil
}

// DeleteReceivingInboundShipmentNotification is the resolver for the deleteReceivingInboundShipmentNotification field.
func (r *mutationResolver) DeleteReceivingInboundShipmentNotification(ctx context.Context, id uuid.UUID) (*model.ReceivingInboundShipmentNotificationDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Soft delete notification (MutationEventHook detects soft delete, WorkflowReplyMiddleware handles reply)
	_, err = tx.InboundShipmentNotification.
		UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(request.ForContext(ctx).User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundShipmentNotificationDeletePayload{DeletedID: &id}, nil
}

// PatchReceivingInboundData applies RFC 6902 JSON Patch operations to the inbound's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchReceivingInboundData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.ReceivingInboundOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.Inbound.Query().Where(inbound.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    inbound.Table,
		FieldName:    inbound.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.Inbound.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundOutput{ReceivingInbound: updated}, nil
}

// PatchReceivingInboundItemData applies RFC 6902 JSON Patch operations to the inbound item's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchReceivingInboundItemData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.ReceivingInboundItemOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.InboundItem.Query().Where(inbounditem.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    inbounditem.Table,
		FieldName:    inbounditem.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.InboundItem.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundItemOutput{ReceivingInboundItem: updated}, nil
}

// PatchReceivingInboundShipmentNotificationData applies RFC 6902 JSON Patch operations to the notification's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchReceivingInboundShipmentNotificationData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.ReceivingInboundShipmentNotificationOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.InboundShipmentNotification.Query().Where(inboundshipmentnotification.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    inboundshipmentnotification.Table,
		FieldName:    inboundshipmentnotification.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.InboundShipmentNotification.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReceivingInboundShipmentNotificationOutput{ReceivingInboundShipmentNotification: updated}, nil
}

// Mutation returns receiving.MutationResolver implementation.
func (r *Resolver) Mutation() receiving.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
