// Code generated by "enumer -text -json -yaml -sql -gqlgen -typederrors -output=topic_gen.go -type=TopicType -trimprefix=TopicType"; DO NOT EDIT.

package topic

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"io"
	"strconv"
	"strings"
)

const _TopicTypeName = "UnknownCustomEventMutationEventDeadLetterEventMutationEventWithReplyUpdateEventWorkflowEventTemporalWorkflowStateChangeEvent"

var _TopicTypeIndex = [...]uint8{0, 7, 18, 31, 46, 68, 79, 92, 124}

const _TopicTypeLowerName = "unknowncustomeventmutationeventdeadlettereventmutationeventwithreplyupdateeventworkfloweventtemporalworkflowstatechangeevent"

func (i TopicType) String() string {
	if i < 0 || i >= TopicType(len(_TopicTypeIndex)-1) {
		return fmt.Sprintf("TopicType(%d)", i)
	}
	return _TopicTypeName[_TopicTypeIndex[i]:_TopicTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TopicTypeNoOp() {
	var x [1]struct{}
	_ = x[TopicTypeUnknown-(0)]
	_ = x[TopicTypeCustomEvent-(1)]
	_ = x[TopicTypeMutationEvent-(2)]
	_ = x[TopicTypeDeadLetterEvent-(3)]
	_ = x[TopicTypeMutationEventWithReply-(4)]
	_ = x[TopicTypeUpdateEvent-(5)]
	_ = x[TopicTypeWorkflowEvent-(6)]
	_ = x[TopicTypeTemporalWorkflowStateChangeEvent-(7)]
}

var _TopicTypeValues = []TopicType{TopicTypeUnknown, TopicTypeCustomEvent, TopicTypeMutationEvent, TopicTypeDeadLetterEvent, TopicTypeMutationEventWithReply, TopicTypeUpdateEvent, TopicTypeWorkflowEvent, TopicTypeTemporalWorkflowStateChangeEvent}

var _TopicTypeNameToValueMap = map[string]TopicType{
	_TopicTypeName[0:7]:         TopicTypeUnknown,
	_TopicTypeLowerName[0:7]:    TopicTypeUnknown,
	_TopicTypeName[7:18]:        TopicTypeCustomEvent,
	_TopicTypeLowerName[7:18]:   TopicTypeCustomEvent,
	_TopicTypeName[18:31]:       TopicTypeMutationEvent,
	_TopicTypeLowerName[18:31]:  TopicTypeMutationEvent,
	_TopicTypeName[31:46]:       TopicTypeDeadLetterEvent,
	_TopicTypeLowerName[31:46]:  TopicTypeDeadLetterEvent,
	_TopicTypeName[46:68]:       TopicTypeMutationEventWithReply,
	_TopicTypeLowerName[46:68]:  TopicTypeMutationEventWithReply,
	_TopicTypeName[68:79]:       TopicTypeUpdateEvent,
	_TopicTypeLowerName[68:79]:  TopicTypeUpdateEvent,
	_TopicTypeName[79:92]:       TopicTypeWorkflowEvent,
	_TopicTypeLowerName[79:92]:  TopicTypeWorkflowEvent,
	_TopicTypeName[92:124]:      TopicTypeTemporalWorkflowStateChangeEvent,
	_TopicTypeLowerName[92:124]: TopicTypeTemporalWorkflowStateChangeEvent,
}

var _TopicTypeNames = []string{
	_TopicTypeName[0:7],
	_TopicTypeName[7:18],
	_TopicTypeName[18:31],
	_TopicTypeName[31:46],
	_TopicTypeName[46:68],
	_TopicTypeName[68:79],
	_TopicTypeName[79:92],
	_TopicTypeName[92:124],
}

// TopicTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TopicTypeString(s string) (TopicType, error) {
	if val, ok := _TopicTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TopicTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to TopicType values", s))
}

// TopicTypeValues returns all values of the enum
func TopicTypeValues() []TopicType {
	return _TopicTypeValues
}

// TopicTypeStrings returns a slice of all String values of the enum
func TopicTypeStrings() []string {
	strs := make([]string, len(_TopicTypeNames))
	copy(strs, _TopicTypeNames)
	return strs
}

// IsATopicType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TopicType) IsATopicType() bool {
	for _, v := range _TopicTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TopicType
func (i TopicType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TopicType
func (i *TopicType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TopicType should be a string, got %s", data)
	}

	var err error
	*i, err = TopicTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TopicType
func (i TopicType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TopicType
func (i *TopicType) UnmarshalText(text []byte) error {
	var err error
	*i, err = TopicTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for TopicType
func (i TopicType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for TopicType
func (i *TopicType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = TopicTypeString(s)
	return err
}

func (i TopicType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *TopicType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of TopicType: %[1]T(%[1]v)", value)
	}

	val, err := TopicTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// MarshalGQL implements the graphql.Marshaler interface for TopicType
func (i TopicType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for TopicType
func (i *TopicType) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("TopicType should be a string, got %T", value)
	}

	var err error
	*i, err = TopicTypeString(str)
	return err
}
