name: local
variables:
  - name: env_baseurl
    value: http://localhost
  - name: env_baseurl_gateway
    value: "{{env_baseurl}}:4000"
  - name: env_baseurl_gateway_query
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_file
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_file_query
    value: "{{env_baseurl_gateway_query}}"
  - name: env_baseurl_inventory
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_inventory_query
    value: "{{env_baseurl_gateway_query}}"
  - name: env_baseurl_maindata
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_maindata_query
    value: "{{env_baseurl_gateway_query}}"
  - name: env_baseurl_management
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_management_query
    value: "{{env_baseurl_gateway_query}}"
  - name: env_baseurl_picking
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_picking_query
    value: "{{env_baseurl_gateway_query}}"
  - name: env_baseurl_receiving
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_receiving_query
    value: "{{env_baseurl_gateway_query}}"
  - name: env_baseurl_workflow
    value: "{{env_baseurl_gateway}}"
  - name: env_baseurl_workflow_query
    value: "{{env_baseurl_gateway_query}}"
  - name: env_zitadel_url
    value: http://localhost:8080
  - name: env_zitadel_client_id
    value: <bruno client-id>
