version: "3.45"

set: [errexit, nounset, pipefail]

includes:
  module:
    flatten: true
    taskfile: ../../task/module.yaml
  build:
    flatten: true
    taskfile: ../../task/build.yaml
  install:
    flatten: true
    taskfile: ../../task/install.yaml
  container:
    flatten: true
    taskfile: ../../task/container.yaml
    vars:
      NAME: picking
  atlas:
    flatten: true
    taskfile: ../../task/atlas.yaml
