// Code generated by "enumer -text -json -yaml -typederrors -output=exporttype_gen.go -type=ExportType -linecomment"; DO NOT EDIT.

package exporters

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _ExportTypeName = "fileenvk8sprocess-env"

var _ExportTypeIndex = [...]uint8{0, 4, 7, 10, 21}

const _ExportTypeLowerName = "fileenvk8sprocess-env"

func (i ExportType) String() string {
	i -= 1
	if i >= ExportType(len(_ExportTypeIndex)-1) {
		return fmt.Sprintf("ExportType(%d)", i+1)
	}
	return _ExportTypeName[_ExportTypeIndex[i]:_ExportTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ExportTypeNoOp() {
	var x [1]struct{}
	_ = x[ExportTypeFile-(1)]
	_ = x[ExportTypeEnv-(2)]
	_ = x[ExportTypeK8s-(3)]
	_ = x[ExportTypeProcessEnv-(4)]
}

var _ExportTypeValues = []ExportType{ExportTypeFile, ExportTypeEnv, ExportTypeK8s, ExportTypeProcessEnv}

var _ExportTypeNameToValueMap = map[string]ExportType{
	_ExportTypeName[0:4]:        ExportTypeFile,
	_ExportTypeLowerName[0:4]:   ExportTypeFile,
	_ExportTypeName[4:7]:        ExportTypeEnv,
	_ExportTypeLowerName[4:7]:   ExportTypeEnv,
	_ExportTypeName[7:10]:       ExportTypeK8s,
	_ExportTypeLowerName[7:10]:  ExportTypeK8s,
	_ExportTypeName[10:21]:      ExportTypeProcessEnv,
	_ExportTypeLowerName[10:21]: ExportTypeProcessEnv,
}

var _ExportTypeNames = []string{
	_ExportTypeName[0:4],
	_ExportTypeName[4:7],
	_ExportTypeName[7:10],
	_ExportTypeName[10:21],
}

// ExportTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ExportTypeString(s string) (ExportType, error) {
	if val, ok := _ExportTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ExportTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to ExportType values", s))
}

// ExportTypeValues returns all values of the enum
func ExportTypeValues() []ExportType {
	return _ExportTypeValues
}

// ExportTypeStrings returns a slice of all String values of the enum
func ExportTypeStrings() []string {
	strs := make([]string, len(_ExportTypeNames))
	copy(strs, _ExportTypeNames)
	return strs
}

// IsAExportType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ExportType) IsAExportType() bool {
	for _, v := range _ExportTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ExportType
func (i ExportType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ExportType
func (i *ExportType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ExportType should be a string, got %s", data)
	}

	var err error
	*i, err = ExportTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ExportType
func (i ExportType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ExportType
func (i *ExportType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ExportTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for ExportType
func (i ExportType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for ExportType
func (i *ExportType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ExportTypeString(s)
	return err
}
