// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package internal

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// CreateCustomerInput is used for create Customer object.
// Input was generated by ent.
type CreateCustomerInput struct {
	DataTypeID   *uuid.UUID     `json:"dataTypeID,omitempty"`
	DataTypeSlug *string        `json:"dataTypeSlug,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
}

// CreateSupplierInput is used for create Supplier object.
// Input was generated by ent.
type CreateSupplierInput struct {
	DataTypeID   *uuid.UUID     `json:"dataTypeID,omitempty"`
	DataTypeSlug *string        `json:"dataTypeSlug,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
}

// Ordering options for Customer connections
type CustomerOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order Customers.
	Field *CustomerOrderField `json:"field,omitempty"`
	// Dot-notation path into a JSONB column (e.g. "meta.weight").
	JSONPath *string `json:"jsonPath,omitempty"`
	// Cast type for the extracted JSONB value.
	JSONType *JSONType `json:"jsonType,omitempty"`
}

// CustomerWhereInput is used for filtering Customer objects.
// Input was generated by ent.
type CustomerWhereInput struct {
	Not *CustomerWhereInput   `json:"not,omitempty"`
	And []*CustomerWhereInput `json:"and,omitempty"`
	Or  []*CustomerWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *string  `json:"id,omitempty"`
	IDNeq   *string  `json:"idNEQ,omitempty"`
	IDIn    []string `json:"idIn,omitempty"`
	IDNotIn []string `json:"idNotIn,omitempty"`
	IDGt    *string  `json:"idGT,omitempty"`
	IDGte   *string  `json:"idGTE,omitempty"`
	IDLt    *string  `json:"idLT,omitempty"`
	IDLte   *string  `json:"idLTE,omitempty"`
	// tenant_id field predicates
	TenantID      *uuid.UUID  `json:"tenantID,omitempty"`
	TenantIdneq   *uuid.UUID  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn    []uuid.UUID `json:"tenantIDIn,omitempty"`
	TenantIDNotIn []uuid.UUID `json:"tenantIDNotIn,omitempty"`
	TenantIdgt    *uuid.UUID  `json:"tenantIDGT,omitempty"`
	TenantIdgte   *uuid.UUID  `json:"tenantIDGTE,omitempty"`
	TenantIdlt    *uuid.UUID  `json:"tenantIDLT,omitempty"`
	TenantIdlte   *uuid.UUID  `json:"tenantIDLTE,omitempty"`
	// data_type_id field predicates
	DataTypeID       *uuid.UUID  `json:"dataTypeID,omitempty"`
	DataTypeIdneq    *uuid.UUID  `json:"dataTypeIDNEQ,omitempty"`
	DataTypeIDIn     []uuid.UUID `json:"dataTypeIDIn,omitempty"`
	DataTypeIDNotIn  []uuid.UUID `json:"dataTypeIDNotIn,omitempty"`
	DataTypeIdgt     *uuid.UUID  `json:"dataTypeIDGT,omitempty"`
	DataTypeIdgte    *uuid.UUID  `json:"dataTypeIDGTE,omitempty"`
	DataTypeIdlt     *uuid.UUID  `json:"dataTypeIDLT,omitempty"`
	DataTypeIdlte    *uuid.UUID  `json:"dataTypeIDLTE,omitempty"`
	DataTypeIDIsNil  *bool       `json:"dataTypeIDIsNil,omitempty"`
	DataTypeIDNotNil *bool       `json:"dataTypeIDNotNil,omitempty"`
	// data_type_slug field predicates
	DataTypeSlug             *string  `json:"dataTypeSlug,omitempty"`
	DataTypeSlugNeq          *string  `json:"dataTypeSlugNEQ,omitempty"`
	DataTypeSlugIn           []string `json:"dataTypeSlugIn,omitempty"`
	DataTypeSlugNotIn        []string `json:"dataTypeSlugNotIn,omitempty"`
	DataTypeSlugGt           *string  `json:"dataTypeSlugGT,omitempty"`
	DataTypeSlugGte          *string  `json:"dataTypeSlugGTE,omitempty"`
	DataTypeSlugLt           *string  `json:"dataTypeSlugLT,omitempty"`
	DataTypeSlugLte          *string  `json:"dataTypeSlugLTE,omitempty"`
	DataTypeSlugContains     *string  `json:"dataTypeSlugContains,omitempty"`
	DataTypeSlugHasPrefix    *string  `json:"dataTypeSlugHasPrefix,omitempty"`
	DataTypeSlugHasSuffix    *string  `json:"dataTypeSlugHasSuffix,omitempty"`
	DataTypeSlugIsNil        *bool    `json:"dataTypeSlugIsNil,omitempty"`
	DataTypeSlugNotNil       *bool    `json:"dataTypeSlugNotNil,omitempty"`
	DataTypeSlugEqualFold    *string  `json:"dataTypeSlugEqualFold,omitempty"`
	DataTypeSlugContainsFold *string  `json:"dataTypeSlugContainsFold,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// created_by field predicates
	CreatedBy      *uuid.UUID  `json:"createdBy,omitempty"`
	CreatedByNeq   *uuid.UUID  `json:"createdByNEQ,omitempty"`
	CreatedByIn    []uuid.UUID `json:"createdByIn,omitempty"`
	CreatedByNotIn []uuid.UUID `json:"createdByNotIn,omitempty"`
	CreatedByGt    *uuid.UUID  `json:"createdByGT,omitempty"`
	CreatedByGte   *uuid.UUID  `json:"createdByGTE,omitempty"`
	CreatedByLt    *uuid.UUID  `json:"createdByLT,omitempty"`
	CreatedByLte   *uuid.UUID  `json:"createdByLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt       *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq    *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn     []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn  []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt     *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte    *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt     *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte    *time.Time   `json:"updatedAtLTE,omitempty"`
	UpdatedAtIsNil  *bool        `json:"updatedAtIsNil,omitempty"`
	UpdatedAtNotNil *bool        `json:"updatedAtNotNil,omitempty"`
	// updated_by field predicates
	UpdatedBy       *uuid.UUID  `json:"updatedBy,omitempty"`
	UpdatedByNeq    *uuid.UUID  `json:"updatedByNEQ,omitempty"`
	UpdatedByIn     []uuid.UUID `json:"updatedByIn,omitempty"`
	UpdatedByNotIn  []uuid.UUID `json:"updatedByNotIn,omitempty"`
	UpdatedByGt     *uuid.UUID  `json:"updatedByGT,omitempty"`
	UpdatedByGte    *uuid.UUID  `json:"updatedByGTE,omitempty"`
	UpdatedByLt     *uuid.UUID  `json:"updatedByLT,omitempty"`
	UpdatedByLte    *uuid.UUID  `json:"updatedByLTE,omitempty"`
	UpdatedByIsNil  *bool       `json:"updatedByIsNil,omitempty"`
	UpdatedByNotNil *bool       `json:"updatedByNotNil,omitempty"`
	Data            []string    `json:"Data,omitempty"`
	DataHasKey      *string     `json:"DataHasKey,omitempty"`
	DataIn          []string    `json:"DataIn,omitempty"`
	DataContains    []string    `json:"DataContains,omitempty"`
}

// Ordering options for Supplier connections
type SupplierOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order Suppliers.
	Field *SupplierOrderField `json:"field,omitempty"`
	// Dot-notation path into a JSONB column (e.g. "meta.weight").
	JSONPath *string `json:"jsonPath,omitempty"`
	// Cast type for the extracted JSONB value.
	JSONType *JSONType `json:"jsonType,omitempty"`
}

// SupplierWhereInput is used for filtering Supplier objects.
// Input was generated by ent.
type SupplierWhereInput struct {
	Not *SupplierWhereInput   `json:"not,omitempty"`
	And []*SupplierWhereInput `json:"and,omitempty"`
	Or  []*SupplierWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *string  `json:"id,omitempty"`
	IDNeq   *string  `json:"idNEQ,omitempty"`
	IDIn    []string `json:"idIn,omitempty"`
	IDNotIn []string `json:"idNotIn,omitempty"`
	IDGt    *string  `json:"idGT,omitempty"`
	IDGte   *string  `json:"idGTE,omitempty"`
	IDLt    *string  `json:"idLT,omitempty"`
	IDLte   *string  `json:"idLTE,omitempty"`
	// tenant_id field predicates
	TenantID      *uuid.UUID  `json:"tenantID,omitempty"`
	TenantIdneq   *uuid.UUID  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn    []uuid.UUID `json:"tenantIDIn,omitempty"`
	TenantIDNotIn []uuid.UUID `json:"tenantIDNotIn,omitempty"`
	TenantIdgt    *uuid.UUID  `json:"tenantIDGT,omitempty"`
	TenantIdgte   *uuid.UUID  `json:"tenantIDGTE,omitempty"`
	TenantIdlt    *uuid.UUID  `json:"tenantIDLT,omitempty"`
	TenantIdlte   *uuid.UUID  `json:"tenantIDLTE,omitempty"`
	// data_type_id field predicates
	DataTypeID       *uuid.UUID  `json:"dataTypeID,omitempty"`
	DataTypeIdneq    *uuid.UUID  `json:"dataTypeIDNEQ,omitempty"`
	DataTypeIDIn     []uuid.UUID `json:"dataTypeIDIn,omitempty"`
	DataTypeIDNotIn  []uuid.UUID `json:"dataTypeIDNotIn,omitempty"`
	DataTypeIdgt     *uuid.UUID  `json:"dataTypeIDGT,omitempty"`
	DataTypeIdgte    *uuid.UUID  `json:"dataTypeIDGTE,omitempty"`
	DataTypeIdlt     *uuid.UUID  `json:"dataTypeIDLT,omitempty"`
	DataTypeIdlte    *uuid.UUID  `json:"dataTypeIDLTE,omitempty"`
	DataTypeIDIsNil  *bool       `json:"dataTypeIDIsNil,omitempty"`
	DataTypeIDNotNil *bool       `json:"dataTypeIDNotNil,omitempty"`
	// data_type_slug field predicates
	DataTypeSlug             *string  `json:"dataTypeSlug,omitempty"`
	DataTypeSlugNeq          *string  `json:"dataTypeSlugNEQ,omitempty"`
	DataTypeSlugIn           []string `json:"dataTypeSlugIn,omitempty"`
	DataTypeSlugNotIn        []string `json:"dataTypeSlugNotIn,omitempty"`
	DataTypeSlugGt           *string  `json:"dataTypeSlugGT,omitempty"`
	DataTypeSlugGte          *string  `json:"dataTypeSlugGTE,omitempty"`
	DataTypeSlugLt           *string  `json:"dataTypeSlugLT,omitempty"`
	DataTypeSlugLte          *string  `json:"dataTypeSlugLTE,omitempty"`
	DataTypeSlugContains     *string  `json:"dataTypeSlugContains,omitempty"`
	DataTypeSlugHasPrefix    *string  `json:"dataTypeSlugHasPrefix,omitempty"`
	DataTypeSlugHasSuffix    *string  `json:"dataTypeSlugHasSuffix,omitempty"`
	DataTypeSlugIsNil        *bool    `json:"dataTypeSlugIsNil,omitempty"`
	DataTypeSlugNotNil       *bool    `json:"dataTypeSlugNotNil,omitempty"`
	DataTypeSlugEqualFold    *string  `json:"dataTypeSlugEqualFold,omitempty"`
	DataTypeSlugContainsFold *string  `json:"dataTypeSlugContainsFold,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// created_by field predicates
	CreatedBy      *uuid.UUID  `json:"createdBy,omitempty"`
	CreatedByNeq   *uuid.UUID  `json:"createdByNEQ,omitempty"`
	CreatedByIn    []uuid.UUID `json:"createdByIn,omitempty"`
	CreatedByNotIn []uuid.UUID `json:"createdByNotIn,omitempty"`
	CreatedByGt    *uuid.UUID  `json:"createdByGT,omitempty"`
	CreatedByGte   *uuid.UUID  `json:"createdByGTE,omitempty"`
	CreatedByLt    *uuid.UUID  `json:"createdByLT,omitempty"`
	CreatedByLte   *uuid.UUID  `json:"createdByLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt       *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq    *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn     []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn  []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt     *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte    *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt     *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte    *time.Time   `json:"updatedAtLTE,omitempty"`
	UpdatedAtIsNil  *bool        `json:"updatedAtIsNil,omitempty"`
	UpdatedAtNotNil *bool        `json:"updatedAtNotNil,omitempty"`
	// updated_by field predicates
	UpdatedBy       *uuid.UUID  `json:"updatedBy,omitempty"`
	UpdatedByNeq    *uuid.UUID  `json:"updatedByNEQ,omitempty"`
	UpdatedByIn     []uuid.UUID `json:"updatedByIn,omitempty"`
	UpdatedByNotIn  []uuid.UUID `json:"updatedByNotIn,omitempty"`
	UpdatedByGt     *uuid.UUID  `json:"updatedByGT,omitempty"`
	UpdatedByGte    *uuid.UUID  `json:"updatedByGTE,omitempty"`
	UpdatedByLt     *uuid.UUID  `json:"updatedByLT,omitempty"`
	UpdatedByLte    *uuid.UUID  `json:"updatedByLTE,omitempty"`
	UpdatedByIsNil  *bool       `json:"updatedByIsNil,omitempty"`
	UpdatedByNotNil *bool       `json:"updatedByNotNil,omitempty"`
	Data            []string    `json:"Data,omitempty"`
	DataHasKey      *string     `json:"DataHasKey,omitempty"`
	DataIn          []string    `json:"DataIn,omitempty"`
	DataContains    []string    `json:"DataContains,omitempty"`
}

// UpdateCustomerInput is used for update Customer object.
// Input was generated by ent.
type UpdateCustomerInput struct {
	DataTypeID        *uuid.UUID     `json:"dataTypeID,omitempty"`
	ClearDataTypeID   *bool          `json:"clearDataTypeID,omitempty"`
	DataTypeSlug      *string        `json:"dataTypeSlug,omitempty"`
	ClearDataTypeSlug *bool          `json:"clearDataTypeSlug,omitempty"`
	Data              map[string]any `json:"data,omitempty"`
	ClearData         *bool          `json:"clearData,omitempty"`
}

// UpdateSupplierInput is used for update Supplier object.
// Input was generated by ent.
type UpdateSupplierInput struct {
	DataTypeID        *uuid.UUID     `json:"dataTypeID,omitempty"`
	ClearDataTypeID   *bool          `json:"clearDataTypeID,omitempty"`
	DataTypeSlug      *string        `json:"dataTypeSlug,omitempty"`
	ClearDataTypeSlug *bool          `json:"clearDataTypeSlug,omitempty"`
	Data              map[string]any `json:"data,omitempty"`
	ClearData         *bool          `json:"clearData,omitempty"`
}

// Properties by which Customer connections can be ordered.
type CustomerOrderField string

const (
	CustomerOrderFieldTenantID  CustomerOrderField = "TENANT_ID"
	CustomerOrderFieldCreatedAt CustomerOrderField = "CREATED_AT"
	CustomerOrderFieldCreatedBy CustomerOrderField = "CREATED_BY"
	CustomerOrderFieldUpdatedAt CustomerOrderField = "UPDATED_AT"
	CustomerOrderFieldUpdatedBy CustomerOrderField = "UPDATED_BY"
	CustomerOrderFieldDeletedAt CustomerOrderField = "DELETED_AT"
	CustomerOrderFieldDeletedBy CustomerOrderField = "DELETED_BY"
)

var AllCustomerOrderField = []CustomerOrderField{
	CustomerOrderFieldTenantID,
	CustomerOrderFieldCreatedAt,
	CustomerOrderFieldCreatedBy,
	CustomerOrderFieldUpdatedAt,
	CustomerOrderFieldUpdatedBy,
	CustomerOrderFieldDeletedAt,
	CustomerOrderFieldDeletedBy,
}

func (e CustomerOrderField) IsValid() bool {
	switch e {
	case CustomerOrderFieldTenantID, CustomerOrderFieldCreatedAt, CustomerOrderFieldCreatedBy, CustomerOrderFieldUpdatedAt, CustomerOrderFieldUpdatedBy, CustomerOrderFieldDeletedAt, CustomerOrderFieldDeletedBy:
		return true
	}
	return false
}

func (e CustomerOrderField) String() string {
	return string(e)
}

func (e *CustomerOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CustomerOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CustomerOrderField", str)
	}
	return nil
}

func (e CustomerOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CustomerOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CustomerOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// JSON type for casting extracted JSONB values during ordering.
type JSONType string

const (
	// Cast to numeric for number comparisons.
	JSONTypeNumber JSONType = "NUMBER"
	// Cast to text for string comparisons.
	JSONTypeString JSONType = "STRING"
	// Cast to boolean for boolean comparisons.
	JSONTypeBoolean JSONType = "BOOLEAN"
)

var AllJSONType = []JSONType{
	JSONTypeNumber,
	JSONTypeString,
	JSONTypeBoolean,
}

func (e JSONType) IsValid() bool {
	switch e {
	case JSONTypeNumber, JSONTypeString, JSONTypeBoolean:
		return true
	}
	return false
}

func (e JSONType) String() string {
	return string(e)
}

func (e *JSONType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JSONType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JSONType", str)
	}
	return nil
}

func (e JSONType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JSONType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JSONType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Possible directions in which to order a list of items when provided an `orderBy` argument.
type OrderDirection string

const (
	// Specifies an ascending order for a given `orderBy` argument.
	OrderDirectionAsc OrderDirection = "ASC"
	// Specifies a descending order for a given `orderBy` argument.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Properties by which Supplier connections can be ordered.
type SupplierOrderField string

const (
	SupplierOrderFieldTenantID  SupplierOrderField = "TENANT_ID"
	SupplierOrderFieldCreatedAt SupplierOrderField = "CREATED_AT"
	SupplierOrderFieldCreatedBy SupplierOrderField = "CREATED_BY"
	SupplierOrderFieldUpdatedAt SupplierOrderField = "UPDATED_AT"
	SupplierOrderFieldUpdatedBy SupplierOrderField = "UPDATED_BY"
	SupplierOrderFieldDeletedAt SupplierOrderField = "DELETED_AT"
	SupplierOrderFieldDeletedBy SupplierOrderField = "DELETED_BY"
)

var AllSupplierOrderField = []SupplierOrderField{
	SupplierOrderFieldTenantID,
	SupplierOrderFieldCreatedAt,
	SupplierOrderFieldCreatedBy,
	SupplierOrderFieldUpdatedAt,
	SupplierOrderFieldUpdatedBy,
	SupplierOrderFieldDeletedAt,
	SupplierOrderFieldDeletedBy,
}

func (e SupplierOrderField) IsValid() bool {
	switch e {
	case SupplierOrderFieldTenantID, SupplierOrderFieldCreatedAt, SupplierOrderFieldCreatedBy, SupplierOrderFieldUpdatedAt, SupplierOrderFieldUpdatedBy, SupplierOrderFieldDeletedAt, SupplierOrderFieldDeletedBy:
		return true
	}
	return false
}

func (e SupplierOrderField) String() string {
	return string(e)
}

func (e *SupplierOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SupplierOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SupplierOrderField", str)
	}
	return nil
}

func (e SupplierOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SupplierOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SupplierOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
