// Code generated by "enumer -text -json -yaml -sql -gqlgen -typederrors -output=protocol_gen.go -type=ProtocolType -linecomment"; DO NOT EDIT.

package otel

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"io"
	"strconv"
	"strings"
)

const _ProtocolTypeName = "invalidgrpchttphttp/protobuf"

var _ProtocolTypeIndex = [...]uint8{0, 7, 11, 15, 28}

const _ProtocolTypeLowerName = "invalidgrpchttphttp/protobuf"

func (i ProtocolType) String() string {
	if i >= ProtocolType(len(_ProtocolTypeIndex)-1) {
		return fmt.Sprintf("ProtocolType(%d)", i)
	}
	return _ProtocolTypeName[_ProtocolTypeIndex[i]:_ProtocolTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProtocolTypeNoOp() {
	var x [1]struct{}
	_ = x[ProtocolTypeInvalid-(0)]
	_ = x[ProtocolTypeGRPC-(1)]
	_ = x[ProtocolTypeHTTP-(2)]
	_ = x[ProtocolTypeHTTPProtobuf-(3)]
}

var _ProtocolTypeValues = []ProtocolType{ProtocolTypeInvalid, ProtocolTypeGRPC, ProtocolTypeHTTP, ProtocolTypeHTTPProtobuf}

var _ProtocolTypeNameToValueMap = map[string]ProtocolType{
	_ProtocolTypeName[0:7]:        ProtocolTypeInvalid,
	_ProtocolTypeLowerName[0:7]:   ProtocolTypeInvalid,
	_ProtocolTypeName[7:11]:       ProtocolTypeGRPC,
	_ProtocolTypeLowerName[7:11]:  ProtocolTypeGRPC,
	_ProtocolTypeName[11:15]:      ProtocolTypeHTTP,
	_ProtocolTypeLowerName[11:15]: ProtocolTypeHTTP,
	_ProtocolTypeName[15:28]:      ProtocolTypeHTTPProtobuf,
	_ProtocolTypeLowerName[15:28]: ProtocolTypeHTTPProtobuf,
}

var _ProtocolTypeNames = []string{
	_ProtocolTypeName[0:7],
	_ProtocolTypeName[7:11],
	_ProtocolTypeName[11:15],
	_ProtocolTypeName[15:28],
}

// ProtocolTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProtocolTypeString(s string) (ProtocolType, error) {
	if val, ok := _ProtocolTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProtocolTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to ProtocolType values", s))
}

// ProtocolTypeValues returns all values of the enum
func ProtocolTypeValues() []ProtocolType {
	return _ProtocolTypeValues
}

// ProtocolTypeStrings returns a slice of all String values of the enum
func ProtocolTypeStrings() []string {
	strs := make([]string, len(_ProtocolTypeNames))
	copy(strs, _ProtocolTypeNames)
	return strs
}

// IsAProtocolType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProtocolType) IsAProtocolType() bool {
	for _, v := range _ProtocolTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ProtocolType
func (i ProtocolType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProtocolType
func (i *ProtocolType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ProtocolType should be a string, got %s", data)
	}

	var err error
	*i, err = ProtocolTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ProtocolType
func (i ProtocolType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ProtocolType
func (i *ProtocolType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ProtocolTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for ProtocolType
func (i ProtocolType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for ProtocolType
func (i *ProtocolType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ProtocolTypeString(s)
	return err
}

func (i ProtocolType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ProtocolType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ProtocolType: %[1]T(%[1]v)", value)
	}

	val, err := ProtocolTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// MarshalGQL implements the graphql.Marshaler interface for ProtocolType
func (i ProtocolType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for ProtocolType
func (i *ProtocolType) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("ProtocolType should be a string, got %T", value)
	}

	var err error
	*i, err = ProtocolTypeString(str)
	return err
}
