// Code generated by ent, DO NOT EDIT.
//
// This file simulates the generated all_pages.go in real services.
// The analyzer should NOT flag .All(ctx) calls inside ent/gen even
// though Item has LimitMixin.

package gentest

import "context"

func unusedNoFlagInGenerated(ctx context.Context, c *Client) {
	_, _ = c.Item.Query().All(ctx)
}
