// Code generated by "enumer -text -json -yaml -sql -gqlgen -typederrors -output=workflowtarget_gen.go -type=WorkflowTarget -trimprefix=WorkflowTarget"; DO NOT EDIT.

package workflow

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"io"
	"strconv"
	"strings"
)

const _WorkflowTargetName = "UNKNOWNWEBMOBILESETUP"

var _WorkflowTargetIndex = [...]uint8{0, 7, 10, 16, 21}

const _WorkflowTargetLowerName = "unknownwebmobilesetup"

func (i WorkflowTarget) String() string {
	if i >= WorkflowTarget(len(_WorkflowTargetIndex)-1) {
		return fmt.Sprintf("WorkflowTarget(%d)", i)
	}
	return _WorkflowTargetName[_WorkflowTargetIndex[i]:_WorkflowTargetIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _WorkflowTargetNoOp() {
	var x [1]struct{}
	_ = x[WorkflowTargetUNKNOWN-(0)]
	_ = x[WorkflowTargetWEB-(1)]
	_ = x[WorkflowTargetMOBILE-(2)]
	_ = x[WorkflowTargetSETUP-(3)]
}

var _WorkflowTargetValues = []WorkflowTarget{WorkflowTargetUNKNOWN, WorkflowTargetWEB, WorkflowTargetMOBILE, WorkflowTargetSETUP}

var _WorkflowTargetNameToValueMap = map[string]WorkflowTarget{
	_WorkflowTargetName[0:7]:        WorkflowTargetUNKNOWN,
	_WorkflowTargetLowerName[0:7]:   WorkflowTargetUNKNOWN,
	_WorkflowTargetName[7:10]:       WorkflowTargetWEB,
	_WorkflowTargetLowerName[7:10]:  WorkflowTargetWEB,
	_WorkflowTargetName[10:16]:      WorkflowTargetMOBILE,
	_WorkflowTargetLowerName[10:16]: WorkflowTargetMOBILE,
	_WorkflowTargetName[16:21]:      WorkflowTargetSETUP,
	_WorkflowTargetLowerName[16:21]: WorkflowTargetSETUP,
}

var _WorkflowTargetNames = []string{
	_WorkflowTargetName[0:7],
	_WorkflowTargetName[7:10],
	_WorkflowTargetName[10:16],
	_WorkflowTargetName[16:21],
}

// WorkflowTargetString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func WorkflowTargetString(s string) (WorkflowTarget, error) {
	if val, ok := _WorkflowTargetNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _WorkflowTargetNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to WorkflowTarget values", s))
}

// WorkflowTargetValues returns all values of the enum
func WorkflowTargetValues() []WorkflowTarget {
	return _WorkflowTargetValues
}

// WorkflowTargetStrings returns a slice of all String values of the enum
func WorkflowTargetStrings() []string {
	strs := make([]string, len(_WorkflowTargetNames))
	copy(strs, _WorkflowTargetNames)
	return strs
}

// IsAWorkflowTarget returns "true" if the value is listed in the enum definition. "false" otherwise
func (i WorkflowTarget) IsAWorkflowTarget() bool {
	for _, v := range _WorkflowTargetValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for WorkflowTarget
func (i WorkflowTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for WorkflowTarget
func (i *WorkflowTarget) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("WorkflowTarget should be a string, got %s", data)
	}

	var err error
	*i, err = WorkflowTargetString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for WorkflowTarget
func (i WorkflowTarget) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for WorkflowTarget
func (i *WorkflowTarget) UnmarshalText(text []byte) error {
	var err error
	*i, err = WorkflowTargetString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for WorkflowTarget
func (i WorkflowTarget) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for WorkflowTarget
func (i *WorkflowTarget) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = WorkflowTargetString(s)
	return err
}

func (i WorkflowTarget) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *WorkflowTarget) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of WorkflowTarget: %[1]T(%[1]v)", value)
	}

	val, err := WorkflowTargetString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// MarshalGQL implements the graphql.Marshaler interface for WorkflowTarget
func (i WorkflowTarget) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for WorkflowTarget
func (i *WorkflowTarget) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("WorkflowTarget should be a string, got %T", value)
	}

	var err error
	*i, err = WorkflowTargetString(str)
	return err
}
