package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/picking"
	"github.com/pyck-ai/pyck/backend/picking/ent/gen"
)

// FindPickingOrderByID is the resolver for the findPickingOrderByID field.
func (r *entityResolver) FindPickingOrderByID(ctx context.Context, id uuid.UUID) (*gen.Order, error) {
	order, err := r.client.Order.Query().Where(func(s *sql.Selector) {
		s.Where(sql.EQ("id", id))
	}).First(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed reading picking order: %w", err)
	}

	return order, nil
}

// FindPickingOrderItemBySku is the resolver for the findPickingOrderItemBySku field.
func (r *entityResolver) FindPickingOrderItemBySku(ctx context.Context, sku string) (*gen.OrderItems, error) {
	orderItem, err := r.client.OrderItems.Query().Where(func(s *sql.Selector) {
		s.Where(sql.EQ("sku", sku))
	}).First(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed reading picking order item: %w", err)
	}

	return orderItem, nil
}

// Entity returns picking.EntityResolver implementation.
func (r *Resolver) Entity() picking.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
