package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/common/ent/mixin"
	"github.com/pyck-ai/pyck/backend/common/gqltx"
	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/common/validator"
	"github.com/pyck-ai/pyck/backend/picking"
	"github.com/pyck-ai/pyck/backend/picking/core"
	ent "github.com/pyck-ai/pyck/backend/picking/ent/gen"
	"github.com/pyck-ai/pyck/backend/picking/ent/gen/order"
	"github.com/pyck-ai/pyck/backend/picking/ent/gen/orderitems"
	"github.com/pyck-ai/pyck/backend/picking/ent/gen/outboundshipmentnotification"
	"github.com/pyck-ai/pyck/backend/picking/model"
)

// CreatePickingOrder is the resolver for the createPickingOrder field.
func (r *mutationResolver) CreatePickingOrder(ctx context.Context, input model.CreatePickingOrderWithItemsInput) (*model.PickingOrderOutput, error) {
	// MutationEventHook captures the mutation automatically.

	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Validate uniqueness for picking order
	if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: order.Table,
		FieldName: order.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	// Prepare and validate order items first
	for _, item := range input.OrderItems {
		if item == nil {
			continue
		}
		itemDataType, err := r.validator.ValidateDataTypeInput(ctx, true, item.Data, item.DataTypeID, item.DataTypeSlug)
		if err != nil {
			return nil, err
		}
		mixin.PatchDataTypeIdSlugInput(item, itemDataType)
		if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
			Input:     item.Data,
			DataType:  itemDataType,
			TableName: orderitems.Table,
			FieldName: orderitems.FieldData,
			DbDriver:  core.Config.DbDriver,
		}); err != nil {
			return nil, err
		}
	}

	// Create picking order (MutationEventHook captures automatically, WorkflowReplyMiddleware handles reply)
	orderInput := ent.CreatePickingOrderInput{
		DataTypeID:   input.DataTypeID,
		DataTypeSlug: input.DataTypeSlug,
		Data:         input.Data,
		CustomerID:   input.CustomerID,
	}
	createdOrder, err := tx.Order.Create().SetInput(orderInput).Save(ctx)
	if err != nil {
		return nil, err
	}

	// Create order items (hook captures automatically)
	var bulk []*ent.OrderItemsCreate
	for _, item := range input.OrderItems {
		if item == nil {
			continue
		}
		createInput := ent.CreatePickingOrderItemInput{
			DataTypeID:   item.DataTypeID,
			DataTypeSlug: item.DataTypeSlug,
			Data:         item.Data,
			Sku:          item.Sku,
			Quantity:     int64(item.Quantity),
			OrderID:      createdOrder.ID,
		}
		bulk = append(bulk, tx.OrderItems.Create().SetInput(createInput))
	}

	if _, err := tx.OrderItems.CreateBulk(bulk...).Save(ctx); err != nil {
		return nil, err
	}

	return &model.PickingOrderOutput{PickingOrder: createdOrder}, nil
}

// UpdatePickingOrder is the resolver for the updatePickingOrder field.
func (r *mutationResolver) UpdatePickingOrder(ctx context.Context, id uuid.UUID, input ent.UpdatePickingOrderInput) (*model.PickingOrderOutput, error) {
	// MutationEventHook captures the mutation automatically with field-level events.

	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: order.Table,
		FieldName: order.FieldData,
		DbDriver:  core.Config.DbDriver,
		ExcludeID: &id,
	}); err != nil {
		return nil, err
	}

	// Update picking order (MutationEventHook captures automatically with field-level events)
	updated, err := tx.Order.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.PickingOrderOutput{PickingOrder: updated}, nil
}

// DeletePickingOrder is the resolver for the deletePickingOrder field.
func (r *mutationResolver) DeletePickingOrder(ctx context.Context, id uuid.UUID) (*model.PickingOrderDeletePayload, error) {
	// MutationEventHook captures the mutation automatically.
	req := request.ForContext(ctx)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Soft delete order (MutationEventHook detects soft delete, WorkflowReplyMiddleware handles reply)
	_, err = tx.Order.
		UpdateOneID(id).
		SetDeletedAt(time.Now()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	// Soft delete related order items
	items, err := tx.OrderItems.
		Query().
		Where(orderitems.OrderID(id)).
		All(ctx)
	if err != nil {
		return nil, err
	}

	for _, v := range items {
		_, err = tx.OrderItems.
			UpdateOneID(v.ID).
			SetDeletedAt(time.Now()).
			SetDeletedBy(req.User().ID).
			Save(ctx)
		if err != nil {
			return nil, err
		}
	}

	return &model.PickingOrderDeletePayload{DeletedID: &id}, nil
}

// CreatePickingOrderItem is the resolver for the createPickingOrderItem field.
func (r *mutationResolver) CreatePickingOrderItem(ctx context.Context, input ent.CreatePickingOrderItemInput) (*model.PickingOrderItemOutput, error) {
	// MutationEventHook captures the mutation automatically.

	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: orderitems.Table,
		FieldName: orderitems.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	// Verify the parent order belongs to the caller's tenant.
	if _, err := tx.Order.Get(ctx, input.OrderID); err != nil {
		return nil, fmt.Errorf("invalid order: %w", err)
	}

	// Create item (MutationEventHook captures automatically, WorkflowReplyMiddleware handles reply)
	orderItem, err := tx.OrderItems.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.PickingOrderItemOutput{PickingOrderItem: orderItem}, nil
}

// UpdatePickingOrderItem is the resolver for the updatePickingOrderItem field.
func (r *mutationResolver) UpdatePickingOrderItem(ctx context.Context, id uuid.UUID, input ent.UpdatePickingOrderItemInput) (*model.PickingOrderItemOutput, error) {
	// MutationEventHook captures the mutation automatically with field-level events.

	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: orderitems.Table,
		FieldName: orderitems.FieldData,
		DbDriver:  core.Config.DbDriver,
		ExcludeID: &id,
	}); err != nil {
		return nil, err
	}

	if input.OrderID != nil {
		if _, err := tx.Order.Get(ctx, *input.OrderID); err != nil {
			return nil, fmt.Errorf("invalid order: %w", err)
		}
	}

	// Update item (MutationEventHook captures automatically with field-level events)
	orderItem, err := tx.OrderItems.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.PickingOrderItemOutput{PickingOrderItem: orderItem}, nil
}

// DeletePickingOrderItem is the resolver for the deletePickingOrderItem field.
func (r *mutationResolver) DeletePickingOrderItem(ctx context.Context, id uuid.UUID) (*model.PickingOrderItemDeletePayload, error) {
	// MutationEventHook captures the mutation automatically.

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Soft delete item (MutationEventHook detects soft delete, WorkflowReplyMiddleware handles reply)
	_, err = tx.OrderItems.
		UpdateOneID(id).
		SetDeletedAt(time.Now()).
		SetDeletedBy(request.ForContext(ctx).User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.PickingOrderItemDeletePayload{DeletedID: &id}, nil
}

// CreatePickingOutboundShipmentNotification is the resolver for the createPickingOutboundShipmentNotification field.
func (r *mutationResolver) CreatePickingOutboundShipmentNotification(ctx context.Context, input ent.CreatePickingOutboundShipmentNotificationInput) (*model.PickingOutboundShipmentNotificationOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: outboundshipmentnotification.Table,
		FieldName: outboundshipmentnotification.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	// Verify the order exists and belongs to the caller's tenant
	if _, err := tx.Order.Get(ctx, input.OrderID); err != nil {
		return nil, fmt.Errorf("invalid order: %w", err)
	}

	// Create notification (MutationEventHook captures automatically, WorkflowReplyMiddleware handles reply)
	notification, err := tx.OutboundShipmentNotification.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.PickingOutboundShipmentNotificationOutput{PickingOutboundShipmentNotification: notification}, nil
}

// UpdatePickingOutboundShipmentNotification is the resolver for the updatePickingOutboundShipmentNotification field.
func (r *mutationResolver) UpdatePickingOutboundShipmentNotification(ctx context.Context, id uuid.UUID, input ent.UpdatePickingOutboundShipmentNotificationInput) (*model.PickingOutboundShipmentNotificationOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: outboundshipmentnotification.Table,
		FieldName: outboundshipmentnotification.FieldData,
		DbDriver:  core.Config.DbDriver,
		ExcludeID: &id,
	}); err != nil {
		return nil, err
	}

	// Verify the order belongs to the caller's tenant if being changed
	if input.OrderID != nil {
		if _, err := tx.Order.Get(ctx, *input.OrderID); err != nil {
			return nil, fmt.Errorf("invalid order: %w", err)
		}
	}

	// Update notification (MutationEventHook captures automatically with field-level events)
	notification, err := tx.OutboundShipmentNotification.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.PickingOutboundShipmentNotificationOutput{PickingOutboundShipmentNotification: notification}, nil
}

// DeletePickingOutboundShipmentNotification is the resolver for the deletePickingOutboundShipmentNotification field.
func (r *mutationResolver) DeletePickingOutboundShipmentNotification(ctx context.Context, id uuid.UUID) (*model.PickingOutboundShipmentNotificationDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Soft delete notification (MutationEventHook detects soft delete, WorkflowReplyMiddleware handles reply)
	_, err = tx.OutboundShipmentNotification.
		UpdateOneID(id).
		SetDeletedAt(time.Now()).
		SetDeletedBy(request.ForContext(ctx).User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.PickingOutboundShipmentNotificationDeletePayload{DeletedID: &id}, nil
}

// Mutation returns picking.MutationResolver implementation.
func (r *Resolver) Mutation() picking.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
