package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqljson"
	"github.com/pyck-ai/pyck/backend/common/sqljsonpath"
	"github.com/pyck-ai/pyck/backend/picking/ent/gen"
	"github.com/pyck-ai/pyck/backend/picking/ent/gen/order"
)

// Data is the resolver for the Data field.
func (r *pickingOrderWhereInputResolver) Data(ctx context.Context, obj *gen.PickingOrderWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		jsonPath, err := sqljsonpath.DotPath(data[0])
		if err != nil {
			return err
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueEQ(order.FieldData, data[1], jsonPath))
		})
	}
	return nil
}

// DataHasKey is the resolver for the DataHasKey field.
func (r *pickingOrderWhereInputResolver) DataHasKey(ctx context.Context, obj *gen.PickingOrderWhereInput, data *string) error {
	if obj == nil || data == nil {
		return nil
	}

	if *data != "" {
		jsonPath, err := sqljsonpath.DotPath(*data)
		if err != nil {
			return err
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.HasKey(order.FieldData, jsonPath))
		})
	}
	return nil
}

// DataIn is the resolver for the DataIn field.
func (r *pickingOrderWhereInputResolver) DataIn(ctx context.Context, obj *gen.PickingOrderWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) >= 2 {
		var args []any
		for _, v := range data[1:] {
			args = append(args, v)
		}
		jsonPath, err := sqljsonpath.DotPath(data[0])
		if err != nil {
			return err
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueIn(order.FieldData, args, jsonPath))
		})
	}
	return nil
}

// DataContains is the resolver for the DataContains field.
func (r *pickingOrderWhereInputResolver) DataContains(ctx context.Context, obj *gen.PickingOrderWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		jsonPath, err := sqljsonpath.DotPath(data[0])
		if err != nil {
			return err
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueContains(order.FieldData, data[1], jsonPath))
		})
	}
	return nil
}
