// Package txid carries the per-DB-transaction UUID v7 generated by the
// gqltx middleware. It is intentionally a leaf package (no dependencies
// on other backend/common packages) so it can be imported from both
// gqltx (writer) and events (reader) without a cycle.
//
// Semantics: gqltx generates a fresh UUID at every BeginTx (so OCC retries
// see distinct IDs) and stores it on the per-attempt context. The outbox
// hook persists it in the outbox row; the outbox handler embeds it in the
// NATS JetStream message ID for deterministic, transaction-scoped
// deduplication.
package txid

import (
	"context"

	"github.com/google/uuid"

	"github.com/pyck-ai/pyck/backend/common/uuidgql"
)

type ctxKey struct{}

// With returns a derived context carrying txID.
func With(ctx context.Context, txID uuid.UUID) context.Context {
	return context.WithValue(ctx, ctxKey{}, txID)
}

// FromContext returns the transaction ID injected by the Tx middleware.
// Returns uuid.Nil and false when no tx is active on ctx (read-only path,
// background goroutine, etc).
func FromContext(ctx context.Context) (uuid.UUID, bool) {
	if v := ctx.Value(ctxKey{}); v != nil {
		if id, ok := v.(uuid.UUID); ok && id != uuid.Nil {
			return id, true
		}
	}
	return uuid.Nil, false
}

// New generates a fresh transaction ID. Used by gqltx at BeginTx and by
// tests that need to forge a tx context without running the full
// middleware.
func New() uuid.UUID {
	return uuidgql.GenerateV7UUID()
}
