package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/file"
	"github.com/pyck-ai/pyck/backend/file/ent/gen"
	entfile "github.com/pyck-ai/pyck/backend/file/ent/gen/file"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id uuid.UUID) (gen.Noder, error) {
	return r.client.Noder(ctx, id, gen.WithFixedNodeType(entfile.Table))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []uuid.UUID) ([]gen.Noder, error) {
	return r.client.Noders(ctx, ids, gen.WithFixedNodeType(entfile.Table))
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, orderBy *gen.FileOrder, where *gen.FileWhereInput) (*gen.FileConnection, error) {
	return r.client.File.Query().
		Paginate(ctx, after, first, before, last,
			gen.WithFileOrder(orderBy),
			gen.WithFileFilter(where.Filter))
}

// File returns file.FileResolver implementation.
func (r *Resolver) File() file.FileResolver { return &fileResolver{r} }

// Query returns file.QueryResolver implementation.
func (r *Resolver) Query() file.QueryResolver { return &queryResolver{r} }

// FileWhereInput returns file.FileWhereInputResolver implementation.
func (r *Resolver) FileWhereInput() file.FileWhereInputResolver { return &fileWhereInputResolver{r} }

type fileResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type fileWhereInputResolver struct{ *Resolver }
