package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/file/ent/gen"
	entfile "github.com/pyck-ai/pyck/backend/file/ent/gen/file"
	"github.com/pyck-ai/pyck/backend/file/exec"
	"github.com/pyck-ai/pyck/backend/file/model"
)

// FindCustomerByIDAndTenantID is the resolver for the findCustomerByIDAndTenantID field.
func (r *entityResolver) FindCustomerByIDAndTenantID(ctx context.Context, id uuid.UUID, tenantID uuid.UUID) (*model.Customer, error) {
	files, err := r.ownerFiles(ctx, id, tenantID)
	if err != nil {
		return nil, err
	}
	return &model.Customer{
		ID:       id,
		TenantID: tenantID,
		File:     files,
	}, nil
}

// FindFileByID is the resolver for the findFileByID field.
func (r *entityResolver) FindFileByID(ctx context.Context, id uuid.UUID) (*gen.File, error) {
	file, err := r.client.File.Query().Where(entfile.ID(id)).First(ctx)
	if err != nil {
		return nil, err
	}

	return file, nil
}

// FindInventoryItemByIDAndTenantID is the resolver for the findInventoryItemByIDAndTenantID field.
func (r *entityResolver) FindInventoryItemByIDAndTenantID(ctx context.Context, id uuid.UUID, tenantID uuid.UUID) (*model.InventoryItem, error) {
	files, err := r.ownerFiles(ctx, id, tenantID)
	if err != nil {
		return nil, err
	}
	return &model.InventoryItem{
		ID:       id,
		TenantID: tenantID,
		File:     files,
	}, nil
}

// FindPickingOrderByIDAndTenantID is the resolver for the findPickingOrderByIDAndTenantID field.
func (r *entityResolver) FindPickingOrderByIDAndTenantID(ctx context.Context, id uuid.UUID, tenantID uuid.UUID) (*model.PickingOrder, error) {
	files, err := r.ownerFiles(ctx, id, tenantID)
	if err != nil {
		return nil, err
	}
	return &model.PickingOrder{
		ID:       id,
		TenantID: tenantID,
		File:     files,
	}, nil
}

// FindRepositoryByIDAndTenantID is the resolver for the findRepositoryByIDAndTenantID field.
func (r *entityResolver) FindRepositoryByIDAndTenantID(ctx context.Context, id uuid.UUID, tenantID uuid.UUID) (*model.Repository, error) {
	files, err := r.ownerFiles(ctx, id, tenantID)
	if err != nil {
		return nil, err
	}
	return &model.Repository{
		ID:       id,
		TenantID: tenantID,
		File:     files,
	}, nil
}

// FindSupplierByIDAndTenantID is the resolver for the findSupplierByIDAndTenantID field.
func (r *entityResolver) FindSupplierByIDAndTenantID(ctx context.Context, id uuid.UUID, tenantID uuid.UUID) (*model.Supplier, error) {
	files, err := r.ownerFiles(ctx, id, tenantID)
	if err != nil {
		return nil, err
	}
	return &model.Supplier{
		ID:       id,
		TenantID: tenantID,
		File:     files,
	}, nil
}

// Entity returns exec.EntityResolver implementation.
func (r *Resolver) Entity() exec.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
