package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqljson"
	"github.com/pyck-ai/pyck/backend/common/std"
	ent "github.com/pyck-ai/pyck/backend/file/ent/gen"
	"github.com/pyck-ai/pyck/backend/file/ent/gen/file"
)

// URL is the resolver for the url field.
func (r *fileResolver) URL(ctx context.Context, obj *ent.File) (*string, error) {
	url, err := r.s3Storage.GetPreSignedURL(obj.TenantID, obj.Refid, obj.Name)
	if err != nil {
		return nil, err
	}
	return &url, nil
}

// PublicURL is the resolver for the publicURL field.
func (r *fileResolver) PublicURL(ctx context.Context, obj *ent.File) (*string, error) {
	if obj.PublicAlias != nil && *obj.PublicAlias != "" && std.IsValidSlug(*obj.PublicAlias) {
		publicURL := fmt.Sprintf("/api/v1/files/%s/%s", obj.TenantID, *obj.PublicAlias)
		return &publicURL, nil
	}
	return nil, nil
}

// Data is the resolver for the Data field.
func (r *fileWhereInputResolver) Data(ctx context.Context, obj *ent.FileWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueEQ(file.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataHasKey is the resolver for the DataHasKey field.
func (r *fileWhereInputResolver) DataHasKey(ctx context.Context, obj *ent.FileWhereInput, data *string) error {
	if obj == nil || data == nil {
		return nil
	}

	if *data != "" {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.HasKey(file.FieldData, sqljson.DotPath(*data)))
		})
	}
	return nil
}

// DataIn is the resolver for the DataIn field.
func (r *fileWhereInputResolver) DataIn(ctx context.Context, obj *ent.FileWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) >= 2 {
		var args []any
		for _, v := range data[1:] {
			args = append(args, v)
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueIn(file.FieldData, args, sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataContains is the resolver for the DataContains field.
func (r *fileWhereInputResolver) DataContains(ctx context.Context, obj *ent.FileWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueContains(file.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}
