package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/common/ent/mixin"
	"github.com/pyck-ai/pyck/backend/common/gqltx"
	"github.com/pyck-ai/pyck/backend/common/jsonpatch"
	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/common/validator"
	"github.com/pyck-ai/pyck/backend/file/core"
	ent "github.com/pyck-ai/pyck/backend/file/ent/gen"
	entfile "github.com/pyck-ai/pyck/backend/file/ent/gen/file"
	"github.com/pyck-ai/pyck/backend/file/exec"
	"github.com/pyck-ai/pyck/backend/file/model"
	"github.com/pyck-ai/pyck/backend/file/workflows"
	imageanalyzer "github.com/pyck-ai/pyck/backend/file/workflows/image-analyzer"
)

// CreateFile is the resolver for the createFile field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateFile(ctx context.Context, input ent.CreateFileInput) (*model.CreateFileResult, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entfile.Table,
		FieldName: entfile.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	file, err := tx.File.Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	preSignedUploadURL, err := r.s3Storage.GetPreSignedUploadURL(file.TenantID, file.Name, file.Refid, file.ContentType)
	if err != nil {
		return nil, err
	}

	return &model.CreateFileResult{
		ID:                 file.ID,
		PreSignedUploadURL: &preSignedUploadURL,
		File:               file,
	}, nil
}

// UpdateFile is the resolver for the updateFile field.
// MutationEventHook captures the mutation automatically with field-level events.
func (r *mutationResolver) UpdateFile(ctx context.Context, id uuid.UUID, input ent.UpdateFileInput) (*ent.File, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entfile.Table,
		FieldName: entfile.FieldData,
		DbDriver:  core.Config.DbDriver,
		ExcludeID: &id,
	}); err != nil {
		return nil, err
	}

	file, err := tx.File.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return file, nil
}

// DeleteFile is the resolver for the deleteFile field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteFile(ctx context.Context, id uuid.UUID) (*model.FileDeletePayload, error) {
	req := request.ForContext(ctx)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	file, err := tx.File.UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.s3Storage.DeleteFile(file.TenantID, file.Refid, file.Name); err != nil {
		return nil, err
	}

	return &model.FileDeletePayload{DeletedID: &id}, nil
}

// FinalizeFileUpload is the resolver for the finalizeFileUpload field.
// Reads the actual object size from S3 and persists it on the File record.
// If the stored size already matches the object size, returns the file as-is
// to avoid emitting a redundant mutation event.
func (r *mutationResolver) FinalizeFileUpload(ctx context.Context, id uuid.UUID) (*ent.File, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	f, err := tx.File.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	info, err := r.s3Storage.StatObject(f.TenantID, f.Refid, f.Name)
	if err != nil {
		return nil, err
	}

	if f.Size != nil && *f.Size == info.Size {
		return f, nil
	}

	return tx.File.UpdateOneID(id).SetSize(info.Size).Save(ctx)
}

// AnalyzeImageFile is the resolver for the analyzeImageFile field.
func (r *mutationResolver) AnalyzeImageFile(ctx context.Context, id uuid.UUID) (*model.ImageAnalysisResponse, error) {
	file, err := r.client.File.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	if !strings.Contains(file.ContentType, "image") {
		return nil, errors.New("file is not an image")
	}

	imageUrl, err := r.File().URL(ctx, file)
	if err != nil || imageUrl == nil {
		return nil, fmt.Errorf("failed to get image URL")
	}

	dataType, err := r.validator.ReadBySlug(ctx, file.DataTypeSlug)
	if err != nil {
		return nil, fmt.Errorf("failed to read data type: %w", err)
	}

	workflowInput := imageanalyzer.ImageAnalyzerWorkflowInput{
		OpenAIToken: core.Config.OpenAiToken,
		ImageURL:    *imageUrl,
		JsonSchema:  dataType.JsonSchema,
	}

	workflowID, runID, err := r.workflowClient.StartWorkflow(
		ctx, workflows.AnalyzeImageWorkflow, workflows.TemporalFileTaskQueue, workflowInput, nil,
	)
	if err != nil {
		return nil, err
	}

	var analysisResponse imageanalyzer.ImageAnalyzerWorkflowOutput
	err = r.workflowClient.GetWorkflowResult(ctx, workflowID, runID, &analysisResponse)
	if err != nil {
		return nil, err
	}
	return &model.ImageAnalysisResponse{JSONData: analysisResponse.JsonData}, nil
}

// PatchFileData applies RFC 6902 JSON Patch operations to the file's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchFileData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*ent.File, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.File.Query().Where(entfile.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    entfile.Table,
		FieldName:    entfile.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	return tx.File.UpdateOneID(id).SetData(patched).Save(ctx)
}

// Mutation returns exec.MutationResolver implementation.
func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
