package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/pyck-ai/pyck/backend/common/env"
	"github.com/pyck-ai/pyck/backend/file/model"
)

// FileServiceInfo is the resolver for the fileServiceInfo field.
func (r *queryResolver) FileServiceInfo(ctx context.Context) (*model.ServiceInfo, error) {
	bi := env.GetBuildInfo()

	return &model.ServiceInfo{
		Version: bi.GitCommitSHA(),
		Date:    bi.GitCommitDate(),
	}, nil
}
