// Code generated by importgen; DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/pyck-ai/pyck/backend/common/importexport"
	"github.com/pyck-ai/pyck/backend/receiving/model"
)

// RegisterEntities registers all importable receiving service entities
// with the given registry.
func RegisterEntities(r *importexport.Registry, c Client) error {
	for _, fn := range []func(*importexport.Registry, Client) error{
		registerReceivingInbound,
		registerReceivingInboundItem,
	} {
		if err := fn(r, c); err != nil {
			return err
		}
	}
	return nil
}

func registerReceivingInbound(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "ReceivingInbound",
		Service:       "receiving",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *ReceivingInboundWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[ReceivingInboundWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetReceivingInbounds(ctx, GetReceivingInboundsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetReceivingInbounds()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[model.CreateReceivingInboundWithItemsInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateReceivingInbound(ctx, CreateReceivingInboundArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateReceivingInbound().GetReceivingInbound())
		},
	})
}

func registerReceivingInboundItem(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "ReceivingInboundItem",
		Service:       "receiving",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *ReceivingInboundItemWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[ReceivingInboundItemWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetReceivingInboundItems(ctx, GetReceivingInboundItemsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetReceivingInboundItems()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateReceivingInboundItemInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateReceivingInboundItem(ctx, CreateReceivingInboundItemArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateReceivingInboundItem().GetReceivingInboundItem())
		},
	})
}
