// Code generated by importgen; DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/pyck-ai/pyck/backend/common/importexport"
)

// RegisterEntities registers all importable main-data service entities
// with the given registry.
func RegisterEntities(r *importexport.Registry, c Client) error {
	for _, fn := range []func(*importexport.Registry, Client) error{
		registerCustomer,
		registerSupplier,
	} {
		if err := fn(r, c); err != nil {
			return err
		}
	}
	return nil
}

func registerCustomer(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "Customer",
		Service:       "main-data",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *CustomerWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[CustomerWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetCustomers(ctx, GetCustomersArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetCustomers()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateCustomerInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateCustomer(ctx, CreateCustomerArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateCustomer())
		},
	})
}

func registerSupplier(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "Supplier",
		Service:       "main-data",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *SupplierWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[SupplierWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetSuppliers(ctx, GetSuppliersArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetSuppliers()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateSupplierInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateSupplier(ctx, CreateSupplierArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateSupplier())
		},
	})
}
