// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/file/ent/gen"
)

type CreateFileResult struct {
	ID                 uuid.UUID `json:"id"`
	PreSignedUploadURL *string   `json:"preSignedUploadUrl,omitempty"`
	File               *gen.File `json:"file,omitempty"`
}

type Customer struct {
	ID   uuid.UUID   `json:"id"`
	File []*gen.File `json:"file,omitempty"`
}

func (Customer) IsEntity() {}

type FileDeletePayload struct {
	DeletedID *uuid.UUID `json:"deletedID,omitempty"`
}

type GetPreSignedUploadURLPayload struct {
	URL *string `json:"url,omitempty"`
}

type ImageAnalysisResponse struct {
	JSONData string `json:"jsonData"`
}

type InventoryItem struct {
	ID   uuid.UUID   `json:"id"`
	File []*gen.File `json:"file,omitempty"`
}

func (InventoryItem) IsEntity() {}

type PickingOrder struct {
	ID   uuid.UUID   `json:"id"`
	File []*gen.File `json:"file,omitempty"`
}

func (PickingOrder) IsEntity() {}

type Repository struct {
	ID   uuid.UUID   `json:"id"`
	File []*gen.File `json:"file,omitempty"`
}

func (Repository) IsEntity() {}

type ServiceInfo struct {
	Version string     `json:"version"`
	Date    *time.Time `json:"date,omitempty"`
}

type Supplier struct {
	ID   uuid.UUID   `json:"id"`
	File []*gen.File `json:"file,omitempty"`
}

func (Supplier) IsEntity() {}
