// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package internal

import (
	"context"
	"time"

	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/file/ent/gen/file"
)

type APIClient interface {
	GetFiles(ctx context.Context, after *string, first *int, before *string, last *int, orderBy *FileOrder, where *FileWhereInput, interceptors ...clientv2.RequestInterceptor) (*GetFiles, error)
	GetFileServiceInfo(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetFileServiceInfo, error)
	CreateFile(ctx context.Context, input CreateFileInput, interceptors ...clientv2.RequestInterceptor) (*CreateFile, error)
	UpdateFile(ctx context.Context, id string, input UpdateFileInput, interceptors ...clientv2.RequestInterceptor) (*UpdateFile, error)
	DeleteFile(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*DeleteFile, error)
	FinalizeFileUpload(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*FinalizeFileUpload, error)
	AnalyzeImageFile(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*AnalyzeImageFile, error)
	PatchFileData(ctx context.Context, id string, patches []*JSONPatchInput, interceptors ...clientv2.RequestInterceptor) (*PatchFileData, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) APIClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetFiles_Files_PageInfo struct {
	EndCursor       *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage     bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
	HasPreviousPage bool    "json:\"hasPreviousPage\" graphql:\"hasPreviousPage\""
	StartCursor     *string "json:\"startCursor,omitempty\" graphql:\"startCursor\""
}

func (t *GetFiles_Files_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &GetFiles_Files_PageInfo{}
	}
	return t.EndCursor
}
func (t *GetFiles_Files_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &GetFiles_Files_PageInfo{}
	}
	return t.HasNextPage
}
func (t *GetFiles_Files_PageInfo) GetHasPreviousPage() bool {
	if t == nil {
		t = &GetFiles_Files_PageInfo{}
	}
	return t.HasPreviousPage
}
func (t *GetFiles_Files_PageInfo) GetStartCursor() *string {
	if t == nil {
		t = &GetFiles_Files_PageInfo{}
	}
	return t.StartCursor
}

type GetFiles_Files_Edges_Node struct {
	ContentType  string         "json:\"contentType\" graphql:\"contentType\""
	CreatedAt    time.Time      "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy    uuid.UUID      "json:\"createdBy\" graphql:\"createdBy\""
	Data         map[string]any "json:\"data,omitempty\" graphql:\"data\""
	DataTypeID   *uuid.UUID     "json:\"dataTypeID,omitempty\" graphql:\"dataTypeID\""
	DataTypeSlug *string        "json:\"dataTypeSlug,omitempty\" graphql:\"dataTypeSlug\""
	DeletedAt    *time.Time     "json:\"deletedAt,omitempty\" graphql:\"deletedAt\""
	DeletedBy    *uuid.UUID     "json:\"deletedBy,omitempty\" graphql:\"deletedBy\""
	Description  *string        "json:\"description,omitempty\" graphql:\"description\""
	ID           string         "json:\"id\" graphql:\"id\""
	Name         string         "json:\"name\" graphql:\"name\""
	PublicAlias  *string        "json:\"publicAlias,omitempty\" graphql:\"publicAlias\""
	PublicURL    *string        "json:\"publicURL,omitempty\" graphql:\"publicURL\""
	Refid        uuid.UUID      "json:\"refid\" graphql:\"refid\""
	Reftype      file.Reftype   "json:\"reftype\" graphql:\"reftype\""
	Size         *int           "json:\"size,omitempty\" graphql:\"size\""
	TenantID     uuid.UUID      "json:\"tenantID\" graphql:\"tenantID\""
	UpdatedAt    *time.Time     "json:\"updatedAt,omitempty\" graphql:\"updatedAt\""
	UpdatedBy    *uuid.UUID     "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
	URL          *string        "json:\"url,omitempty\" graphql:\"url\""
}

func (t *GetFiles_Files_Edges_Node) GetContentType() string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.ContentType
}
func (t *GetFiles_Files_Edges_Node) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return &t.CreatedAt
}
func (t *GetFiles_Files_Edges_Node) GetCreatedBy() *uuid.UUID {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return &t.CreatedBy
}
func (t *GetFiles_Files_Edges_Node) GetData() map[string]any {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.Data
}
func (t *GetFiles_Files_Edges_Node) GetDataTypeID() *uuid.UUID {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.DataTypeID
}
func (t *GetFiles_Files_Edges_Node) GetDataTypeSlug() *string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.DataTypeSlug
}
func (t *GetFiles_Files_Edges_Node) GetDeletedAt() *time.Time {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.DeletedAt
}
func (t *GetFiles_Files_Edges_Node) GetDeletedBy() *uuid.UUID {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.DeletedBy
}
func (t *GetFiles_Files_Edges_Node) GetDescription() *string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.Description
}
func (t *GetFiles_Files_Edges_Node) GetID() string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.ID
}
func (t *GetFiles_Files_Edges_Node) GetName() string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.Name
}
func (t *GetFiles_Files_Edges_Node) GetPublicAlias() *string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.PublicAlias
}
func (t *GetFiles_Files_Edges_Node) GetPublicURL() *string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.PublicURL
}
func (t *GetFiles_Files_Edges_Node) GetRefid() *uuid.UUID {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return &t.Refid
}
func (t *GetFiles_Files_Edges_Node) GetReftype() *file.Reftype {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return &t.Reftype
}
func (t *GetFiles_Files_Edges_Node) GetSize() *int {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.Size
}
func (t *GetFiles_Files_Edges_Node) GetTenantID() *uuid.UUID {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return &t.TenantID
}
func (t *GetFiles_Files_Edges_Node) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.UpdatedAt
}
func (t *GetFiles_Files_Edges_Node) GetUpdatedBy() *uuid.UUID {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.UpdatedBy
}
func (t *GetFiles_Files_Edges_Node) GetURL() *string {
	if t == nil {
		t = &GetFiles_Files_Edges_Node{}
	}
	return t.URL
}

type GetFiles_Files_Edges struct {
	Cursor string                     "json:\"cursor\" graphql:\"cursor\""
	Node   *GetFiles_Files_Edges_Node "json:\"node,omitempty\" graphql:\"node\""
}

func (t *GetFiles_Files_Edges) GetCursor() string {
	if t == nil {
		t = &GetFiles_Files_Edges{}
	}
	return t.Cursor
}
func (t *GetFiles_Files_Edges) GetNode() *GetFiles_Files_Edges_Node {
	if t == nil {
		t = &GetFiles_Files_Edges{}
	}
	return t.Node
}

type GetFiles_Files struct {
	Edges      []*GetFiles_Files_Edges "json:\"edges,omitempty\" graphql:\"edges\""
	PageInfo   GetFiles_Files_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
	TotalCount int                     "json:\"totalCount\" graphql:\"totalCount\""
}

func (t *GetFiles_Files) GetEdges() []*GetFiles_Files_Edges {
	if t == nil {
		t = &GetFiles_Files{}
	}
	return t.Edges
}
func (t *GetFiles_Files) GetPageInfo() *GetFiles_Files_PageInfo {
	if t == nil {
		t = &GetFiles_Files{}
	}
	return &t.PageInfo
}
func (t *GetFiles_Files) GetTotalCount() int {
	if t == nil {
		t = &GetFiles_Files{}
	}
	return t.TotalCount
}

type GetFileServiceInfo_FileServiceInfo struct {
	Date    *time.Time "json:\"date,omitempty\" graphql:\"date\""
	Version string     "json:\"version\" graphql:\"version\""
}

func (t *GetFileServiceInfo_FileServiceInfo) GetDate() *time.Time {
	if t == nil {
		t = &GetFileServiceInfo_FileServiceInfo{}
	}
	return t.Date
}
func (t *GetFileServiceInfo_FileServiceInfo) GetVersion() string {
	if t == nil {
		t = &GetFileServiceInfo_FileServiceInfo{}
	}
	return t.Version
}

type CreateFile_CreateFile_File struct {
	ContentType  string         "json:\"contentType\" graphql:\"contentType\""
	CreatedAt    time.Time      "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy    uuid.UUID      "json:\"createdBy\" graphql:\"createdBy\""
	Data         map[string]any "json:\"data,omitempty\" graphql:\"data\""
	DataTypeID   *uuid.UUID     "json:\"dataTypeID,omitempty\" graphql:\"dataTypeID\""
	DataTypeSlug *string        "json:\"dataTypeSlug,omitempty\" graphql:\"dataTypeSlug\""
	DeletedAt    *time.Time     "json:\"deletedAt,omitempty\" graphql:\"deletedAt\""
	DeletedBy    *uuid.UUID     "json:\"deletedBy,omitempty\" graphql:\"deletedBy\""
	Description  *string        "json:\"description,omitempty\" graphql:\"description\""
	ID           string         "json:\"id\" graphql:\"id\""
	Name         string         "json:\"name\" graphql:\"name\""
	PublicAlias  *string        "json:\"publicAlias,omitempty\" graphql:\"publicAlias\""
	PublicURL    *string        "json:\"publicURL,omitempty\" graphql:\"publicURL\""
	Refid        uuid.UUID      "json:\"refid\" graphql:\"refid\""
	Reftype      file.Reftype   "json:\"reftype\" graphql:\"reftype\""
	Size         *int           "json:\"size,omitempty\" graphql:\"size\""
	TenantID     uuid.UUID      "json:\"tenantID\" graphql:\"tenantID\""
	UpdatedAt    *time.Time     "json:\"updatedAt,omitempty\" graphql:\"updatedAt\""
	UpdatedBy    *uuid.UUID     "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
	URL          *string        "json:\"url,omitempty\" graphql:\"url\""
}

func (t *CreateFile_CreateFile_File) GetContentType() string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.ContentType
}
func (t *CreateFile_CreateFile_File) GetCreatedAt() *time.Time {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return &t.CreatedAt
}
func (t *CreateFile_CreateFile_File) GetCreatedBy() *uuid.UUID {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return &t.CreatedBy
}
func (t *CreateFile_CreateFile_File) GetData() map[string]any {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.Data
}
func (t *CreateFile_CreateFile_File) GetDataTypeID() *uuid.UUID {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.DataTypeID
}
func (t *CreateFile_CreateFile_File) GetDataTypeSlug() *string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.DataTypeSlug
}
func (t *CreateFile_CreateFile_File) GetDeletedAt() *time.Time {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.DeletedAt
}
func (t *CreateFile_CreateFile_File) GetDeletedBy() *uuid.UUID {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.DeletedBy
}
func (t *CreateFile_CreateFile_File) GetDescription() *string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.Description
}
func (t *CreateFile_CreateFile_File) GetID() string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.ID
}
func (t *CreateFile_CreateFile_File) GetName() string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.Name
}
func (t *CreateFile_CreateFile_File) GetPublicAlias() *string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.PublicAlias
}
func (t *CreateFile_CreateFile_File) GetPublicURL() *string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.PublicURL
}
func (t *CreateFile_CreateFile_File) GetRefid() *uuid.UUID {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return &t.Refid
}
func (t *CreateFile_CreateFile_File) GetReftype() *file.Reftype {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return &t.Reftype
}
func (t *CreateFile_CreateFile_File) GetSize() *int {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.Size
}
func (t *CreateFile_CreateFile_File) GetTenantID() *uuid.UUID {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return &t.TenantID
}
func (t *CreateFile_CreateFile_File) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.UpdatedAt
}
func (t *CreateFile_CreateFile_File) GetUpdatedBy() *uuid.UUID {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.UpdatedBy
}
func (t *CreateFile_CreateFile_File) GetURL() *string {
	if t == nil {
		t = &CreateFile_CreateFile_File{}
	}
	return t.URL
}

type CreateFile_CreateFile struct {
	File               *CreateFile_CreateFile_File "json:\"file,omitempty\" graphql:\"file\""
	ID                 string                      "json:\"id\" graphql:\"id\""
	PreSignedUploadURL *string                     "json:\"preSignedUploadUrl,omitempty\" graphql:\"preSignedUploadUrl\""
}

func (t *CreateFile_CreateFile) GetFile() *CreateFile_CreateFile_File {
	if t == nil {
		t = &CreateFile_CreateFile{}
	}
	return t.File
}
func (t *CreateFile_CreateFile) GetID() string {
	if t == nil {
		t = &CreateFile_CreateFile{}
	}
	return t.ID
}
func (t *CreateFile_CreateFile) GetPreSignedUploadURL() *string {
	if t == nil {
		t = &CreateFile_CreateFile{}
	}
	return t.PreSignedUploadURL
}

type UpdateFile_UpdateFile struct {
	ContentType  string         "json:\"contentType\" graphql:\"contentType\""
	CreatedAt    time.Time      "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy    uuid.UUID      "json:\"createdBy\" graphql:\"createdBy\""
	Data         map[string]any "json:\"data,omitempty\" graphql:\"data\""
	DataTypeID   *uuid.UUID     "json:\"dataTypeID,omitempty\" graphql:\"dataTypeID\""
	DataTypeSlug *string        "json:\"dataTypeSlug,omitempty\" graphql:\"dataTypeSlug\""
	DeletedAt    *time.Time     "json:\"deletedAt,omitempty\" graphql:\"deletedAt\""
	DeletedBy    *uuid.UUID     "json:\"deletedBy,omitempty\" graphql:\"deletedBy\""
	Description  *string        "json:\"description,omitempty\" graphql:\"description\""
	ID           string         "json:\"id\" graphql:\"id\""
	Name         string         "json:\"name\" graphql:\"name\""
	PublicAlias  *string        "json:\"publicAlias,omitempty\" graphql:\"publicAlias\""
	PublicURL    *string        "json:\"publicURL,omitempty\" graphql:\"publicURL\""
	Refid        uuid.UUID      "json:\"refid\" graphql:\"refid\""
	Reftype      file.Reftype   "json:\"reftype\" graphql:\"reftype\""
	Size         *int           "json:\"size,omitempty\" graphql:\"size\""
	TenantID     uuid.UUID      "json:\"tenantID\" graphql:\"tenantID\""
	UpdatedAt    *time.Time     "json:\"updatedAt,omitempty\" graphql:\"updatedAt\""
	UpdatedBy    *uuid.UUID     "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
	URL          *string        "json:\"url,omitempty\" graphql:\"url\""
}

func (t *UpdateFile_UpdateFile) GetContentType() string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.ContentType
}
func (t *UpdateFile_UpdateFile) GetCreatedAt() *time.Time {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return &t.CreatedAt
}
func (t *UpdateFile_UpdateFile) GetCreatedBy() *uuid.UUID {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return &t.CreatedBy
}
func (t *UpdateFile_UpdateFile) GetData() map[string]any {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.Data
}
func (t *UpdateFile_UpdateFile) GetDataTypeID() *uuid.UUID {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.DataTypeID
}
func (t *UpdateFile_UpdateFile) GetDataTypeSlug() *string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.DataTypeSlug
}
func (t *UpdateFile_UpdateFile) GetDeletedAt() *time.Time {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.DeletedAt
}
func (t *UpdateFile_UpdateFile) GetDeletedBy() *uuid.UUID {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.DeletedBy
}
func (t *UpdateFile_UpdateFile) GetDescription() *string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.Description
}
func (t *UpdateFile_UpdateFile) GetID() string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.ID
}
func (t *UpdateFile_UpdateFile) GetName() string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.Name
}
func (t *UpdateFile_UpdateFile) GetPublicAlias() *string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.PublicAlias
}
func (t *UpdateFile_UpdateFile) GetPublicURL() *string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.PublicURL
}
func (t *UpdateFile_UpdateFile) GetRefid() *uuid.UUID {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return &t.Refid
}
func (t *UpdateFile_UpdateFile) GetReftype() *file.Reftype {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return &t.Reftype
}
func (t *UpdateFile_UpdateFile) GetSize() *int {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.Size
}
func (t *UpdateFile_UpdateFile) GetTenantID() *uuid.UUID {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return &t.TenantID
}
func (t *UpdateFile_UpdateFile) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.UpdatedAt
}
func (t *UpdateFile_UpdateFile) GetUpdatedBy() *uuid.UUID {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.UpdatedBy
}
func (t *UpdateFile_UpdateFile) GetURL() *string {
	if t == nil {
		t = &UpdateFile_UpdateFile{}
	}
	return t.URL
}

type DeleteFile_DeleteFile struct {
	DeletedID *string "json:\"deletedID,omitempty\" graphql:\"deletedID\""
}

func (t *DeleteFile_DeleteFile) GetDeletedID() *string {
	if t == nil {
		t = &DeleteFile_DeleteFile{}
	}
	return t.DeletedID
}

type FinalizeFileUpload_FinalizeFileUpload struct {
	ContentType  string         "json:\"contentType\" graphql:\"contentType\""
	CreatedAt    time.Time      "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy    uuid.UUID      "json:\"createdBy\" graphql:\"createdBy\""
	Data         map[string]any "json:\"data,omitempty\" graphql:\"data\""
	DataTypeID   *uuid.UUID     "json:\"dataTypeID,omitempty\" graphql:\"dataTypeID\""
	DataTypeSlug *string        "json:\"dataTypeSlug,omitempty\" graphql:\"dataTypeSlug\""
	DeletedAt    *time.Time     "json:\"deletedAt,omitempty\" graphql:\"deletedAt\""
	DeletedBy    *uuid.UUID     "json:\"deletedBy,omitempty\" graphql:\"deletedBy\""
	Description  *string        "json:\"description,omitempty\" graphql:\"description\""
	ID           string         "json:\"id\" graphql:\"id\""
	Name         string         "json:\"name\" graphql:\"name\""
	PublicAlias  *string        "json:\"publicAlias,omitempty\" graphql:\"publicAlias\""
	PublicURL    *string        "json:\"publicURL,omitempty\" graphql:\"publicURL\""
	Refid        uuid.UUID      "json:\"refid\" graphql:\"refid\""
	Reftype      file.Reftype   "json:\"reftype\" graphql:\"reftype\""
	Size         *int           "json:\"size,omitempty\" graphql:\"size\""
	TenantID     uuid.UUID      "json:\"tenantID\" graphql:\"tenantID\""
	UpdatedAt    *time.Time     "json:\"updatedAt,omitempty\" graphql:\"updatedAt\""
	UpdatedBy    *uuid.UUID     "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
	URL          *string        "json:\"url,omitempty\" graphql:\"url\""
}

func (t *FinalizeFileUpload_FinalizeFileUpload) GetContentType() string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.ContentType
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetCreatedAt() *time.Time {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return &t.CreatedAt
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetCreatedBy() *uuid.UUID {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return &t.CreatedBy
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetData() map[string]any {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.Data
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetDataTypeID() *uuid.UUID {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.DataTypeID
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetDataTypeSlug() *string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.DataTypeSlug
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetDeletedAt() *time.Time {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.DeletedAt
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetDeletedBy() *uuid.UUID {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.DeletedBy
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetDescription() *string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.Description
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetID() string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.ID
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetName() string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.Name
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetPublicAlias() *string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.PublicAlias
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetPublicURL() *string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.PublicURL
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetRefid() *uuid.UUID {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return &t.Refid
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetReftype() *file.Reftype {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return &t.Reftype
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetSize() *int {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.Size
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetTenantID() *uuid.UUID {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return &t.TenantID
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.UpdatedAt
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetUpdatedBy() *uuid.UUID {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.UpdatedBy
}
func (t *FinalizeFileUpload_FinalizeFileUpload) GetURL() *string {
	if t == nil {
		t = &FinalizeFileUpload_FinalizeFileUpload{}
	}
	return t.URL
}

type AnalyzeImageFile_AnalyzeImageFile struct {
	JSONData string "json:\"jsonData\" graphql:\"jsonData\""
}

func (t *AnalyzeImageFile_AnalyzeImageFile) GetJSONData() string {
	if t == nil {
		t = &AnalyzeImageFile_AnalyzeImageFile{}
	}
	return t.JSONData
}

type PatchFileData_PatchFileData struct {
	ContentType  string         "json:\"contentType\" graphql:\"contentType\""
	CreatedAt    time.Time      "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy    uuid.UUID      "json:\"createdBy\" graphql:\"createdBy\""
	Data         map[string]any "json:\"data,omitempty\" graphql:\"data\""
	DataTypeID   *uuid.UUID     "json:\"dataTypeID,omitempty\" graphql:\"dataTypeID\""
	DataTypeSlug *string        "json:\"dataTypeSlug,omitempty\" graphql:\"dataTypeSlug\""
	DeletedAt    *time.Time     "json:\"deletedAt,omitempty\" graphql:\"deletedAt\""
	DeletedBy    *uuid.UUID     "json:\"deletedBy,omitempty\" graphql:\"deletedBy\""
	Description  *string        "json:\"description,omitempty\" graphql:\"description\""
	ID           string         "json:\"id\" graphql:\"id\""
	Name         string         "json:\"name\" graphql:\"name\""
	PublicAlias  *string        "json:\"publicAlias,omitempty\" graphql:\"publicAlias\""
	PublicURL    *string        "json:\"publicURL,omitempty\" graphql:\"publicURL\""
	Refid        uuid.UUID      "json:\"refid\" graphql:\"refid\""
	Reftype      file.Reftype   "json:\"reftype\" graphql:\"reftype\""
	Size         *int           "json:\"size,omitempty\" graphql:\"size\""
	TenantID     uuid.UUID      "json:\"tenantID\" graphql:\"tenantID\""
	UpdatedAt    *time.Time     "json:\"updatedAt,omitempty\" graphql:\"updatedAt\""
	UpdatedBy    *uuid.UUID     "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
	URL          *string        "json:\"url,omitempty\" graphql:\"url\""
}

func (t *PatchFileData_PatchFileData) GetContentType() string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.ContentType
}
func (t *PatchFileData_PatchFileData) GetCreatedAt() *time.Time {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return &t.CreatedAt
}
func (t *PatchFileData_PatchFileData) GetCreatedBy() *uuid.UUID {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return &t.CreatedBy
}
func (t *PatchFileData_PatchFileData) GetData() map[string]any {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.Data
}
func (t *PatchFileData_PatchFileData) GetDataTypeID() *uuid.UUID {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.DataTypeID
}
func (t *PatchFileData_PatchFileData) GetDataTypeSlug() *string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.DataTypeSlug
}
func (t *PatchFileData_PatchFileData) GetDeletedAt() *time.Time {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.DeletedAt
}
func (t *PatchFileData_PatchFileData) GetDeletedBy() *uuid.UUID {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.DeletedBy
}
func (t *PatchFileData_PatchFileData) GetDescription() *string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.Description
}
func (t *PatchFileData_PatchFileData) GetID() string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.ID
}
func (t *PatchFileData_PatchFileData) GetName() string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.Name
}
func (t *PatchFileData_PatchFileData) GetPublicAlias() *string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.PublicAlias
}
func (t *PatchFileData_PatchFileData) GetPublicURL() *string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.PublicURL
}
func (t *PatchFileData_PatchFileData) GetRefid() *uuid.UUID {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return &t.Refid
}
func (t *PatchFileData_PatchFileData) GetReftype() *file.Reftype {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return &t.Reftype
}
func (t *PatchFileData_PatchFileData) GetSize() *int {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.Size
}
func (t *PatchFileData_PatchFileData) GetTenantID() *uuid.UUID {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return &t.TenantID
}
func (t *PatchFileData_PatchFileData) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.UpdatedAt
}
func (t *PatchFileData_PatchFileData) GetUpdatedBy() *uuid.UUID {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.UpdatedBy
}
func (t *PatchFileData_PatchFileData) GetURL() *string {
	if t == nil {
		t = &PatchFileData_PatchFileData{}
	}
	return t.URL
}

type GetFiles struct {
	Files GetFiles_Files "json:\"files\" graphql:\"files\""
}

func (t *GetFiles) GetFiles() *GetFiles_Files {
	if t == nil {
		t = &GetFiles{}
	}
	return &t.Files
}

type GetFileServiceInfo struct {
	FileServiceInfo GetFileServiceInfo_FileServiceInfo "json:\"fileServiceInfo\" graphql:\"fileServiceInfo\""
}

func (t *GetFileServiceInfo) GetFileServiceInfo() *GetFileServiceInfo_FileServiceInfo {
	if t == nil {
		t = &GetFileServiceInfo{}
	}
	return &t.FileServiceInfo
}

type CreateFile struct {
	CreateFile *CreateFile_CreateFile "json:\"createFile,omitempty\" graphql:\"createFile\""
}

func (t *CreateFile) GetCreateFile() *CreateFile_CreateFile {
	if t == nil {
		t = &CreateFile{}
	}
	return t.CreateFile
}

type UpdateFile struct {
	UpdateFile *UpdateFile_UpdateFile "json:\"updateFile,omitempty\" graphql:\"updateFile\""
}

func (t *UpdateFile) GetUpdateFile() *UpdateFile_UpdateFile {
	if t == nil {
		t = &UpdateFile{}
	}
	return t.UpdateFile
}

type DeleteFile struct {
	DeleteFile DeleteFile_DeleteFile "json:\"deleteFile\" graphql:\"deleteFile\""
}

func (t *DeleteFile) GetDeleteFile() *DeleteFile_DeleteFile {
	if t == nil {
		t = &DeleteFile{}
	}
	return &t.DeleteFile
}

type FinalizeFileUpload struct {
	FinalizeFileUpload FinalizeFileUpload_FinalizeFileUpload "json:\"finalizeFileUpload\" graphql:\"finalizeFileUpload\""
}

func (t *FinalizeFileUpload) GetFinalizeFileUpload() *FinalizeFileUpload_FinalizeFileUpload {
	if t == nil {
		t = &FinalizeFileUpload{}
	}
	return &t.FinalizeFileUpload
}

type AnalyzeImageFile struct {
	AnalyzeImageFile AnalyzeImageFile_AnalyzeImageFile "json:\"analyzeImageFile\" graphql:\"analyzeImageFile\""
}

func (t *AnalyzeImageFile) GetAnalyzeImageFile() *AnalyzeImageFile_AnalyzeImageFile {
	if t == nil {
		t = &AnalyzeImageFile{}
	}
	return &t.AnalyzeImageFile
}

type PatchFileData struct {
	PatchFileData *PatchFileData_PatchFileData "json:\"patchFileData,omitempty\" graphql:\"patchFileData\""
}

func (t *PatchFileData) GetPatchFileData() *PatchFileData_PatchFileData {
	if t == nil {
		t = &PatchFileData{}
	}
	return t.PatchFileData
}

const GetFilesDocument = `query GetFiles ($after: Cursor, $first: Int, $before: Cursor, $last: Int, $orderBy: FileOrder, $where: FileWhereInput) {
	files(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {
		totalCount
		pageInfo {
			hasNextPage
			hasPreviousPage
			startCursor
			endCursor
		}
		edges {
			cursor
			node {
				contentType
				createdAt
				createdBy
				data
				dataTypeID
				dataTypeSlug
				deletedAt
				deletedBy
				description
				id
				name
				publicAlias
				publicURL
				refid
				reftype
				size
				tenantID
				updatedAt
				updatedBy
				url
			}
		}
	}
}
`

func (c *Client) GetFiles(ctx context.Context, after *string, first *int, before *string, last *int, orderBy *FileOrder, where *FileWhereInput, interceptors ...clientv2.RequestInterceptor) (*GetFiles, error) {
	vars := map[string]any{
		"after":   after,
		"first":   first,
		"before":  before,
		"last":    last,
		"orderBy": orderBy,
		"where":   where,
	}

	var res GetFiles
	if err := c.Client.Post(ctx, "GetFiles", GetFilesDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetFileServiceInfoDocument = `query GetFileServiceInfo {
	fileServiceInfo {
		date
		version
	}
}
`

func (c *Client) GetFileServiceInfo(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetFileServiceInfo, error) {
	vars := map[string]any{}

	var res GetFileServiceInfo
	if err := c.Client.Post(ctx, "GetFileServiceInfo", GetFileServiceInfoDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreateFileDocument = `mutation CreateFile ($input: CreateFileInput!) {
	createFile(input: $input) {
		file {
			contentType
			createdAt
			createdBy
			data
			dataTypeID
			dataTypeSlug
			deletedAt
			deletedBy
			description
			id
			name
			publicAlias
			publicURL
			refid
			reftype
			size
			tenantID
			updatedAt
			updatedBy
			url
		}
		id
		preSignedUploadUrl
	}
}
`

func (c *Client) CreateFile(ctx context.Context, input CreateFileInput, interceptors ...clientv2.RequestInterceptor) (*CreateFile, error) {
	vars := map[string]any{
		"input": input,
	}

	var res CreateFile
	if err := c.Client.Post(ctx, "CreateFile", CreateFileDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const UpdateFileDocument = `mutation UpdateFile ($id: ID!, $input: UpdateFileInput!) {
	updateFile(id: $id, input: $input) {
		contentType
		createdAt
		createdBy
		data
		dataTypeID
		dataTypeSlug
		deletedAt
		deletedBy
		description
		id
		name
		publicAlias
		publicURL
		refid
		reftype
		size
		tenantID
		updatedAt
		updatedBy
		url
	}
}
`

func (c *Client) UpdateFile(ctx context.Context, id string, input UpdateFileInput, interceptors ...clientv2.RequestInterceptor) (*UpdateFile, error) {
	vars := map[string]any{
		"id":    id,
		"input": input,
	}

	var res UpdateFile
	if err := c.Client.Post(ctx, "UpdateFile", UpdateFileDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const DeleteFileDocument = `mutation DeleteFile ($id: ID!) {
	deleteFile(id: $id) {
		deletedID
	}
}
`

func (c *Client) DeleteFile(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*DeleteFile, error) {
	vars := map[string]any{
		"id": id,
	}

	var res DeleteFile
	if err := c.Client.Post(ctx, "DeleteFile", DeleteFileDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const FinalizeFileUploadDocument = `mutation FinalizeFileUpload ($id: ID!) {
	finalizeFileUpload(id: $id) {
		contentType
		createdAt
		createdBy
		data
		dataTypeID
		dataTypeSlug
		deletedAt
		deletedBy
		description
		id
		name
		publicAlias
		publicURL
		refid
		reftype
		size
		tenantID
		updatedAt
		updatedBy
		url
	}
}
`

func (c *Client) FinalizeFileUpload(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*FinalizeFileUpload, error) {
	vars := map[string]any{
		"id": id,
	}

	var res FinalizeFileUpload
	if err := c.Client.Post(ctx, "FinalizeFileUpload", FinalizeFileUploadDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const AnalyzeImageFileDocument = `mutation AnalyzeImageFile ($id: ID!) {
	analyzeImageFile(id: $id) {
		jsonData
	}
}
`

func (c *Client) AnalyzeImageFile(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*AnalyzeImageFile, error) {
	vars := map[string]any{
		"id": id,
	}

	var res AnalyzeImageFile
	if err := c.Client.Post(ctx, "AnalyzeImageFile", AnalyzeImageFileDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const PatchFileDataDocument = `mutation PatchFileData ($id: ID!, $patches: [JSONPatchInput!]!) {
	patchFileData(id: $id, patches: $patches) {
		contentType
		createdAt
		createdBy
		data
		dataTypeID
		dataTypeSlug
		deletedAt
		deletedBy
		description
		id
		name
		publicAlias
		publicURL
		refid
		reftype
		size
		tenantID
		updatedAt
		updatedBy
		url
	}
}
`

func (c *Client) PatchFileData(ctx context.Context, id string, patches []*JSONPatchInput, interceptors ...clientv2.RequestInterceptor) (*PatchFileData, error) {
	vars := map[string]any{
		"id":      id,
		"patches": patches,
	}

	var res PatchFileData
	if err := c.Client.Post(ctx, "PatchFileData", PatchFileDataDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetFilesDocument:           "GetFiles",
	GetFileServiceInfoDocument: "GetFileServiceInfo",
	CreateFileDocument:         "CreateFile",
	UpdateFileDocument:         "UpdateFile",
	DeleteFileDocument:         "DeleteFile",
	FinalizeFileUploadDocument: "FinalizeFileUpload",
	AnalyzeImageFileDocument:   "AnalyzeImageFile",
	PatchFileDataDocument:      "PatchFileData",
}
