package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/common/authn"
	"github.com/pyck-ai/pyck/backend/common/ent/mixin"
	"github.com/pyck-ai/pyck/backend/common/feature"
	"github.com/pyck-ai/pyck/backend/common/gqltx"
	"github.com/pyck-ai/pyck/backend/common/jsonpatch"
	"github.com/pyck-ai/pyck/backend/common/log"
	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/common/uuidgql"
	"github.com/pyck-ai/pyck/backend/common/validator"
	"github.com/pyck-ai/pyck/backend/inventory/core"
	ent "github.com/pyck-ai/pyck/backend/inventory/ent/gen"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/collection_movement"
	entitem "github.com/pyck-ai/pyck/backend/inventory/ent/gen/item"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/itemmovement"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/itemset"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/predicate"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/replenishmentorder"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/replenishmentorderitem"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/repository"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/repositorymovement"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/transaction"
	"github.com/pyck-ai/pyck/backend/inventory/exec"
	"github.com/pyck-ai/pyck/backend/inventory/model"
	stocksvc "github.com/pyck-ai/pyck/backend/inventory/service/stock"
)

// CreateInventoryItem is the resolver for the createInventoryItem field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateInventoryItem(ctx context.Context, input ent.CreateInventoryItemInput) (*model.InventoryItemOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryItemOutput

	item, err := tx.Item.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entitem.Table,
		FieldName: entitem.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryItem = item
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// UpdateInventoryItem is the resolver for the updateInventoryItem field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateInventoryItem(ctx context.Context, id uuid.UUID, input ent.UpdateInventoryItemInput) (*model.InventoryItemOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryItemOutput

	item, err := tx.Item.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: entitem.Table,
		FieldName: entitem.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryItem = item
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// DeleteInventoryItem is the resolver for the deleteInventoryItem field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteInventoryItem(ctx context.Context, id uuid.UUID) (*model.InventoryItemDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryItemDeletePayload
	req := request.ForContext(ctx)

	repositoryMap, err := r.stock.GetRepositoriesDetails(ctx, tx)
	if err != nil {
		return nil, err
	}

	var warehouseRepoIDs []uuid.UUID
	for _, v := range repositoryMap {
		if v.ParentID == uuid.Nil && !v.VirtualRepo {
			warehouseRepoIDs = append(warehouseRepoIDs, v.ID)
		}
	}

	if len(warehouseRepoIDs) > 0 {
		stockMap, err := r.stock.GetCurrentRepositoriesStock(ctx, tx, warehouseRepoIDs)
		if err != nil {
			return nil, fmt.Errorf("failed to query stock table: %w", err)
		}

		for _, itemStocks := range stockMap {
			if record, ok := itemStocks[id]; ok {
				if record.Quantity > 0 {
					return nil, fmt.Errorf("unable to remove item as long as it is in stock")
				}
				if record.IncomingStock > 0 {
					return nil, fmt.Errorf("unable to remove item as long as there are expected items in stock")
				}
				if record.OutgoingStock > 0 {
					return nil, fmt.Errorf("unable to remove item as long as there are reserved items in stock")
				}
			}
		}
	}

	_, err = tx.Item.
		UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	resp.DeletedID = &id
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// CreateInventoryRepository is the resolver for the createInventoryRepository field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateInventoryRepository(ctx context.Context, input ent.CreateRepositoryInput) (*model.InventoryRepositoryOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryRepositoryOutput

	inputVirtualRepoFlag := true
	if input.VirtualRepo != nil {
		inputVirtualRepoFlag = *input.VirtualRepo
	}

	if input.ParentID != nil {
		parentRepo, err := tx.Repository.Get(ctx, *input.ParentID)
		if err != nil || parentRepo == nil {
			return nil, errors.New("unable to validate data: ParentID not found")
		}

		if parentRepo.VirtualRepo != inputVirtualRepoFlag {
			return nil, errors.New("the repo child must have the same virtualRepo flag as the parent")
		}

		if inputVirtualRepoFlag && parentRepo.ParentID != uuid.Nil {
			return nil, errors.New("the depth of virtual zones is maximum 1")
		}
	}

	repo, err := tx.Repository.Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: repository.Table,
		FieldName: repository.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryRepository = repo
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// UpdateInventoryRepository is the resolver for the updateInventoryRepository field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateInventoryRepository(ctx context.Context, id uuid.UUID, input ent.UpdateRepositoryInput) (*model.InventoryRepositoryOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryRepositoryOutput

	if input.ParentID != nil {
		response, err := tx.Repository.Get(ctx, *input.ParentID)
		if err != nil || response == nil {
			return nil, errors.New("unable to validate data: ParentID not found")
		}
	}

	repo, err := tx.Repository.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: repository.Table,
		FieldName: repository.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryRepository = repo
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// DeleteInventoryRepository is the resolver for the deleteInventoryRepository field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteInventoryRepository(ctx context.Context, id uuid.UUID) (*model.InventoryRepositoryDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryRepositoryDeletePayload
	req := request.ForContext(ctx)

	stockMap, err := r.stock.GetCurrentRepositoriesStock(ctx, tx, []uuid.UUID{id})
	if err != nil {
		return nil, fmt.Errorf("failed to query stock table: %w", err)
	}

	for _, record := range stockMap[id] {
		if record.Quantity > 0 {
			return nil, fmt.Errorf("unable to remove repository as long as there are items in stock")
		}
		if record.IncomingStock > 0 {
			return nil, fmt.Errorf("unable to remove repository as long as there are expected items in stock")
		}
		if record.OutgoingStock > 0 {
			return nil, fmt.Errorf("unable to remove repository as long as there are reserved items in stock")
		}
	}

	childList, err := tx.Repository.
		Query().
		Where(repository.ParentIDEQ(id)).
		Where(repository.TenantID(req.MutationTenantID())).
		AllPages(ctx, mixin.Limit)
	if err != nil {
		return nil, err
	}

	if len(childList) > 0 {
		return nil, fmt.Errorf("unable to remove repository as long as it has children")
	}

	_, err = tx.Repository.
		UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	resp.DeletedID = &id
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// CreateInventoryItemMovement is the resolver for the createInventoryItemMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateInventoryItemMovement(ctx context.Context, input ent.CreateItemMovementInput) (*model.InventoryItemMovementOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}
	mixin.PatchDataTypeIdSlugInput(&input, dataType)
	if input.CollectionID == nil {
		input.CollectionID = &uuid.UUID{}
	}
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}
	uniqueness := func() error {
		return r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
			Input: input.Data, DataType: dataType, DbDriver: core.Config.DbDriver,
			TableName: itemmovement.Table, FieldName: itemmovement.FieldData,
		})
	}
	movement, err := r.stock.CreateItemMovement(ctx, tx, stocksvc.CreateItemMovementInput{
		Input: input, TenantID: request.ForContext(ctx).MutationTenantID(), ValidateUniquenessHook: uniqueness,
	})
	if err != nil {
		return nil, err
	}
	return &model.InventoryItemMovementOutput{InventoryItemMovement: movement, Workflows: make([]*model.TemporalWorkflow, 0)}, nil
}

// UpdateInventoryItemMovement is the resolver for the updateInventoryItemMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateInventoryItemMovement(ctx context.Context, id uuid.UUID, input ent.UpdateItemMovementInput) (*model.InventoryItemMovementOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryItemMovementOutput

	_, err = tx.ItemMovement.Get(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("itemMovement not found")
	}

	movement, err := tx.ItemMovement.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: itemmovement.Table,
		FieldName: itemmovement.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryItemMovement = movement
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// ExecuteInventoryItemMovement is the resolver for the executeInventoryItemMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) ExecuteInventoryItemMovement(ctx context.Context, id uuid.UUID) (*model.InventoryItemMovementOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}
	itemMovement, err := r.stock.ExecuteItemMovement(ctx, tx, stocksvc.ExecuteItemMovementInput{
		ID: id, TenantID: request.ForContext(ctx).MutationTenantID(),
	})
	if err != nil {
		return nil, err
	}
	return &model.InventoryItemMovementOutput{InventoryItemMovement: itemMovement, Workflows: make([]*model.TemporalWorkflow, 0)}, nil
}

// DeleteInventoryItemMovement is the resolver for the deleteInventoryItemMovement field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteInventoryItemMovement(ctx context.Context, id uuid.UUID) (*model.InventoryItemMovementDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}
	req := request.ForContext(ctx)
	if _, err = r.stock.DeleteItemMovement(ctx, tx, stocksvc.DeleteItemMovementInput{
		ID: id, TenantID: req.MutationTenantID(), DeletedBy: req.User().ID,
	}); err != nil {
		return nil, err
	}
	return &model.InventoryItemMovementDeletePayload{DeletedID: &id, Workflows: make([]*model.TemporalWorkflow, 0)}, nil
}

// CreateInventoryRepositoryMovement is the resolver for the createInventoryRepositoryMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateInventoryRepositoryMovement(ctx context.Context, input ent.CreateRepositoryMovementInput) (*model.InventoryRepositoryMovementOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}
	mixin.PatchDataTypeIdSlugInput(&input, dataType)
	if input.CollectionID == nil {
		input.CollectionID = &uuid.UUID{}
	}
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}
	uniqueness := func() error {
		return r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
			Input: input.Data, DataType: dataType, DbDriver: core.Config.DbDriver,
			TableName: repositorymovement.Table, FieldName: repositorymovement.FieldData,
		})
	}
	movement, err := r.stock.CreateRepositoryMovement(ctx, tx, stocksvc.CreateRepositoryMovementInput{
		Input: input, TenantID: request.ForContext(ctx).MutationTenantID(), ValidateUniquenessHook: uniqueness,
	})
	if err != nil {
		return nil, err
	}
	return &model.InventoryRepositoryMovementOutput{InventoryRepositoryMovement: movement, Workflows: make([]*model.TemporalWorkflow, 0)}, nil
}

// UpdateInventoryRepositoryMovement is the resolver for the updateInventoryRepositoryMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateInventoryRepositoryMovement(ctx context.Context, id uuid.UUID, input ent.UpdateRepositoryMovementInput) (*model.InventoryRepositoryMovementOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryRepositoryMovementOutput

	_, err = tx.RepositoryMovement.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	movement, err := tx.RepositoryMovement.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: repositorymovement.Table,
		FieldName: repositorymovement.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryRepositoryMovement = movement
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// ExecuteInventoryRepositoryMovement is the resolver for the executeInventoryRepositoryMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) ExecuteInventoryRepositoryMovement(ctx context.Context, id uuid.UUID) (*model.InventoryRepositoryMovementOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}
	repositoryMovement, err := r.stock.ExecuteRepositoryMovement(ctx, tx, stocksvc.ExecuteRepositoryMovementInput{
		ID: id, TenantID: request.ForContext(ctx).MutationTenantID(),
	})
	if err != nil {
		return nil, err
	}
	return &model.InventoryRepositoryMovementOutput{InventoryRepositoryMovement: repositoryMovement, Workflows: make([]*model.TemporalWorkflow, 0)}, nil
}

// DeleteInventoryRepositoryMovement is the resolver for the deleteInventoryRepositoryMovement field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteInventoryRepositoryMovement(ctx context.Context, id uuid.UUID) (*model.InventoryRepositoryMovementDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}
	req := request.ForContext(ctx)
	if _, err = r.stock.DeleteRepositoryMovement(ctx, tx, stocksvc.DeleteRepositoryMovementInput{
		ID: id, TenantID: req.MutationTenantID(), DeletedBy: req.User().ID,
	}); err != nil {
		return nil, err
	}
	return &model.InventoryRepositoryMovementDeletePayload{DeletedID: &id, Workflows: make([]*model.TemporalWorkflow, 0)}, nil
}

// CreateInventoryCollectionMovement is the resolver for the createInventoryCollectionMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateInventoryCollectionMovement(ctx context.Context, input model.CreateCollectionMovementInput) (*model.CreateCollectionMovementOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}
	mixin.PatchDataTypeIdSlugInput(&input, dataType)
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Validate per-position data type and patch DataTypeID/DataTypeSlug onto the
	// per-position GraphQL input. Carries the resolver-side validator
	// responsibility; the stock service consumes the already-validated values.
	collection := make([]stocksvc.CreateCollectionMovementCollectionInput, len(input.Collection))
	for i, position := range input.Collection {
		collDataType, err := r.validator.ValidateDataTypeInput(ctx, true, position.Data, position.DataTypeID, position.DataTypeSlug)
		if err != nil {
			return nil, err
		}
		mixin.PatchDataTypeIdSlugInput(position, collDataType)
		collection[i] = stocksvc.CreateCollectionMovementCollectionInput{
			Handler:      position.Handler,
			DataTypeID:   position.DataTypeID,
			DataTypeSlug: position.DataTypeSlug,
			Data:         position.Data,
			FromID:       position.FromID,
			ToID:         position.ToID,
			ItemID:       position.ItemID,
			Quantity:     position.Quantity,
			RepositoryID: position.RepositoryID,
			OrderID:      position.OrderID,
		}
	}

	resolvedDataTypeID := input.DataTypeID
	if dataType != nil {
		resolvedDataTypeID = &dataType.ID
	}
	uniqueness := func() error {
		return r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
			Input: input.Data, DataType: dataType, DbDriver: core.Config.DbDriver,
			TableName: collection_movement.Table, FieldName: collection_movement.FieldData,
		})
	}
	out, err := r.stock.CreateCollectionMovement(ctx, tx, stocksvc.CreateCollectionMovementInput{
		ID: uuidgql.GenerateV7UUID(), DataTypeID: resolvedDataTypeID, DataTypeSlug: input.DataTypeSlug,
		Data: input.Data, Handler: input.Handler, Collection: collection,
		TenantID: request.ForContext(ctx).MutationTenantID(), PreInsertStockHook: uniqueness,
	})
	if err != nil {
		return nil, err
	}
	movements := make([]*model.CollectionMovement, len(out.Movements))
	for i, m := range out.Movements {
		movements[i] = &model.CollectionMovement{ID: m.ID, MovementType: m.MovementType}
	}
	return &model.CreateCollectionMovementOutput{ID: out.ID, Movements: movements}, nil
}

// UpdateInventoryCollectionMovement is the resolver for the updateInventoryCollectionMovement field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateInventoryCollectionMovement(ctx context.Context, id uuid.UUID, input ent.UpdateInventoryCollectionInput) (*model.UpdateCollectionMovementOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	resp := model.UpdateCollectionMovementOutput{}

	if input.Handler != nil && *input.Handler == "" {
		input.Handler = nil
	}

	collectionMovement, err := tx.Collection_Movement.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: collection_movement.Table,
		FieldName: collection_movement.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryCollection = collectionMovement
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// DeleteInventoryCollection is the resolver for the deleteInventoryCollection field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteInventoryCollection(ctx context.Context, id uuid.UUID) (*model.InventoryCollectionDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}
	req := request.ForContext(ctx)
	if _, err = r.stock.DeleteCollection(ctx, tx, stocksvc.DeleteCollectionInput{
		ID: id, DeletedBy: req.User().ID,
	}); err != nil {
		return nil, err
	}
	return &model.InventoryCollectionDeletePayload{DeletedID: &id, Workflows: make([]*model.TemporalWorkflow, 0)}, nil
}

// DeleteInventoryStock is the resolver for the deleteInventoryStock field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) DeleteInventoryStock(ctx context.Context, input model.ClearVirtualStockInput) (*model.RepositoryDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	req := request.ForContext(ctx)

	repo, err := tx.Repository.Get(ctx, input.RepositoryID)
	if err != nil {
		return nil, err
	}

	if !repo.VirtualRepo {
		return nil, errors.New("items can only be deleted from virtual repositories")
	}

	where := predicate.Repository(func(s *sql.Selector) {
		s.Where(sql.EQ(repository.FieldParentID, repo.ID))
	})

	childReposIDList, err := tx.Repository.Query().Where(where).AllPages(ctx, mixin.Limit)
	if err != nil {
		return nil, err
	}

	repositoryIDList := make([]uuid.UUID, 0, len(childReposIDList)+2)
	for _, v := range childReposIDList {
		repositoryIDList = append(repositoryIDList, v.ID)
	}

	repositoryIDList = append(repositoryIDList, repo.ID)
	if repo.ParentID != uuid.Nil {
		repositoryIDList = append(repositoryIDList, repo.ParentID)
	}

	stockMap := map[uuid.UUID]map[uuid.UUID]ent.Stock{}
	if len(repositoryIDList) > 0 {
		stockMap, err = r.stock.GetCurrentRepositoriesStock(ctx, tx, repositoryIDList)
		if err != nil {
			return nil, err
		}
	}

	itemsToDelete := make([]uuid.UUID, 0)
	if input.ItemID != nil {
		itemsToDelete = append(itemsToDelete, *input.ItemID)
	} else {
		for _, v := range stockMap[repo.ID] {
			itemsToDelete = append(itemsToDelete, v.ItemID)
		}
	}

	stocksToCreate := []*ent.StockCreate{}
	transactionsToCreate := []*ent.TransactionCreate{}
	for _, v := range itemsToDelete {
		for _, c := range childReposIDList {
			if stockMap[c.ID][v].Quantity != 0 {
				stocksToCreate = append(
					stocksToCreate,
					tx.Stock.
						Create().
						SetItemID(v).
						SetTenantID(req.MutationTenantID()).
						SetRepositoryID(c.ID).
						SetQuantity(0).
						SetCreatedBy(req.User().ID).
						SetVersion(stockMap[c.ID][v].Version+1),
				)
				transactionsToCreate = append(
					transactionsToCreate,
					tx.Transaction.
						Create().
						SetItemID(v).
						SetTenantID(req.MutationTenantID()).
						SetRepositoryID(c.ID).
						SetType(transaction.TypeOut).
						SetQuantity(stockMap[repo.ID][v].Quantity).
						SetCreatedBy(req.User().ID),
				)
			}
		}

		if stockMap[repo.ID][v].Quantity != 0 {
			stocksToCreate = append(
				stocksToCreate,
				tx.Stock.
					Create().
					SetItemID(v).
					SetTenantID(req.MutationTenantID()).
					SetRepositoryID(repo.ID).
					SetQuantity(0).
					SetCreatedBy(req.User().ID).
					SetVersion(stockMap[repo.ID][v].Version+1),
			)
			transactionsToCreate = append(
				transactionsToCreate,
				tx.Transaction.
					Create().
					SetItemID(v).
					SetTenantID(req.MutationTenantID()).
					SetRepositoryID(repo.ID).
					SetType(transaction.TypeOut).
					SetQuantity(stockMap[repo.ID][v].Quantity).
					SetCreatedBy(req.User().ID),
			)
		}

		if repo.ParentID != uuid.Nil && stockMap[repo.ID][v].Quantity != 0 && stockMap[repo.ParentID][v].Quantity != 0 {
			stocksToCreate = append(
				stocksToCreate,
				tx.Stock.
					Create().
					SetItemID(v).
					SetTenantID(req.MutationTenantID()).
					SetRepositoryID(repo.ParentID).
					SetQuantity(stockMap[repo.ParentID][v].Quantity-stockMap[repo.ID][v].Quantity).
					SetCreatedBy(req.User().ID).
					SetVersion(stockMap[repo.ParentID][v].Version+1),
			)
			transactionsToCreate = append(
				transactionsToCreate,
				tx.Transaction.
					Create().
					SetItemID(v).
					SetTenantID(req.MutationTenantID()).
					SetRepositoryID(repo.ParentID).
					SetType(transaction.TypeOut).
					SetQuantity(stockMap[repo.ID][v].Quantity).
					SetCreatedBy(req.User().ID),
			)
		}
	}
	_, err = tx.Stock.CreateBulk(stocksToCreate...).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed inserting stocks: %w", err)
	}

	_, err = tx.Transaction.CreateBulk(transactionsToCreate...).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed inserting transactions: %w", err)
	}

	deletedID := input.RepositoryID
	if input.ItemID != nil {
		deletedID = *input.ItemID
	}

	return &model.RepositoryDeletePayload{DeletedID: &deletedID}, nil
}

// RebuildInventoryStock is the resolver for the rebuildInventoryStock field.
// Requires admin role to execute.
func (r *mutationResolver) RebuildInventoryStock(ctx context.Context) (*model.RebuildStockOutput, error) {
	req := request.ForContext(ctx)

	if !req.User().HasRole(authn.ROLE_ADMIN, req.MutationTenantID()) {
		return nil, fmt.Errorf("%w: admin role required for rebuildInventoryStock", authn.ErrUnauthorized)
	}

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// The rebuild replays every movement, writing one stock row per event.
	// Emitting an outbox event per replayed row would flood the outbox and can
	// OOM the publisher draining the backlog, so suppress event creation by
	// default for this mutation. A caller can opt back into normal event
	// emission by explicitly requesting sync updates (X-Pyck-Feature:
	// syncupdates); all other mutations keep the normal sync behavior.
	rebuildCtx := ctx
	if !feature.HasFeature(ctx, feature.FEATURE_SYNC_UPDATES) {
		rebuildCtx = feature.Context(ctx, feature.FEATURE_SUPPRESS_EVENTS)
	}

	if err := r.stock.RebuildStockTable(rebuildCtx, tx, req.MutationTenantID()); err != nil {
		return nil, err
	}

	return &model.RebuildStockOutput{Success: true}, nil
}

// CreateInventoryItemSet is the resolver for the createInventoryItemSet field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateInventoryItemSet(ctx context.Context, input ent.CreateInventoryItemSetInput) (*model.InventoryItemSetOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryItemSetOutput
	req := request.ForContext(ctx)

	items, err := tx.Item.Query().
		Where(entitem.TenantID(req.MutationTenantID())).
		Where(entitem.IDIn(input.ItemIDs...)).
		AllPages(ctx, mixin.Limit)
	if err != nil {
		return nil, err
	}

	if len(items) != len(input.ItemIDs) {
		return nil, errors.New("invalid itemIDs")
	}

	itemIds := make(map[uuid.UUID]struct{})
	for _, item := range items {
		itemIds[item.ID] = struct{}{}
	}

	for _, itemID := range input.ItemIDs {
		_, ok := itemIds[itemID]
		if !ok {
			return nil, fmt.Errorf("item with ID %s not found", itemID)
		}
	}

	itemSet, err := tx.ItemSet.
		Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: itemset.Table,
		FieldName: itemset.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryItemSet = itemSet
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// UpdateInventoryItemSet is the resolver for the updateInventoryItemSet field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateInventoryItemSet(ctx context.Context, id uuid.UUID, input ent.UpdateInventoryItemSetInput) (*model.InventoryItemSetOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryItemSetOutput
	req := request.ForContext(ctx)

	// Verify the item set belongs to the caller's tenant before validating input.
	if _, err := tx.ItemSet.Get(ctx, id); err != nil {
		return nil, fmt.Errorf("invalid item set: %w", err)
	}

	if len(input.AddItemIDs) > 0 {
		items, err := tx.Item.Query().
			Where(entitem.TenantID(req.MutationTenantID())).
			Where(entitem.IDIn(input.AddItemIDs...)).
			AllPages(ctx, mixin.Limit)
		if err != nil {
			return nil, err
		}

		if len(items) != len(input.AddItemIDs) {
			return nil, errors.New("invalid addItemIDs")
		}

		itemIds := make(map[uuid.UUID]struct{})
		for _, item := range items {
			itemIds[item.ID] = struct{}{}
		}

		for _, itemID := range input.AddItemIDs {
			_, ok := itemIds[itemID]
			if !ok {
				return nil, fmt.Errorf("item with ID %s not found", itemID)
			}
		}
	}

	itemSet, err := tx.ItemSet.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: itemset.Table,
		FieldName: itemset.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	resp.InventoryItemSet = itemSet
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// DeleteInventoryItemSet is the resolver for the deleteInventoryItemSet field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteInventoryItemSet(ctx context.Context, id uuid.UUID) (*model.InventoryItemSetDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.InventoryItemSetDeletePayload
	req := request.ForContext(ctx)

	_, err = tx.ItemSet.UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	resp.DeletedID = &id
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// CreateReplenishmentOrder is the resolver for the createReplenishmentOrder field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateReplenishmentOrder(ctx context.Context, input model.CreateReplenishmentOrderWithItemsInput) (*model.ReplenishmentOrderOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}

	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	// Validate uniqueness for replenishment order
	if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: replenishmentorder.Table,
		FieldName: replenishmentorder.FieldData,
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		return nil, err
	}

	// Create replenishment order
	var orderInput ent.CreateReplenishmentOrderInput
	orderInput.Data = input.Data
	orderInput.SupplierID = input.SupplierID
	if dataType != nil {
		orderInput.DataTypeID = &dataType.ID
		orderInput.DataTypeSlug = &dataType.Slug
	}
	createdOrder, err := tx.ReplenishmentOrder.Create().SetInput(orderInput).Save(ctx)
	if err != nil {
		return nil, err
	}

	// Prepare and validate order items
	var bulk []*ent.ReplenishmentOrderItemCreate
	for _, item := range input.Items {
		if item == nil {
			continue
		}
		itemDataType, err := r.validator.ValidateDataTypeInput(ctx, true, item.Data, item.DataTypeID, item.DataTypeSlug)
		if err != nil {
			return nil, err
		}
		mixin.PatchDataTypeIdSlugInput(item, itemDataType)
		if err := r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
			Input:     item.Data,
			DataType:  itemDataType,
			TableName: replenishmentorderitem.Table,
			FieldName: replenishmentorderitem.FieldData,
			DbDriver:  core.Config.DbDriver,
		}); err != nil {
			return nil, err
		}
		createInput := ent.CreateReplenishmentOrderItemInput{
			Data:                 item.Data,
			Sku:                  item.Sku,
			Quantity:             int64(item.Quantity),
			ReplenishmentOrderID: createdOrder.ID,
		}
		if itemDataType != nil {
			createInput.DataTypeID = &itemDataType.ID
			createInput.DataTypeSlug = &itemDataType.Slug
		}
		bulk = append(bulk, tx.ReplenishmentOrderItem.Create().SetInput(createInput))
	}

	// Bulk create order items
	_, err = tx.ReplenishmentOrderItem.CreateBulk(bulk...).Save(ctx)
	if err != nil {
		return nil, err
	}

	resp := &model.ReplenishmentOrderOutput{
		ReplenishmentOrder: createdOrder,
		Workflows:          make([]*model.TemporalWorkflow, 0),
	}

	return resp, nil
}

// UpdateReplenishmentOrder is the resolver for the updateReplenishmentOrder field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateReplenishmentOrder(ctx context.Context, id uuid.UUID, input ent.UpdateReplenishmentOrderInput) (*model.ReplenishmentOrderOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		log.ForContext(ctx).Err(err).Msg("Failed data type validation in UpdateReplenishmentOrder")
		return nil, err
	}
	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.ReplenishmentOrderOutput

	order, err := tx.ReplenishmentOrder.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		log.ForContext(ctx).Err(err).Msg("Failed to update replenishment order in database")
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: "replenishment_orders",
		FieldName: "data",
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		log.ForContext(ctx).Err(err).Msg("Failed data uniqueness validation in UpdateReplenishmentOrder")
		return nil, err
	}

	resp.ReplenishmentOrder = order
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// DeleteReplenishmentOrder is the resolver for the deleteReplenishmentOrder field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteReplenishmentOrder(ctx context.Context, id uuid.UUID) (*model.ReplenishmentOrderDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.ReplenishmentOrderDeletePayload
	req := request.ForContext(ctx)

	// Get the order before deletion for event publishing
	_, err = tx.ReplenishmentOrder.Get(ctx, id)
	if err != nil {
		log.ForContext(ctx).Err(err).Msg("Failed to get replenishment order for deletion")
		return nil, err
	}

	_, err = tx.ReplenishmentOrder.UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		log.ForContext(ctx).Err(err).Msg("Failed to delete replenishment order from database")
		return nil, err
	}

	// Cascade delete child items
	items, err := tx.ReplenishmentOrderItem.
		Query().
		Where(replenishmentorderitem.ReplenishmentOrderID(id)).
		AllPages(ctx, mixin.Limit)
	if err != nil {
		return nil, err
	}

	for _, v := range items {
		_, err = tx.ReplenishmentOrderItem.
			UpdateOneID(v.ID).
			SetDeletedAt(time.Now().UTC()).
			SetDeletedBy(req.User().ID).
			Save(ctx)
		if err != nil {
			return nil, err
		}
	}

	resp.DeletedID = &id
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// CreateReplenishmentOrderItem is the resolver for the createReplenishmentOrderItem field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) CreateReplenishmentOrderItem(ctx context.Context, input ent.CreateReplenishmentOrderItemInput) (*model.ReplenishmentOrderItemOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}
	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.ReplenishmentOrderItemOutput

	// Verify the parent order belongs to the caller's tenant.
	if _, err := tx.ReplenishmentOrder.Get(ctx, input.ReplenishmentOrderID); err != nil {
		return nil, fmt.Errorf("invalid replenishment order: %w", err)
	}

	orderItem, err := tx.ReplenishmentOrderItem.Create().
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	resp.ReplenishmentOrderItem = orderItem
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// UpdateReplenishmentOrderItem is the resolver for the updateReplenishmentOrderItem field.
// MutationEventHook captures the mutation automatically.
func (r *mutationResolver) UpdateReplenishmentOrderItem(ctx context.Context, id uuid.UUID, input ent.UpdateReplenishmentOrderItemInput) (*model.ReplenishmentOrderItemOutput, error) {
	dataType, err := r.validator.ValidateDataTypeInput(ctx, true, input.Data, input.DataTypeID, input.DataTypeSlug)
	if err != nil {
		return nil, err
	}
	mixin.PatchDataTypeIdSlugInput(&input, dataType)

	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.ReplenishmentOrderItemOutput

	orderItem, err := tx.ReplenishmentOrderItem.
		UpdateOneID(id).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if err = r.validator.ValidateInputDataUniqueness(ctx, tx, validator.UniquenessValidationParams{
		Input:     input.Data,
		DataType:  dataType,
		TableName: "replenishment_order_items",
		FieldName: "data",
		DbDriver:  core.Config.DbDriver,
	}); err != nil {
		log.ForContext(ctx).Err(err).Msg("Failed data uniqueness validation in UpdateReplenishmentOrderItem")
		return nil, err
	}

	resp.ReplenishmentOrderItem = orderItem
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// DeleteReplenishmentOrderItem is the resolver for the deleteReplenishmentOrderItem field.
// MutationEventHook detects the soft delete automatically.
func (r *mutationResolver) DeleteReplenishmentOrderItem(ctx context.Context, id uuid.UUID) (*model.ReplenishmentOrderItemDeletePayload, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	var resp model.ReplenishmentOrderItemDeletePayload
	req := request.ForContext(ctx)

	_, err = tx.ReplenishmentOrderItem.UpdateOneID(id).
		SetDeletedAt(time.Now().UTC()).
		SetDeletedBy(req.User().ID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	resp.DeletedID = &id
	resp.Workflows = make([]*model.TemporalWorkflow, 0)

	return &resp, nil
}

// PatchInventoryItemData applies RFC 6902 JSON Patch operations to the item's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchInventoryItemData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.InventoryItemOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.Item.Query().Where(entitem.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    entitem.Table,
		FieldName:    entitem.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.Item.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.InventoryItemOutput{InventoryItem: updated}, nil
}

// PatchInventoryRepositoryData applies RFC 6902 JSON Patch operations to the repository's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchInventoryRepositoryData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.InventoryRepositoryOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.Repository.Query().Where(repository.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    repository.Table,
		FieldName:    repository.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.Repository.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.InventoryRepositoryOutput{InventoryRepository: updated}, nil
}

// PatchInventoryItemMovementData applies RFC 6902 JSON Patch operations to the item movement's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchInventoryItemMovementData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.InventoryItemMovementOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.ItemMovement.Query().Where(itemmovement.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    itemmovement.Table,
		FieldName:    itemmovement.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.ItemMovement.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.InventoryItemMovementOutput{InventoryItemMovement: updated}, nil
}

// PatchInventoryRepositoryMovementData applies RFC 6902 JSON Patch operations to the repository movement's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchInventoryRepositoryMovementData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.InventoryRepositoryMovementOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.RepositoryMovement.Query().Where(repositorymovement.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    repositorymovement.Table,
		FieldName:    repositorymovement.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.RepositoryMovement.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.InventoryRepositoryMovementOutput{InventoryRepositoryMovement: updated}, nil
}

// PatchInventoryCollectionMovementData applies RFC 6902 JSON Patch operations to the collection movement's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchInventoryCollectionMovementData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.UpdateCollectionMovementOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.Collection_Movement.Query().Where(collection_movement.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    collection_movement.Table,
		FieldName:    collection_movement.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.Collection_Movement.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.UpdateCollectionMovementOutput{InventoryCollection: updated}, nil
}

// PatchInventoryItemSetData applies RFC 6902 JSON Patch operations to the item set's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchInventoryItemSetData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.InventoryItemSetOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.ItemSet.Query().Where(itemset.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    itemset.Table,
		FieldName:    itemset.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.ItemSet.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.InventoryItemSetOutput{InventoryItemSet: updated}, nil
}

// PatchReplenishmentOrderData applies RFC 6902 JSON Patch operations to the replenishment order's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchReplenishmentOrderData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.ReplenishmentOrderOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.ReplenishmentOrder.Query().Where(replenishmentorder.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    replenishmentorder.Table,
		FieldName:    replenishmentorder.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.ReplenishmentOrder.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReplenishmentOrderOutput{ReplenishmentOrder: updated}, nil
}

// PatchReplenishmentOrderItemData applies RFC 6902 JSON Patch operations to the replenishment order item's data field.
// MutationEventHook captures field-level changes automatically.
func (r *mutationResolver) PatchReplenishmentOrderItemData(ctx context.Context, id uuid.UUID, patches []*jsonpatch.JSONPatchInput) (*model.ReplenishmentOrderItemOutput, error) {
	tx, err := gqltx.ForContext(ctx, ent.TxFromContext)
	if err != nil {
		return nil, err
	}

	q := tx.ReplenishmentOrderItem.Query().Where(replenishmentorderitem.IDEQ(id))
	if core.Config.DbDriver == dialect.Postgres {
		q = q.ForUpdate()
	}
	entity, err := q.Only(ctx)
	if err != nil {
		return nil, err
	}

	patched, err := jsonpatch.PatchEntityData(ctx, jsonpatch.PatchParams{
		CurrentData:  entity.Data,
		DataTypeID:   &entity.DataTypeID,
		DataTypeSlug: &entity.DataTypeSlug,
		Patches:      jsonpatch.ToOperations(patches),
		Validator:    r.validator,
		Executor:     tx,
		TableName:    replenishmentorderitem.Table,
		FieldName:    replenishmentorderitem.FieldData,
		DbDriver:     core.Config.DbDriver,
		EntityID:     id,
	})
	if err != nil {
		return nil, err
	}

	updated, err := tx.ReplenishmentOrderItem.UpdateOneID(id).SetData(patched).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.ReplenishmentOrderItemOutput{ReplenishmentOrderItem: updated}, nil
}

// Mutation returns exec.MutationResolver implementation.
func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
