package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqljson"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/replenishmentorder"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/replenishmentorderitem"
)

// Data is the resolver for the Data field.
func (r *replenishmentOrderItemWhereInputResolver) Data(ctx context.Context, obj *gen.ReplenishmentOrderItemWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueEQ(replenishmentorderitem.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataHasKey is the resolver for the DataHasKey field.
func (r *replenishmentOrderItemWhereInputResolver) DataHasKey(ctx context.Context, obj *gen.ReplenishmentOrderItemWhereInput, data *string) error {
	if obj == nil || data == nil {
		return nil
	}

	if *data != "" {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.HasKey(replenishmentorderitem.FieldData, sqljson.DotPath(*data)))
		})
	}
	return nil
}

// DataIn is the resolver for the DataIn field.
func (r *replenishmentOrderItemWhereInputResolver) DataIn(ctx context.Context, obj *gen.ReplenishmentOrderItemWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) >= 2 {
		var args []any
		for _, v := range data[1:] {
			args = append(args, v)
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueIn(replenishmentorderitem.FieldData, args, sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataContains is the resolver for the DataContains field.
func (r *replenishmentOrderItemWhereInputResolver) DataContains(ctx context.Context, obj *gen.ReplenishmentOrderItemWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueContains(replenishmentorderitem.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// Data is the resolver for the Data field.
func (r *replenishmentOrderWhereInputResolver) Data(ctx context.Context, obj *gen.ReplenishmentOrderWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueEQ(replenishmentorder.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataHasKey is the resolver for the DataHasKey field.
func (r *replenishmentOrderWhereInputResolver) DataHasKey(ctx context.Context, obj *gen.ReplenishmentOrderWhereInput, data *string) error {
	if obj == nil || data == nil {
		return nil
	}

	if *data != "" {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.HasKey(replenishmentorder.FieldData, sqljson.DotPath(*data)))
		})
	}
	return nil
}

// DataIn is the resolver for the DataIn field.
func (r *replenishmentOrderWhereInputResolver) DataIn(ctx context.Context, obj *gen.ReplenishmentOrderWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) >= 2 {
		var args []any
		for _, v := range data[1:] {
			args = append(args, v)
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueIn(replenishmentorder.FieldData, args, sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataContains is the resolver for the DataContains field.
func (r *replenishmentOrderWhereInputResolver) DataContains(ctx context.Context, obj *gen.ReplenishmentOrderWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueContains(replenishmentorder.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}
