package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqljson"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/repository"
	"github.com/pyck-ai/pyck/backend/inventory/model"
)

// Data is the resolver for the Data field.
func (r *repositoryWhereInputResolver) Data(ctx context.Context, obj *gen.RepositoryWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueEQ(repository.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataHasKey is the resolver for the DataHasKey field.
func (r *repositoryWhereInputResolver) DataHasKey(ctx context.Context, obj *gen.RepositoryWhereInput, data *string) error {
	if obj == nil || data == nil {
		return nil
	}

	if *data != "" {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.HasKey(repository.FieldData, sqljson.DotPath(*data)))
		})
	}
	return nil
}

// DataIn is the resolver for the DataIn field.
func (r *repositoryWhereInputResolver) DataIn(ctx context.Context, obj *gen.RepositoryWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) >= 2 {
		var args []any
		for _, v := range data[1:] {
			args = append(args, v)
		}
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueIn(repository.FieldData, args, sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataContains is the resolver for the DataContains field.
func (r *repositoryWhereInputResolver) DataContains(ctx context.Context, obj *gen.RepositoryWhereInput, data []string) error {
	if obj == nil || data == nil {
		return nil
	}

	if len(data) == 2 {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueContains(repository.FieldData, data[1], sqljson.DotPath(data[0])))
		})
	}
	return nil
}

// DataContainsBool is the resolver for the DataContainsBool field.
func (r *repositoryWhereInputResolver) DataContainsBool(ctx context.Context, obj *gen.RepositoryWhereInput, data *model.DataBoolInput) error {
	if obj == nil || data == nil {
		return nil
	}

	if data.Key != nil && data.Value != nil {
		obj.AddPredicates(func(s *sql.Selector) {
			s.Where(sqljson.ValueContains(repository.FieldData, *data.Value, sqljson.DotPath(*data.Key)))
		})
	}
	return nil
}
