package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"sort"
	"time"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqljson"
	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/common/ent/mixin"
	"github.com/pyck-ai/pyck/backend/common/request"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/repository"
	"github.com/pyck-ai/pyck/backend/inventory/ent/gen/stock"
	"github.com/pyck-ai/pyck/backend/inventory/model"
)

// GetStockTree returns a paginated forest of RepositoryTree roots with current stocks.
func (r *queryResolver) GetStockTree(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *gen.StockWhereInput) (*model.RepositoryTreeConnection, error) {
	if where == nil {
		where = &gen.StockWhereInput{}
	}

	if where.CreatedAtLT == nil {
		now := time.Now().UTC()
		where.CreatedAtLT = &now
	}

	req := request.ForContext(ctx)

	if where.TenantID == nil {
		where.TenantIDIn = req.TenantIDs()
	}

	// Keep only the latest stock row per (repository_id, item_id) as of the
	// cutoff, deduplicated inline via a correlated NOT EXISTS predicate that is
	// evaluated together with the query's own filters and explicit pagination.
	//
	// Previously the latest-row ids were pre-computed in a separate, tenant-wide
	// query whose result was then re-queried by IDIn. That query carried no
	// explicit limit, so the LimitMixin interceptor silently capped it at the
	// default limit with no ORDER BY; on tenants with more (item, repository)
	// pairs than the cap the wanted rows fell outside the arbitrary capped set
	// and the tree came back wrong (often empty).
	stockPreds := BuildPredicates(where)
	stockPreds = append(stockPreds, latestStockPredicate(*where.CreatedAtLT, req.TenantIDs()))

	stocks, err := r.client.Stock.Query().
		Where(stockPreds...).
		Order(gen.Desc(stock.FieldCreatedAt)).
		AllPages(ctx, mixin.Limit)
	if err != nil {
		return nil, err
	}

	stocksByRepo := make(map[uuid.UUID][]*gen.Stock)
	var stockedRepos []uuid.UUID
	for _, s := range stocks {
		if _, exists := stocksByRepo[s.RepositoryID]; !exists {
			stockedRepos = append(stockedRepos, s.RepositoryID)
		}
		stocksByRepo[s.RepositoryID] = append(stocksByRepo[s.RepositoryID], s)
	}

	repos, err := r.client.Repository.Query().
		Where(repository.TenantIDIn(req.TenantIDs()...)).
		AllPages(ctx, mixin.Limit)
	if err != nil {
		return nil, err
	}

	repoTree := make(map[uuid.UUID]*model.RepositoryTree, len(repos))
	childrenMap := make(map[uuid.UUID]bool)

	for _, repo := range repos {
		var parentID *uuid.UUID
		if repo.ParentID != uuid.Nil {
			pid := repo.ParentID
			parentID = &pid
		} else {
			parentID = nil
		}

		repoTree[repo.ID] = &model.RepositoryTree{
			RepositoryID: repo.ID,
			ParentID:     parentID,
			Stocks:       stocksByRepo[repo.ID],
			Children:     []*model.RepositoryTreeEdge{},
			CreatedAt:    repo.CreatedAt,
		}
	}

	for id, node := range repoTree {
		if node.ParentID != nil && *node.ParentID != uuid.Nil {
			if parent, ok := repoTree[*node.ParentID]; ok {
				parent.Children = append(parent.Children, &model.RepositoryTreeEdge{
					Cursor: entgql.Cursor[uuid.UUID]{ID: id},
					Node:   node,
				})
				childrenMap[id] = true
			}
		}
	}

	var roots []*model.RepositoryTree
	for id, node := range repoTree {
		if !childrenMap[id] {
			roots = append(roots, node)
		}
	}
	sort.SliceStable(roots, func(i, j int) bool { return roots[i].CreatedAt.After(roots[j].CreatedAt) })

	includeInit := map[uuid.UUID]struct{}{}
	for _, id := range stockedRepos {
		for cursorID := id; cursorID != uuid.Nil; {
			includeInit[cursorID] = struct{}{}
			if n := repoTree[cursorID]; n != nil && n.ParentID != nil {
				cursorID = *n.ParentID
			} else {
				break
			}
		}
	}

	initialTree := PruneTree(roots, includeInit)
	allEdges := FlattenTreeEdges(initialTree)

	var stockedEdges []*model.RepositoryTreeEdge
	for _, e := range allEdges {
		if len(e.Node.Stocks) > 0 {
			stockedEdges = append(stockedEdges, e)
		}
	}
	total := len(stockedEdges)

	start, end := 0, total
	if after != nil {
		for i, e := range stockedEdges {
			if e.Cursor.ID == after.ID {
				start = i + 1
				break
			}
		}
	}

	if before != nil {
		for i, e := range stockedEdges {
			if e.Cursor.ID == before.ID {
				end = i
				break
			}
		}
	}

	if first != nil && end-start > *first {
		end = start + *first
	}

	if last != nil && end-start > *last {
		start = end - *last
		if start < 0 {
			start = 0
		}
	}
	selectedEdges := stockedEdges[start:end]

	includeSelected := map[uuid.UUID]struct{}{}
	for _, e := range selectedEdges {
		for cursorID := e.Cursor.ID; cursorID != uuid.Nil; {
			includeSelected[cursorID] = struct{}{}
			if n := repoTree[cursorID]; n != nil && n.ParentID != nil {
				cursorID = *n.ParentID
			} else {
				break
			}
		}
	}
	finalTree := PruneTree(initialTree, includeSelected)

	var outEdges []*model.RepositoryTreeEdge
	if after != nil || before != nil || first != nil || last != nil {
		for _, r := range finalTree {
			outEdges = append(outEdges, &model.RepositoryTreeEdge{
				Cursor: entgql.Cursor[uuid.UUID]{ID: r.RepositoryID},
				Node:   r,
			})
		}
	} else {
		for _, r := range initialTree {
			outEdges = append(outEdges, &model.RepositoryTreeEdge{
				Cursor: entgql.Cursor[uuid.UUID]{ID: r.RepositoryID},
				Node:   r,
			})
		}
	}

	var startCursor, endCursor *entgql.Cursor[uuid.UUID]
	if len(selectedEdges) > 0 {
		startCursor = &selectedEdges[0].Cursor
		endCursor = &selectedEdges[len(selectedEdges)-1].Cursor
	}

	return &model.RepositoryTreeConnection{
		Edges: outEdges,
		PageInfo: &entgql.PageInfo[uuid.UUID]{
			StartCursor:     startCursor,
			EndCursor:       endCursor,
			HasNextPage:     end < total,
			HasPreviousPage: start > 0,
		},
	}, nil
}

// Time is the resolver for the time field.
func (r *stockWhereInputResolver) Time(ctx context.Context, obj *gen.StockWhereInput, data *time.Time) error {
	if data == nil {
		t := time.Now().UTC()
		data = &t
	}

	// Set CreatedAtLT so GetStockTree (which uses BuildPredicates) can use the
	// time cutoff in its own latest-per-group logic.
	obj.CreatedAtLT = data

	req := request.ForContext(ctx)
	tenantIDs := req.TenantIDs()
	if len(tenantIDs) == 0 {
		return nil
	}

	// Deduplicate to the latest stock row per (repository_id, item_id) before the
	// cutoff via a correlated NOT EXISTS predicate. It is evaluated together with
	// the stocks query's own filters (e.g. itemID) and its explicit pagination
	// limit, so it stays scoped and bounded.
	//
	// Previously the latest-row ids were pre-computed in a separate, tenant-wide
	// query and added as an IDIn predicate. That query carried no explicit limit,
	// so the LimitMixin interceptor silently capped it at the default limit with
	// no ORDER BY; on tenants with more (item, repository) pairs than the cap the
	// requested rows fell outside the arbitrary capped set and the query returned
	// 0 rows.
	obj.AddPredicates(latestStockPredicate(*data, tenantIDs))

	return nil
}

// NetStockGte is the resolver for the netStockGTE field.
func (r *stockWhereInputResolver) NetStockGte(ctx context.Context, obj *gen.StockWhereInput, data *int) error {
	if obj == nil || data == nil {
		return nil
	}

	obj.AddPredicates(func(s *sql.Selector) {
		expr := fmt.Sprintf("(%s + %s - %s)",
			s.C(stock.FieldOwnQuantity),
			s.C(stock.FieldOwnIncomingStock),
			s.C(stock.FieldOwnOutgoingStock),
		)
		s.Where(sqljson.ValueGTE(expr, *data))
	})

	return nil
}
