// Code generated by importgen; DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/pyck-ai/pyck/backend/common/importexport"
	"github.com/pyck-ai/pyck/backend/inventory/model"
)

// RegisterEntities registers all importable inventory service entities
// with the given registry.
func RegisterEntities(r *importexport.Registry, c Client) error {
	for _, fn := range []func(*importexport.Registry, Client) error{
		registerInventoryItem,
		registerInventoryItemSet,
		registerItemMovement,
		registerReplenishmentOrder,
		registerReplenishmentOrderItem,
		registerRepository,
		registerRepositoryMovement,
	} {
		if err := fn(r, c); err != nil {
			return err
		}
	}
	return nil
}

func registerInventoryItem(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "InventoryItem",
		Service:       "inventory",
		IdentityField: "sku",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *InventoryItemWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[InventoryItemWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetInventoryItems(ctx, GetInventoryItemsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetInventoryItems()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateInventoryItemInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateInventoryItem(ctx, CreateInventoryItemArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateInventoryItem().GetInventoryItem())
		},
		Update: func(ctx context.Context, id string, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[UpdateInventoryItemInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.UpdateInventoryItem(ctx, UpdateInventoryItemArgs{Id: id, Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetUpdateInventoryItem().GetInventoryItem())
		},
	})
}

func registerInventoryItemSet(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "InventoryItemSet",
		Service:       "inventory",
		IdentityField: "sku",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *InventoryItemSetWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[InventoryItemSetWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetInventoryItemSets(ctx, GetInventoryItemSetsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetInventoryItemSets()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateInventoryItemSetInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateInventoryItemSet(ctx, CreateInventoryItemSetArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateInventoryItemSet().GetInventoryItemSet())
		},
		Update: func(ctx context.Context, id string, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[UpdateInventoryItemSetInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.UpdateInventoryItemSet(ctx, UpdateInventoryItemSetArgs{Id: id, Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetUpdateInventoryItemSet().GetInventoryItemSet())
		},
	})
}

func registerItemMovement(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "ItemMovement",
		Service:       "inventory",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *ItemMovementWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[ItemMovementWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetItemMovements(ctx, GetItemMovementsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetItemMovements()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateItemMovementInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateInventoryItemMovement(ctx, CreateInventoryItemMovementArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateInventoryItemMovement().GetInventoryItemMovement())
		},
	})
}

func registerReplenishmentOrder(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "ReplenishmentOrder",
		Service:       "inventory",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *ReplenishmentOrderWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[ReplenishmentOrderWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetReplenishmentOrders(ctx, GetReplenishmentOrdersArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetReplenishmentOrders()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[model.CreateReplenishmentOrderWithItemsInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateReplenishmentOrder(ctx, CreateReplenishmentOrderArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateReplenishmentOrder().GetReplenishmentOrder())
		},
	})
}

func registerReplenishmentOrderItem(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "ReplenishmentOrderItem",
		Service:       "inventory",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *ReplenishmentOrderItemWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[ReplenishmentOrderItemWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetReplenishmentOrderItems(ctx, GetReplenishmentOrderItemsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetReplenishmentOrderItems()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateReplenishmentOrderItemInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateReplenishmentOrderItem(ctx, CreateReplenishmentOrderItemArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateReplenishmentOrderItem().GetReplenishmentOrderItem())
		},
	})
}

func registerRepository(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "Repository",
		Service:       "inventory",
		IdentityField: "name",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *RepositoryWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[RepositoryWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetRepositories(ctx, GetRepositoriesArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetRepositories()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateRepositoryInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateInventoryRepository(ctx, CreateInventoryRepositoryArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateInventoryRepository().GetInventoryRepository())
		},
		Update: func(ctx context.Context, id string, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[UpdateRepositoryInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.UpdateInventoryRepository(ctx, UpdateInventoryRepositoryArgs{Id: id, Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetUpdateInventoryRepository().GetInventoryRepository())
		},
	})
}

func registerRepositoryMovement(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "RepositoryMovement",
		Service:       "inventory",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *RepositoryMovementWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[RepositoryMovementWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetRepositoryMovements(ctx, GetRepositoryMovementsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetRepositoryMovements()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreateRepositoryMovementInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreateInventoryRepositoryMovement(ctx, CreateInventoryRepositoryMovementArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreateInventoryRepositoryMovement().GetInventoryRepositoryMovement())
		},
	})
}
