// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/pyck-ai/pyck/backend/receiving/ent/gen"
)

type CreateReceivingInboundItemsInput struct {
	DataTypeID   *uuid.UUID     `json:"dataTypeID,omitempty"`
	DataTypeSlug *string        `json:"dataTypeSlug,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
	Sku          string         `json:"sku"`
	Quantity     int            `json:"quantity"`
}

type CreateReceivingInboundWithItemsInput struct {
	DataTypeID   *uuid.UUID                          `json:"dataTypeID,omitempty"`
	DataTypeSlug *string                             `json:"dataTypeSlug,omitempty"`
	Data         map[string]any                      `json:"data,omitempty"`
	SupplierID   *uuid.UUID                          `json:"supplierID,omitempty"`
	OrderID      *string                             `json:"orderID,omitempty"`
	InboundItems []*CreateReceivingInboundItemsInput `json:"inboundItems,omitempty"`
}

type ReceivingInboundDeletePayload struct {
	DeletedID *uuid.UUID          `json:"deletedID,omitempty"`
	Workflows []*TemporalWorkflow `json:"workflows,omitempty"`
}

type ReceivingInboundItemDeletePayload struct {
	DeletedID *uuid.UUID          `json:"deletedID,omitempty"`
	Workflows []*TemporalWorkflow `json:"workflows,omitempty"`
}

type ReceivingInboundItemOutput struct {
	ReceivingInboundItem *gen.InboundItem    `json:"receivingInboundItem,omitempty"`
	Workflows            []*TemporalWorkflow `json:"workflows,omitempty"`
}

type ReceivingInboundOutput struct {
	ReceivingInbound *gen.Inbound        `json:"receivingInbound,omitempty"`
	Workflows        []*TemporalWorkflow `json:"workflows,omitempty"`
}

type ReceivingInboundShipmentNotificationDeletePayload struct {
	DeletedID *uuid.UUID          `json:"deletedID,omitempty"`
	Workflows []*TemporalWorkflow `json:"workflows,omitempty"`
}

type ReceivingInboundShipmentNotificationOutput struct {
	ReceivingInboundShipmentNotification *gen.InboundShipmentNotification `json:"receivingInboundShipmentNotification,omitempty"`
	Workflows                            []*TemporalWorkflow              `json:"workflows,omitempty"`
}

type ServiceInfo struct {
	Version string     `json:"version"`
	Date    *time.Time `json:"date,omitempty"`
}

type TemporalMetadata struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TemporalWorkflow struct {
	Type  string `json:"type"`
	ID    string `json:"id"`
	RunID string `json:"runID"`
}
