// Code generated by "enumer -text -json -yaml -sql -gqlgen -typederrors -output=fieldname_gen.go -type=FieldName -trimprefix=Field"; DO NOT EDIT.

package fieldnames

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"io"
	"strconv"
	"strings"
)

const _FieldNameName = "InvalidDataJSONSchemaTenantIDIDEntityEventsOutboxDataTypeSlugDeletedAt"

var _FieldNameIndex = [...]uint8{0, 7, 11, 21, 29, 31, 49, 61, 70}

const _FieldNameLowerName = "invaliddatajsonschematenantididentityeventsoutboxdatatypeslugdeletedat"

func (i FieldName) String() string {
	if i < 0 || i >= FieldName(len(_FieldNameIndex)-1) {
		return fmt.Sprintf("FieldName(%d)", i)
	}
	return _FieldNameName[_FieldNameIndex[i]:_FieldNameIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FieldNameNoOp() {
	var x [1]struct{}
	_ = x[FieldInvalid-(0)]
	_ = x[FieldData-(1)]
	_ = x[FieldJSONSchema-(2)]
	_ = x[FieldTenantID-(3)]
	_ = x[FieldID-(4)]
	_ = x[FieldEntityEventsOutbox-(5)]
	_ = x[FieldDataTypeSlug-(6)]
	_ = x[FieldDeletedAt-(7)]
}

var _FieldNameValues = []FieldName{FieldInvalid, FieldData, FieldJSONSchema, FieldTenantID, FieldID, FieldEntityEventsOutbox, FieldDataTypeSlug, FieldDeletedAt}

var _FieldNameNameToValueMap = map[string]FieldName{
	_FieldNameName[0:7]:        FieldInvalid,
	_FieldNameLowerName[0:7]:   FieldInvalid,
	_FieldNameName[7:11]:       FieldData,
	_FieldNameLowerName[7:11]:  FieldData,
	_FieldNameName[11:21]:      FieldJSONSchema,
	_FieldNameLowerName[11:21]: FieldJSONSchema,
	_FieldNameName[21:29]:      FieldTenantID,
	_FieldNameLowerName[21:29]: FieldTenantID,
	_FieldNameName[29:31]:      FieldID,
	_FieldNameLowerName[29:31]: FieldID,
	_FieldNameName[31:49]:      FieldEntityEventsOutbox,
	_FieldNameLowerName[31:49]: FieldEntityEventsOutbox,
	_FieldNameName[49:61]:      FieldDataTypeSlug,
	_FieldNameLowerName[49:61]: FieldDataTypeSlug,
	_FieldNameName[61:70]:      FieldDeletedAt,
	_FieldNameLowerName[61:70]: FieldDeletedAt,
}

var _FieldNameNames = []string{
	_FieldNameName[0:7],
	_FieldNameName[7:11],
	_FieldNameName[11:21],
	_FieldNameName[21:29],
	_FieldNameName[29:31],
	_FieldNameName[31:49],
	_FieldNameName[49:61],
	_FieldNameName[61:70],
}

// FieldNameString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FieldNameString(s string) (FieldName, error) {
	if val, ok := _FieldNameNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FieldNameNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to FieldName values", s))
}

// FieldNameValues returns all values of the enum
func FieldNameValues() []FieldName {
	return _FieldNameValues
}

// FieldNameStrings returns a slice of all String values of the enum
func FieldNameStrings() []string {
	strs := make([]string, len(_FieldNameNames))
	copy(strs, _FieldNameNames)
	return strs
}

// IsAFieldName returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FieldName) IsAFieldName() bool {
	for _, v := range _FieldNameValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FieldName
func (i FieldName) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FieldName
func (i *FieldName) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FieldName should be a string, got %s", data)
	}

	var err error
	*i, err = FieldNameString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for FieldName
func (i FieldName) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FieldName
func (i *FieldName) UnmarshalText(text []byte) error {
	var err error
	*i, err = FieldNameString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for FieldName
func (i FieldName) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for FieldName
func (i *FieldName) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = FieldNameString(s)
	return err
}

func (i FieldName) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *FieldName) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of FieldName: %[1]T(%[1]v)", value)
	}

	val, err := FieldNameString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// MarshalGQL implements the graphql.Marshaler interface for FieldName
func (i FieldName) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for FieldName
func (i *FieldName) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("FieldName should be a string, got %T", value)
	}

	var err error
	*i, err = FieldNameString(str)
	return err
}
