// Code generated by github.com/pyck-ai/pyck/backend/common/cmd/entitygen, DO NOT EDIT.

package datatype

// DataTypeEntities contains all entity type names in snake_case.
func DataTypeEntities() []string {
	return []string{
		"collection_movement",
		"customer",
		"device",
		"device_location",
		"device_user",
		"file",
		"inbound",
		"inbound_item",
		"inbound_shipment_notification",
		"item",
		"item_movement",
		"item_set",
		"key_value",
		"location",
		"order",
		"order_items",
		"outbound_shipment_notification",
		"replenishment_order",
		"replenishment_order_item",
		"repository",
		"repository_movement",
		"supplier",
		"tenant",
		"workflow",
	}
}

// ServiceEntities maps each service to the Go type names of all its Ent
// entities, as ent names them (e.g. "DataType"), whether or not they use
// DataMixin.
func ServiceEntities() map[string][]string {
	return map[string][]string{
		"file": {
			"EntityEventsOutbox",
			"File",
			"IdempotencyKey",
		},
		"inventory": {
			"Collection_Movement",
			"EntityEventsOutbox",
			"IdempotencyKey",
			"Item",
			"ItemMovement",
			"ItemSet",
			"ReplenishmentOrder",
			"ReplenishmentOrderItem",
			"Repository",
			"RepositoryMovement",
			"Stock",
			"Transaction",
		},
		"main-data": {
			"Customer",
			"EntityEventsOutbox",
			"IdempotencyKey",
			"Supplier",
		},
		"management": {
			"DataType",
			"Device",
			"DeviceLocation",
			"DeviceUser",
			"EntityEventsOutbox",
			"IdempotencyKey",
			"KeyValue",
			"Location",
			"Tenant",
			"User",
		},
		"picking": {
			"EntityEventsOutbox",
			"IdempotencyKey",
			"Order",
			"OrderItems",
			"OutboundShipmentNotification",
		},
		"receiving": {
			"EntityEventsOutbox",
			"IdempotencyKey",
			"Inbound",
			"InboundItem",
			"InboundShipmentNotification",
		},
		"workflow": {
			"EntityEventsOutbox",
			"IdempotencyKey",
			"Workflow",
			"WorkflowSignal",
		},
	}
}
