// Code generated by github.com/pyck-ai/pyck/backend/common/cmd/apigen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/Yamashou/gqlgenc/clientv2"

	"github.com/pyck-ai/pyck/backend/common/api"
	"github.com/pyck-ai/pyck/backend/common/env"
	"github.com/pyck-ai/pyck/backend/picking/model"

	internalapi "github.com/pyck-ai/pyck/backend/picking/api/internal"
)

type Config = api.Config

// DefaultClient creates a new Client with default configuration loaded from
// environment variables. Additional request interceptors can be provided which
// will be appended to the default ones. The default configuration includes
// authentication and tenant ID headers. Returns an error if the configuration
// cannot be loaded.
func DefaultClient(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (Client, error) {
	_, config, err := env.Load[api.Config](ctx)
	if err != nil {
		return nil, err
	}

	clientOptions := clientv2.Options{
		ParseDataAlongWithErrors: false,
	}

	interceptors = append([]clientv2.RequestInterceptor{
		api.AuthnMiddleware(api.Config{
			GatewayConfig: config.GatewayConfig,
			APIToken:      config.APIToken,
			APITenantID:   config.APITenantID,
		}),
	}, interceptors...)

	return NewClient(http.DefaultClient, config.GatewayUrl, &clientOptions, interceptors...), nil
}

type Client interface {
	GetPickingOrders(ctx context.Context, input GetPickingOrdersArgs) (*GetPickingOrders, error)
	GetPickingOrderItems(ctx context.Context, input GetPickingOrderItemsArgs) (*GetPickingOrderItems, error)
	GetPickingOutboundShipmentNotifications(ctx context.Context, input GetPickingOutboundShipmentNotificationsArgs) (*GetPickingOutboundShipmentNotifications, error)
	GetPickingServiceInfo(ctx context.Context) (*GetPickingServiceInfo, error)
	CreatePickingOrder(ctx context.Context, input CreatePickingOrderArgs) (*CreatePickingOrder, error)
	UpdatePickingOrder(ctx context.Context, input UpdatePickingOrderArgs) (*UpdatePickingOrder, error)
	DeletePickingOrder(ctx context.Context, input DeletePickingOrderArgs) (*DeletePickingOrder, error)
	CreatePickingOrderItem(ctx context.Context, input CreatePickingOrderItemArgs) (*CreatePickingOrderItem, error)
	UpdatePickingOrderItem(ctx context.Context, input UpdatePickingOrderItemArgs) (*UpdatePickingOrderItem, error)
	DeletePickingOrderItem(ctx context.Context, input DeletePickingOrderItemArgs) (*DeletePickingOrderItem, error)
	CreatePickingOutboundShipmentNotification(ctx context.Context, input CreatePickingOutboundShipmentNotificationArgs) (*CreatePickingOutboundShipmentNotification, error)
	UpdatePickingOutboundShipmentNotification(ctx context.Context, input UpdatePickingOutboundShipmentNotificationArgs) (*UpdatePickingOutboundShipmentNotification, error)
	DeletePickingOutboundShipmentNotification(ctx context.Context, input DeletePickingOutboundShipmentNotificationArgs) (*DeletePickingOutboundShipmentNotification, error)
}

type client struct {
	api          internalapi.APIClient
	interceptors []clientv2.RequestInterceptor
}

func NewClient(c clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *client {
	api := internalapi.NewClient(c, baseURL, options, interceptors...)

	return &client{
		api: api,
	}
}

// GetPickingOrdersArgs is a sparse struct for GetPickingOrders parameters
type GetPickingOrdersArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *PickingOrderOrder
	Where   *PickingOrderWhereInput
}

func (c *client) GetPickingOrders(ctx context.Context, input GetPickingOrdersArgs) (*GetPickingOrders, error) {
	return c.api.GetPickingOrders(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetPickingOrderItemsArgs is a sparse struct for GetPickingOrderItems parameters
type GetPickingOrderItemsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *PickingOrderItemOrder
	Where   *PickingOrderItemWhereInput
}

func (c *client) GetPickingOrderItems(ctx context.Context, input GetPickingOrderItemsArgs) (*GetPickingOrderItems, error) {
	return c.api.GetPickingOrderItems(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

// GetPickingOutboundShipmentNotificationsArgs is a sparse struct for GetPickingOutboundShipmentNotifications parameters
type GetPickingOutboundShipmentNotificationsArgs struct {
	After   *string
	First   *int
	Before  *string
	Last    *int
	OrderBy *PickingOutboundShipmentNotificationOrder
	Where   *PickingOutboundShipmentNotificationWhereInput
}

func (c *client) GetPickingOutboundShipmentNotifications(ctx context.Context, input GetPickingOutboundShipmentNotificationsArgs) (*GetPickingOutboundShipmentNotifications, error) {
	return c.api.GetPickingOutboundShipmentNotifications(ctx, input.After, input.First, input.Before, input.Last, input.OrderBy, input.Where)
}

func (c *client) GetPickingServiceInfo(ctx context.Context) (*GetPickingServiceInfo, error) {
	return c.api.GetPickingServiceInfo(ctx)
}

// CreatePickingOrderArgs is a sparse struct for CreatePickingOrder parameters
type CreatePickingOrderArgs struct {
	Input model.CreatePickingOrderWithItemsInput
}

func (c *client) CreatePickingOrder(ctx context.Context, input CreatePickingOrderArgs) (*CreatePickingOrder, error) {
	return c.api.CreatePickingOrder(ctx, input.Input)
}

// UpdatePickingOrderArgs is a sparse struct for UpdatePickingOrder parameters
type UpdatePickingOrderArgs struct {
	Id    string
	Input UpdatePickingOrderInput
}

func (c *client) UpdatePickingOrder(ctx context.Context, input UpdatePickingOrderArgs) (*UpdatePickingOrder, error) {
	return c.api.UpdatePickingOrder(ctx, input.Id, input.Input)
}

// DeletePickingOrderArgs is a sparse struct for DeletePickingOrder parameters
type DeletePickingOrderArgs struct {
	Id string
}

func (c *client) DeletePickingOrder(ctx context.Context, input DeletePickingOrderArgs) (*DeletePickingOrder, error) {
	return c.api.DeletePickingOrder(ctx, input.Id)
}

// CreatePickingOrderItemArgs is a sparse struct for CreatePickingOrderItem parameters
type CreatePickingOrderItemArgs struct {
	Input CreatePickingOrderItemInput
}

func (c *client) CreatePickingOrderItem(ctx context.Context, input CreatePickingOrderItemArgs) (*CreatePickingOrderItem, error) {
	return c.api.CreatePickingOrderItem(ctx, input.Input)
}

// UpdatePickingOrderItemArgs is a sparse struct for UpdatePickingOrderItem parameters
type UpdatePickingOrderItemArgs struct {
	Id    string
	Input UpdatePickingOrderItemInput
}

func (c *client) UpdatePickingOrderItem(ctx context.Context, input UpdatePickingOrderItemArgs) (*UpdatePickingOrderItem, error) {
	return c.api.UpdatePickingOrderItem(ctx, input.Id, input.Input)
}

// DeletePickingOrderItemArgs is a sparse struct for DeletePickingOrderItem parameters
type DeletePickingOrderItemArgs struct {
	Id string
}

func (c *client) DeletePickingOrderItem(ctx context.Context, input DeletePickingOrderItemArgs) (*DeletePickingOrderItem, error) {
	return c.api.DeletePickingOrderItem(ctx, input.Id)
}

// CreatePickingOutboundShipmentNotificationArgs is a sparse struct for CreatePickingOutboundShipmentNotification parameters
type CreatePickingOutboundShipmentNotificationArgs struct {
	Input CreatePickingOutboundShipmentNotificationInput
}

func (c *client) CreatePickingOutboundShipmentNotification(ctx context.Context, input CreatePickingOutboundShipmentNotificationArgs) (*CreatePickingOutboundShipmentNotification, error) {
	return c.api.CreatePickingOutboundShipmentNotification(ctx, input.Input)
}

// UpdatePickingOutboundShipmentNotificationArgs is a sparse struct for UpdatePickingOutboundShipmentNotification parameters
type UpdatePickingOutboundShipmentNotificationArgs struct {
	Id    string
	Input UpdatePickingOutboundShipmentNotificationInput
}

func (c *client) UpdatePickingOutboundShipmentNotification(ctx context.Context, input UpdatePickingOutboundShipmentNotificationArgs) (*UpdatePickingOutboundShipmentNotification, error) {
	return c.api.UpdatePickingOutboundShipmentNotification(ctx, input.Id, input.Input)
}

// DeletePickingOutboundShipmentNotificationArgs is a sparse struct for DeletePickingOutboundShipmentNotification parameters
type DeletePickingOutboundShipmentNotificationArgs struct {
	Id string
}

func (c *client) DeletePickingOutboundShipmentNotification(ctx context.Context, input DeletePickingOutboundShipmentNotificationArgs) (*DeletePickingOutboundShipmentNotification, error) {
	return c.api.DeletePickingOutboundShipmentNotification(ctx, input.Id)
}
