// Code generated by importgen; DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/pyck-ai/pyck/backend/common/importexport"
	"github.com/pyck-ai/pyck/backend/picking/model"
)

// RegisterEntities registers all importable picking service entities
// with the given registry.
func RegisterEntities(r *importexport.Registry, c Client) error {
	for _, fn := range []func(*importexport.Registry, Client) error{
		registerPickingOrder,
		registerPickingOrderItem,
	} {
		if err := fn(r, c); err != nil {
			return err
		}
	}
	return nil
}

func registerPickingOrder(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "PickingOrder",
		Service:       "picking",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *PickingOrderWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[PickingOrderWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetPickingOrders(ctx, GetPickingOrdersArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetPickingOrders()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[model.CreatePickingOrderWithItemsInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreatePickingOrder(ctx, CreatePickingOrderArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreatePickingOrder().GetPickingOrder())
		},
	})
}

func registerPickingOrderItem(r *importexport.Registry, c Client) error {
	return r.Register(&importexport.EntityDescriptor{
		TypeName:      "PickingOrderItem",
		Service:       "picking",
		IdentityField: "",
		List: func(ctx context.Context, after *string, first *int, where map[string]any) (importexport.ListResult, error) {
			var w *PickingOrderItemWhereInput
			if where != nil {
				parsed, err := importexport.MapToStruct[PickingOrderItemWhereInput](where)
				if err != nil {
					return importexport.ListResult{}, fmt.Errorf("parse where: %w", err)
				}
				w = &parsed
			}
			resp, err := c.GetPickingOrderItems(ctx, GetPickingOrderItemsArgs{
				After: after,
				First: first,
				Where: w,
			})
			if err != nil {
				return importexport.ListResult{}, err
			}
			conn := resp.GetPickingOrderItems()
			pi := conn.GetPageInfo()
			edges := conn.GetEdges()
			nodes := make([]any, 0, len(edges))
			for _, e := range edges {
				nodes = append(nodes, e.GetNode())
			}
			return importexport.BuildListResult(nodes, pi.GetHasNextPage(), pi.GetEndCursor())
		},
		Create: func(ctx context.Context, input map[string]any) (map[string]any, error) {
			typed, err := importexport.MapToStruct[CreatePickingOrderItemInput](input)
			if err != nil {
				return nil, fmt.Errorf("parse input: %w", err)
			}
			resp, err := c.CreatePickingOrderItem(ctx, CreatePickingOrderItemArgs{Input: typed})
			if err != nil {
				return nil, err
			}
			return importexport.StructToMap(resp.GetCreatePickingOrderItem().GetPickingOrderItem())
		},
	})
}
